package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApprovalLevels generated by hbm2java
 */
@Entity
@Table(name = "APPROVAL_LEVELS", catalog = "eHRM_JavaResearching")
public class ApprovalLevels implements java.io.Serializable {

	private Integer approvalLevelId;
	private Serializable roleName;
	private int orderIndex;
	private Set<LeaveTypes> leaveTypeses = new HashSet<LeaveTypes>(0);
	private Set<TaApprovalTypes> taApprovalTypeses = new HashSet<TaApprovalTypes>(0);
	private Set<ApprovalRoles> approvalRoleses = new HashSet<ApprovalRoles>(0);
	private Set<TripTypes> tripTypeses = new HashSet<TripTypes>(0);

	public ApprovalLevels() {
	}

	public ApprovalLevels(Serializable roleName, int orderIndex) {
		this.roleName = roleName;
		this.orderIndex = orderIndex;
	}

	public ApprovalLevels(Serializable roleName, int orderIndex, Set<LeaveTypes> leaveTypeses,
			Set<TaApprovalTypes> taApprovalTypeses, Set<ApprovalRoles> approvalRoleses, Set<TripTypes> tripTypeses) {
		this.roleName = roleName;
		this.orderIndex = orderIndex;
		this.leaveTypeses = leaveTypeses;
		this.taApprovalTypeses = taApprovalTypeses;
		this.approvalRoleses = approvalRoleses;
		this.tripTypeses = tripTypeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APPROVAL_LEVEL_ID", unique = true, nullable = false)
	public Integer getApprovalLevelId() {
		return this.approvalLevelId;
	}

	public void setApprovalLevelId(Integer approvalLevelId) {
		this.approvalLevelId = approvalLevelId;
	}

	@Column(name = "ROLE_NAME", nullable = false)
	public Serializable getRoleName() {
		return this.roleName;
	}

	public void setRoleName(Serializable roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ORDER_INDEX", nullable = false)
	public int getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(int orderIndex) {
		this.orderIndex = orderIndex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalLevels")
	public Set<LeaveTypes> getLeaveTypeses() {
		return this.leaveTypeses;
	}

	public void setLeaveTypeses(Set<LeaveTypes> leaveTypeses) {
		this.leaveTypeses = leaveTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalLevels")
	public Set<TaApprovalTypes> getTaApprovalTypeses() {
		return this.taApprovalTypeses;
	}

	public void setTaApprovalTypeses(Set<TaApprovalTypes> taApprovalTypeses) {
		this.taApprovalTypeses = taApprovalTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalLevels")
	public Set<ApprovalRoles> getApprovalRoleses() {
		return this.approvalRoleses;
	}

	public void setApprovalRoleses(Set<ApprovalRoles> approvalRoleses) {
		this.approvalRoleses = approvalRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalLevels")
	public Set<TripTypes> getTripTypeses() {
		return this.tripTypeses;
	}

	public void setTripTypeses(Set<TripTypes> tripTypeses) {
		this.tripTypeses = tripTypeses;
	}

}
