package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AprovalTripcosts generated by hbm2java
 */
@Entity
@Table(name = "APROVAL_TRIPCOSTS", catalog = "eHRM_JavaResearching")
public class AprovalTripcosts implements java.io.Serializable {

	private Integer aprovalCost;
	private Employees employees;
	private Locations locations;
	private Projects projects;
	private TripCosts tripCosts;
	private TripLocations tripLocations;
	private Date date;
	private BigDecimal breakfast;
	private BigDecimal lunch;
	private BigDecimal dinner;
	private Integer parentAllowanceId;
	private BigDecimal total;
	private Boolean isAproval;
	private Integer tripRequestId;
	private BigDecimal costAllowance;
	private Boolean isHalfDay;
	private Integer countApproval;
	private Date approvalDate;

	public AprovalTripcosts() {
	}

	public AprovalTripcosts(Employees employees, Locations locations, Projects projects, TripCosts tripCosts,
			TripLocations tripLocations, Date date, BigDecimal breakfast, BigDecimal lunch, BigDecimal dinner,
			Integer parentAllowanceId, BigDecimal total, Boolean isAproval, Integer tripRequestId,
			BigDecimal costAllowance, Boolean isHalfDay, Integer countApproval, Date approvalDate) {
		this.employees = employees;
		this.locations = locations;
		this.projects = projects;
		this.tripCosts = tripCosts;
		this.tripLocations = tripLocations;
		this.date = date;
		this.breakfast = breakfast;
		this.lunch = lunch;
		this.dinner = dinner;
		this.parentAllowanceId = parentAllowanceId;
		this.total = total;
		this.isAproval = isAproval;
		this.tripRequestId = tripRequestId;
		this.costAllowance = costAllowance;
		this.isHalfDay = isHalfDay;
		this.countApproval = countApproval;
		this.approvalDate = approvalDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APROVAL_COST", unique = true, nullable = false)
	public Integer getAprovalCost() {
		return this.aprovalCost;
	}

	public void setAprovalCost(Integer aprovalCost) {
		this.aprovalCost = aprovalCost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_ID")
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALLOWANCE_ID")
	public TripCosts getTripCosts() {
		return this.tripCosts;
	}

	public void setTripCosts(TripCosts tripCosts) {
		this.tripCosts = tripCosts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRIP_LOCATION_ID")
	public TripLocations getTripLocations() {
		return this.tripLocations;
	}

	public void setTripLocations(TripLocations tripLocations) {
		this.tripLocations = tripLocations;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE", length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "BREAKFAST", precision = 18)
	public BigDecimal getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(BigDecimal breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name = "LUNCH", precision = 18)
	public BigDecimal getLunch() {
		return this.lunch;
	}

	public void setLunch(BigDecimal lunch) {
		this.lunch = lunch;
	}

	@Column(name = "DINNER", precision = 18)
	public BigDecimal getDinner() {
		return this.dinner;
	}

	public void setDinner(BigDecimal dinner) {
		this.dinner = dinner;
	}

	@Column(name = "PARENT_ALLOWANCE_ID")
	public Integer getParentAllowanceId() {
		return this.parentAllowanceId;
	}

	public void setParentAllowanceId(Integer parentAllowanceId) {
		this.parentAllowanceId = parentAllowanceId;
	}

	@Column(name = "TOTAL", precision = 18)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "IS_APROVAL")
	public Boolean getIsAproval() {
		return this.isAproval;
	}

	public void setIsAproval(Boolean isAproval) {
		this.isAproval = isAproval;
	}

	@Column(name = "TRIP_REQUEST_ID")
	public Integer getTripRequestId() {
		return this.tripRequestId;
	}

	public void setTripRequestId(Integer tripRequestId) {
		this.tripRequestId = tripRequestId;
	}

	@Column(name = "COST_ALLOWANCE", precision = 18)
	public BigDecimal getCostAllowance() {
		return this.costAllowance;
	}

	public void setCostAllowance(BigDecimal costAllowance) {
		this.costAllowance = costAllowance;
	}

	@Column(name = "IS_HALF_DAY")
	public Boolean getIsHalfDay() {
		return this.isHalfDay;
	}

	public void setIsHalfDay(Boolean isHalfDay) {
		this.isHalfDay = isHalfDay;
	}

	@Column(name = "COUNT_APPROVAL")
	public Integer getCountApproval() {
		return this.countApproval;
	}

	public void setCountApproval(Integer countApproval) {
		this.countApproval = countApproval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPROVAL_DATE", length = 23)
	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

}
