package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AssessmentCriterias generated by hbm2java
 */
@Entity
@Table(name = "ASSESSMENT_CRITERIAS", catalog = "eHRM_JavaResearching")
public class AssessmentCriterias implements java.io.Serializable {

	private Integer assessmentCriteriaId;
	private Serializable assessmentCriteriaCode;
	private Serializable assessmentCriteriaName;
	private Integer orderIndex;
	private Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses = new HashSet<PerformanceAssessmentHistories>(
			0);

	public AssessmentCriterias() {
	}

	public AssessmentCriterias(Serializable assessmentCriteriaCode, Serializable assessmentCriteriaName) {
		this.assessmentCriteriaCode = assessmentCriteriaCode;
		this.assessmentCriteriaName = assessmentCriteriaName;
	}

	public AssessmentCriterias(Serializable assessmentCriteriaCode, Serializable assessmentCriteriaName,
			Integer orderIndex, Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses) {
		this.assessmentCriteriaCode = assessmentCriteriaCode;
		this.assessmentCriteriaName = assessmentCriteriaName;
		this.orderIndex = orderIndex;
		this.performanceAssessmentHistorieses = performanceAssessmentHistorieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ASSESSMENT_CRITERIA_ID", unique = true, nullable = false)
	public Integer getAssessmentCriteriaId() {
		return this.assessmentCriteriaId;
	}

	public void setAssessmentCriteriaId(Integer assessmentCriteriaId) {
		this.assessmentCriteriaId = assessmentCriteriaId;
	}

	@Column(name = "ASSESSMENT_CRITERIA_CODE", nullable = false)
	public Serializable getAssessmentCriteriaCode() {
		return this.assessmentCriteriaCode;
	}

	public void setAssessmentCriteriaCode(Serializable assessmentCriteriaCode) {
		this.assessmentCriteriaCode = assessmentCriteriaCode;
	}

	@Column(name = "ASSESSMENT_CRITERIA_NAME", nullable = false)
	public Serializable getAssessmentCriteriaName() {
		return this.assessmentCriteriaName;
	}

	public void setAssessmentCriteriaName(Serializable assessmentCriteriaName) {
		this.assessmentCriteriaName = assessmentCriteriaName;
	}

	@Column(name = "ORDER_INDEX")
	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assessmentCriterias")
	public Set<PerformanceAssessmentHistories> getPerformanceAssessmentHistorieses() {
		return this.performanceAssessmentHistorieses;
	}

	public void setPerformanceAssessmentHistorieses(
			Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses) {
		this.performanceAssessmentHistorieses = performanceAssessmentHistorieses;
	}

}
