package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailConfig generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_CONFIG", catalog = "eHRM_JavaResearching")
public class EmailConfig implements java.io.Serializable {

	private Integer emailId;
	private Serializable emailName;
	private Serializable emailSubject;
	private Serializable emailContent;
	private Date createDate;
	private Integer createBy;
	private Serializable emailCode;
	private Byte emailType;

	public EmailConfig() {
	}

	public EmailConfig(Serializable emailName, Serializable emailSubject, Serializable emailContent, Date createDate,
			Integer createBy, Serializable emailCode, Byte emailType) {
		this.emailName = emailName;
		this.emailSubject = emailSubject;
		this.emailContent = emailContent;
		this.createDate = createDate;
		this.createBy = createBy;
		this.emailCode = emailCode;
		this.emailType = emailType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMAIL_ID", unique = true, nullable = false)
	public Integer getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	@Column(name = "EMAIL_NAME")
	public Serializable getEmailName() {
		return this.emailName;
	}

	public void setEmailName(Serializable emailName) {
		this.emailName = emailName;
	}

	@Column(name = "EMAIL_SUBJECT")
	public Serializable getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(Serializable emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "EMAIL_CONTENT")
	public Serializable getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(Serializable emailContent) {
		this.emailContent = emailContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_BY")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "EMAIL_CODE")
	public Serializable getEmailCode() {
		return this.emailCode;
	}

	public void setEmailCode(Serializable emailCode) {
		this.emailCode = emailCode;
	}

	@Column(name = "EMAIL_TYPE")
	public Byte getEmailType() {
		return this.emailType;
	}

	public void setEmailType(Byte emailType) {
		this.emailType = emailType;
	}

}
