package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEES", catalog = "eHRM_JavaResearching")
public class Employees implements java.io.Serializable {

	private Integer employeeId;
	private Employees employees;
	private MasterDatas masterDatasByGenderId;
	private MasterDatas masterDatasByTitleId;
	private MasterDatas masterDatasByMaritalStatusId;
	private MasterDatas masterDatasByNationalityId;
	private String firstName;
	private String lastName;
	private String middleName;
	private Date dateOfBirth;
	private String birthLocation;
	private String identifyCompany;
	private boolean active;
	private boolean isForeigner;
	private String photo;
	private String idCard;
	private Date idCardIssuedDate;
	private String idCardIssuedPlace;
	private String passportNumber;
	private Date passportIssuedDate;
	private String passportIssuedPlace;
	private Date passportExpiryDate;
	private String otherName;
	private String moreInformation;
	private String pitCode;
	private Date workingStartDate;
	private Date probationEndDate;
	private String biographical;
	private String cvContent;
	private String socialBookNo;
	private boolean isInUnion;
	private BigDecimal transportationAllowance;
	private Date registerStopWorking;
	private Date actualStopWorking;
	private String reasonForLeaving;
	private String oweCompanyEquipments;
	private BigDecimal oweCompanyMoney;
	private String oweCompanyStatus;
	private String middleNameNative;
	private String firstNameNative;
	private String lastNameNative;
	private String nativeCountry;
	private Date placeOfBirth;
	private String permanentAddressEnglish;
	private String permanentAddressVietnamese;
	private String currentSalaryNet;
	private String currentSalaryGross;
	private Date titleDate;
	private Date joinDate;
	private Date serviceTime;
	private Integer probationNet;
	private String workingStatus;
	private String englishAbility;
	private Integer toeicScore;
	private String currentDepartment;
	private String people;
	private Date resignDate;
	private Date lastDay;
	private Date officialLastDay;
	private String remark;
	private String accountNumber;
	private String japaneseAbility;
	private String foreignerHomephone;
	private String foreignerCellphone;
	private String foreignerContact;
	private String currentJobDescrip;
	private Boolean isreplace;
	private Boolean iscashhandler;
	private Integer reasonId;
	private String attendancecode;
	private Set<TripRequestHistories> tripRequestHistorieses = new HashSet<TripRequestHistories>(0);
	private Set<EmployeeLanguage> employeeLanguages = new HashSet<EmployeeLanguage>(0);
	private Set<LeaveCarryForwardRequestHistories> leaveCarryForwardRequestHistorieses = new HashSet<LeaveCarryForwardRequestHistories>(
			0);
	private Set<ProjectDefaults> projectDefaultses = new HashSet<ProjectDefaults>(0);
	private Set<OutBreakRequests> outBreakRequestses = new HashSet<OutBreakRequests>(0);
	private Set<EmployeeAttachmentFiles> employeeAttachmentFileses = new HashSet<EmployeeAttachmentFiles>(0);
	private Set<EmployeeWorkingTitles> employeeWorkingTitleses = new HashSet<EmployeeWorkingTitles>(0);
	private Set<IncomeConfigs> incomeConfigses = new HashSet<IncomeConfigs>(0);
	private Set<EmployeeWorkingDays> employeeWorkingDayses = new HashSet<EmployeeWorkingDays>(0);
	private Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses = new HashSet<LeaveCarryForwardRequests>(0);
	private Set<EmployeeEmails> employeeEmailses = new HashSet<EmployeeEmails>(0);
	private Set<EmployeeEducationLevels> employeeEducationLevelses = new HashSet<EmployeeEducationLevels>(0);
	private Set<EmployeeUnits> employeeUnitses = new HashSet<EmployeeUnits>(0);
	private Set<LeaveRequests> leaveRequestses = new HashSet<LeaveRequests>(0);
	private Set<EmployeeKpi> employeeKpisForEmployeeId = new HashSet<EmployeeKpi>(0);
	private Set<TaOvertimeSchedulesHistories> taOvertimeSchedulesHistorieses = new HashSet<TaOvertimeSchedulesHistories>(
			0);
	private Set<Employees> employeeses = new HashSet<Employees>(0);
	private Set<ManagerOnsides> managerOnsideses = new HashSet<ManagerOnsides>(0);
	private Set<EmployeeManagers> employeeManagersesForEmployeeId = new HashSet<EmployeeManagers>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<RoleDepartments> roleDepartmentses = new HashSet<RoleDepartments>(0);
	private Set<Units> unitsesForHrManagerId = new HashSet<Units>(0);
	private Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdEdited = new HashSet<TaOvertimeSchedules>(0);
	private Set<EmployeeMboRecords> employeeMboRecordses = new HashSet<EmployeeMboRecords>(0);
	private Set<PersonalTargets> personalTargetses = new HashSet<PersonalTargets>(0);
	private Set<EmployeeDisciplines> employeeDisciplineses = new HashSet<EmployeeDisciplines>(0);
	private Set<PerformanceAssessments> performanceAssessmentses = new HashSet<PerformanceAssessments>(0);
	private Set<EmployeeIncomeTaxStats> employeeIncomeTaxStatses = new HashSet<EmployeeIncomeTaxStats>(0);
	private Set<EmployeeEducations> employeeEducationses = new HashSet<EmployeeEducations>(0);
	private Set<EmployeeIncomes> employeeIncomeses = new HashSet<EmployeeIncomes>(0);
	private Set<EmployeeAccounts> employeeAccountses = new HashSet<EmployeeAccounts>(0);
	private Set<Outsides> outsideses = new HashSet<Outsides>(0);
	private Set<LeaveRequestHistories> leaveRequestHistorieses = new HashSet<LeaveRequestHistories>(0);
	private Set<EmployeeAssignments> employeeAssignmentses = new HashSet<EmployeeAssignments>(0);
	private Set<EmployeeRanks> employeeRankses = new HashSet<EmployeeRanks>(0);
	private Set<EmployeeFiles> employeeFileses = new HashSet<EmployeeFiles>(0);
	private Set<EmployeeKaizenAwards> employeeKaizenAwardses = new HashSet<EmployeeKaizenAwards>(0);
	private Set<EmployeeIncomeStats> employeeIncomeStatses = new HashSet<EmployeeIncomeStats>(0);
	private Set<EmployeeMissions> employeeMissionses = new HashSet<EmployeeMissions>(0);
	private Set<LogTimeSheet> logTimeSheets = new HashSet<LogTimeSheet>(0);
	private Set<EmployeeWorkbooks> employeeWorkbookses = new HashSet<EmployeeWorkbooks>(0);
	private Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeId = new HashSet<TaOvertimeSchedules>(0);
	private Set<EmployeeContracts> employeeContractses = new HashSet<EmployeeContracts>(0);
	private Set<Employees> employeeses_1 = new HashSet<Employees>(0);
	private Set<PdfFile> pdfFiles = new HashSet<PdfFile>(0);
	private Set<EmployeeManagers> employeeManagersesForManagerId = new HashSet<EmployeeManagers>(0);
	private Set<EmployeePhones> employeePhoneses = new HashSet<EmployeePhones>(0);
	private Set<AprovalTripcosts> aprovalTripcostses = new HashSet<AprovalTripcosts>(0);
	private Set<EmployeeHierarchicals> employeeHierarchicalses = new HashSet<EmployeeHierarchicals>(0);
	private Set<EmployeeTaxes> employeeTaxeses = new HashSet<EmployeeTaxes>(0);
	private Set<TimeSheets> timeSheetses = new HashSet<TimeSheets>(0);
	private Set<TaWorkingSchedules> taWorkingScheduleses = new HashSet<TaWorkingSchedules>(0);
	private Set<Units> unitsesForManagerId = new HashSet<Units>(0);
	private Set<OutBreakRequestHistories> outBreakRequestHistorieses = new HashSet<OutBreakRequestHistories>(0);
	private Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdCreated = new HashSet<TaOvertimeSchedules>(0);
	private Set<EmployeePreviewjob> employeePreviewjobs = new HashSet<EmployeePreviewjob>(0);
	private Set<EmployeeWages> employeeWageses = new HashSet<EmployeeWages>(0);
	private Set<TripRequests> tripRequestses = new HashSet<TripRequests>(0);
	private Set<EmployeeRelatives> employeeRelativeses = new HashSet<EmployeeRelatives>(0);
	private Set<EmployeeKpi> employeeKpisForModifiedBy = new HashSet<EmployeeKpi>(0);
	private Set<EmployeeAddresses> employeeAddresseses = new HashSet<EmployeeAddresses>(0);
	private Set<EmployeeKpi> employeeKpisForCreateBy = new HashSet<EmployeeKpi>(0);
	private Set<LeaveEmployeeBalances> leaveEmployeeBalanceses = new HashSet<LeaveEmployeeBalances>(0);
	private Set<TaEmployeeTimesheets> taEmployeeTimesheetses = new HashSet<TaEmployeeTimesheets>(0);

	public Employees() {
	}

	public Employees(MasterDatas masterDatasByGenderId, MasterDatas masterDatasByMaritalStatusId,
			MasterDatas masterDatasByNationalityId, String firstName, String lastName,
			String middleName, String identifyCompany, boolean active, boolean isForeigner,
			boolean isInUnion) {
		this.masterDatasByGenderId = masterDatasByGenderId;
		this.masterDatasByMaritalStatusId = masterDatasByMaritalStatusId;
		this.masterDatasByNationalityId = masterDatasByNationalityId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.identifyCompany = identifyCompany;
		this.active = active;
		this.isForeigner = isForeigner;
		this.isInUnion = isInUnion;
	}

	public Employees(MasterDatas masterDatasByTitleId,String firstName,String middleName,String lastName,MasterDatas masterDatasByGenderId,
			String identityCompany,String attendancecode, String firstNameNative, String lastNameNative, String permanentAddressVN, Date dateOfBirth,
			String numberOfSocialBook, MasterDatas nationality, Boolean isForeigner,String foreignerContract,String foreignerCellphone,String foreignerAddress,
			String idCard, Date idCardIssuedDate,String idCardIssuedPlace,Date passportExpiryDate,String pitCode,Date startDate,Date registedStopWorkingDate,
			Date actualStopWorkingDate,Boolean isReplace,String permanentAddressENG,String birthLocation,Boolean active,MasterDatas martialStatus,String nativeCountry,String passportNumber,
			Date passportIssueDate,String passportIssuePlace,String moreInformation,Date endOfProbation,String reason,Boolean isInUnion
			) {
			this.masterDatasByTitleId = masterDatasByTitleId;
			this.firstName = firstName;
			this.middleName = middleName;
			this.lastName = lastName;
			this.masterDatasByGenderId = masterDatasByGenderId;
			this.identifyCompany = identityCompany;
			this.attendancecode = attendancecode;
			this.firstNameNative = firstNameNative;
			this.lastNameNative = lastNameNative;
			this.permanentAddressVietnamese = permanentAddressVN;
			this.dateOfBirth = dateOfBirth;
			this.socialBookNo = numberOfSocialBook;
			this.masterDatasByNationalityId = nationality;
			this.isForeigner = isForeigner;
			this.foreignerContact = foreignerContract;
			this.foreignerCellphone = foreignerCellphone;
			this.foreignerHomephone = foreignerAddress;
			this.idCard = idCard;
			this.idCardIssuedDate = idCardIssuedDate;
			this.idCardIssuedPlace = idCardIssuedPlace;
			this.passportExpiryDate = passportExpiryDate;
			this.pitCode = pitCode;
			this.workingStartDate = startDate;
			this.registerStopWorking = registedStopWorkingDate;
			this.actualStopWorking = actualStopWorkingDate;
			this.isreplace = isReplace;
			this.permanentAddressEnglish = permanentAddressENG;
			this.birthLocation = birthLocation;
			this.active = active;
			this.masterDatasByMaritalStatusId = martialStatus;
			this.nativeCountry = nativeCountry;
			this.passportNumber = passportNumber;
			this.passportIssuedDate = passportIssueDate;
			this.passportIssuedPlace = passportIssuePlace;
			this.moreInformation = moreInformation;
			this.probationEndDate = endOfProbation;
			this.reasonForLeaving = reason;
			this.isInUnion = isInUnion;
	}
	
	public Employees(Employees employees, MasterDatas masterDatasByGenderId, MasterDatas masterDatasByTitleId,
			MasterDatas masterDatasByMaritalStatusId, MasterDatas masterDatasByNationalityId, String firstName,
			String lastName, String middleName, Date dateOfBirth, String birthLocation,
			String identifyCompany, boolean active, boolean isForeigner, String photo, String idCard,
			Date idCardIssuedDate, String idCardIssuedPlace, String passportNumber, Date passportIssuedDate,
			String passportIssuedPlace, Date passportExpiryDate, String otherName,
			String moreInformation, String pitCode, Date workingStartDate, Date probationEndDate,
			String biographical, String cvContent, String socialBookNo, boolean isInUnion,
			BigDecimal transportationAllowance, Date registerStopWorking, Date actualStopWorking,
			String reasonForLeaving, String oweCompanyEquipments, BigDecimal oweCompanyMoney,
			String oweCompanyStatus, String middleNameNative, String firstNameNative,
			String lastNameNative, String nativeCountry, Date placeOfBirth,
			String permanentAddressEnglish, String permanentAddressVietnamese,
			String currentSalaryNet, String currentSalaryGross, Date titleDate, Date joinDate,
			Date serviceTime, Integer probationNet, String workingStatus, String englishAbility,
			Integer toeicScore, String currentDepartment, String people, Date resignDate, Date lastDay,
			Date officialLastDay, String remark, String accountNumber, String japaneseAbility,
			String foreignerHomephone, String foreignerCellphone, String foreignerContact,
			String currentJobDescrip, Boolean isreplace, Boolean iscashhandler, Integer reasonId,
			String attendancecode, Set<TripRequestHistories> tripRequestHistorieses,
			Set<EmployeeLanguage> employeeLanguages,
			Set<LeaveCarryForwardRequestHistories> leaveCarryForwardRequestHistorieses,
			Set<ProjectDefaults> projectDefaultses, Set<OutBreakRequests> outBreakRequestses,
			Set<EmployeeAttachmentFiles> employeeAttachmentFileses, Set<EmployeeWorkingTitles> employeeWorkingTitleses,
			Set<IncomeConfigs> incomeConfigses, Set<EmployeeWorkingDays> employeeWorkingDayses,
			Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses, Set<EmployeeEmails> employeeEmailses,
			Set<EmployeeEducationLevels> employeeEducationLevelses, Set<EmployeeUnits> employeeUnitses,
			Set<LeaveRequests> leaveRequestses, Set<EmployeeKpi> employeeKpisForEmployeeId,
			Set<TaOvertimeSchedulesHistories> taOvertimeSchedulesHistorieses, Set<Employees> employeeses,
			Set<ManagerOnsides> managerOnsideses, Set<EmployeeManagers> employeeManagersesForEmployeeId,
			Set<Users> userses, Set<RoleDepartments> roleDepartmentses, Set<Units> unitsesForHrManagerId,
			Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdEdited,
			Set<EmployeeMboRecords> employeeMboRecordses, Set<PersonalTargets> personalTargetses,
			Set<EmployeeDisciplines> employeeDisciplineses, Set<PerformanceAssessments> performanceAssessmentses,
			Set<EmployeeIncomeTaxStats> employeeIncomeTaxStatses, Set<EmployeeEducations> employeeEducationses,
			Set<EmployeeIncomes> employeeIncomeses, Set<EmployeeAccounts> employeeAccountses, Set<Outsides> outsideses,
			Set<LeaveRequestHistories> leaveRequestHistorieses, Set<EmployeeAssignments> employeeAssignmentses,
			Set<EmployeeRanks> employeeRankses, Set<EmployeeFiles> employeeFileses,
			Set<EmployeeKaizenAwards> employeeKaizenAwardses, Set<EmployeeIncomeStats> employeeIncomeStatses,
			Set<EmployeeMissions> employeeMissionses, Set<LogTimeSheet> logTimeSheets,
			Set<EmployeeWorkbooks> employeeWorkbookses, Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeId,
			Set<EmployeeContracts> employeeContractses, Set<Employees> employeeses_1, Set<PdfFile> pdfFiles,
			Set<EmployeeManagers> employeeManagersesForManagerId, Set<EmployeePhones> employeePhoneses,
			Set<AprovalTripcosts> aprovalTripcostses, Set<EmployeeHierarchicals> employeeHierarchicalses,
			Set<EmployeeTaxes> employeeTaxeses, Set<TimeSheets> timeSheetses,
			Set<TaWorkingSchedules> taWorkingScheduleses, Set<Units> unitsesForManagerId,
			Set<OutBreakRequestHistories> outBreakRequestHistorieses,
			Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdCreated,
			Set<EmployeePreviewjob> employeePreviewjobs, Set<EmployeeWages> employeeWageses,
			Set<TripRequests> tripRequestses, Set<EmployeeRelatives> employeeRelativeses,
			Set<EmployeeKpi> employeeKpisForModifiedBy, Set<EmployeeAddresses> employeeAddresseses,
			Set<EmployeeKpi> employeeKpisForCreateBy, Set<LeaveEmployeeBalances> leaveEmployeeBalanceses,
			Set<TaEmployeeTimesheets> taEmployeeTimesheetses) {
		this.employees = employees;
		this.masterDatasByGenderId = masterDatasByGenderId;
		this.masterDatasByTitleId = masterDatasByTitleId;
		this.masterDatasByMaritalStatusId = masterDatasByMaritalStatusId;
		this.masterDatasByNationalityId = masterDatasByNationalityId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.dateOfBirth = dateOfBirth;
		this.birthLocation = birthLocation;
		this.identifyCompany = identifyCompany;
		this.active = active;
		this.isForeigner = isForeigner;
		this.photo = photo;
		this.idCard = idCard;
		this.idCardIssuedDate = idCardIssuedDate;
		this.idCardIssuedPlace = idCardIssuedPlace;
		this.passportNumber = passportNumber;
		this.passportIssuedDate = passportIssuedDate;
		this.passportIssuedPlace = passportIssuedPlace;
		this.passportExpiryDate = passportExpiryDate;
		this.otherName = otherName;
		this.moreInformation = moreInformation;
		this.pitCode = pitCode;
		this.workingStartDate = workingStartDate;
		this.probationEndDate = probationEndDate;
		this.biographical = biographical;
		this.cvContent = cvContent;
		this.socialBookNo = socialBookNo;
		this.isInUnion = isInUnion;
		this.transportationAllowance = transportationAllowance;
		this.registerStopWorking = registerStopWorking;
		this.actualStopWorking = actualStopWorking;
		this.reasonForLeaving = reasonForLeaving;
		this.oweCompanyEquipments = oweCompanyEquipments;
		this.oweCompanyMoney = oweCompanyMoney;
		this.oweCompanyStatus = oweCompanyStatus;
		this.middleNameNative = middleNameNative;
		this.firstNameNative = firstNameNative;
		this.lastNameNative = lastNameNative;
		this.nativeCountry = nativeCountry;
		this.placeOfBirth = placeOfBirth;
		this.permanentAddressEnglish = permanentAddressEnglish;
		this.permanentAddressVietnamese = permanentAddressVietnamese;
		this.currentSalaryNet = currentSalaryNet;
		this.currentSalaryGross = currentSalaryGross;
		this.titleDate = titleDate;
		this.joinDate = joinDate;
		this.serviceTime = serviceTime;
		this.probationNet = probationNet;
		this.workingStatus = workingStatus;
		this.englishAbility = englishAbility;
		this.toeicScore = toeicScore;
		this.currentDepartment = currentDepartment;
		this.people = people;
		this.resignDate = resignDate;
		this.lastDay = lastDay;
		this.officialLastDay = officialLastDay;
		this.remark = remark;
		this.accountNumber = accountNumber;
		this.japaneseAbility = japaneseAbility;
		this.foreignerHomephone = foreignerHomephone;
		this.foreignerCellphone = foreignerCellphone;
		this.foreignerContact = foreignerContact;
		this.currentJobDescrip = currentJobDescrip;
		this.isreplace = isreplace;
		this.iscashhandler = iscashhandler;
		this.reasonId = reasonId;
		this.attendancecode = attendancecode;
		this.tripRequestHistorieses = tripRequestHistorieses;
		this.employeeLanguages = employeeLanguages;
		this.leaveCarryForwardRequestHistorieses = leaveCarryForwardRequestHistorieses;
		this.projectDefaultses = projectDefaultses;
		this.outBreakRequestses = outBreakRequestses;
		this.employeeAttachmentFileses = employeeAttachmentFileses;
		this.employeeWorkingTitleses = employeeWorkingTitleses;
		this.incomeConfigses = incomeConfigses;
		this.employeeWorkingDayses = employeeWorkingDayses;
		this.leaveCarryForwardRequestses = leaveCarryForwardRequestses;
		this.employeeEmailses = employeeEmailses;
		this.employeeEducationLevelses = employeeEducationLevelses;
		this.employeeUnitses = employeeUnitses;
		this.leaveRequestses = leaveRequestses;
		this.employeeKpisForEmployeeId = employeeKpisForEmployeeId;
		this.taOvertimeSchedulesHistorieses = taOvertimeSchedulesHistorieses;
		this.employeeses = employeeses;
		this.managerOnsideses = managerOnsideses;
		this.employeeManagersesForEmployeeId = employeeManagersesForEmployeeId;
		this.userses = userses;
		this.roleDepartmentses = roleDepartmentses;
		this.unitsesForHrManagerId = unitsesForHrManagerId;
		this.taOvertimeSchedulesesForEmployeeIdEdited = taOvertimeSchedulesesForEmployeeIdEdited;
		this.employeeMboRecordses = employeeMboRecordses;
		this.personalTargetses = personalTargetses;
		this.employeeDisciplineses = employeeDisciplineses;
		this.performanceAssessmentses = performanceAssessmentses;
		this.employeeIncomeTaxStatses = employeeIncomeTaxStatses;
		this.employeeEducationses = employeeEducationses;
		this.employeeIncomeses = employeeIncomeses;
		this.employeeAccountses = employeeAccountses;
		this.outsideses = outsideses;
		this.leaveRequestHistorieses = leaveRequestHistorieses;
		this.employeeAssignmentses = employeeAssignmentses;
		this.employeeRankses = employeeRankses;
		this.employeeFileses = employeeFileses;
		this.employeeKaizenAwardses = employeeKaizenAwardses;
		this.employeeIncomeStatses = employeeIncomeStatses;
		this.employeeMissionses = employeeMissionses;
		this.logTimeSheets = logTimeSheets;
		this.employeeWorkbookses = employeeWorkbookses;
		this.taOvertimeSchedulesesForEmployeeId = taOvertimeSchedulesesForEmployeeId;
		this.employeeContractses = employeeContractses;
		this.employeeses_1 = employeeses_1;
		this.pdfFiles = pdfFiles;
		this.employeeManagersesForManagerId = employeeManagersesForManagerId;
		this.employeePhoneses = employeePhoneses;
		this.aprovalTripcostses = aprovalTripcostses;
		this.employeeHierarchicalses = employeeHierarchicalses;
		this.employeeTaxeses = employeeTaxeses;
		this.timeSheetses = timeSheetses;
		this.taWorkingScheduleses = taWorkingScheduleses;
		this.unitsesForManagerId = unitsesForManagerId;
		this.outBreakRequestHistorieses = outBreakRequestHistorieses;
		this.taOvertimeSchedulesesForEmployeeIdCreated = taOvertimeSchedulesesForEmployeeIdCreated;
		this.employeePreviewjobs = employeePreviewjobs;
		this.employeeWageses = employeeWageses;
		this.tripRequestses = tripRequestses;
		this.employeeRelativeses = employeeRelativeses;
		this.employeeKpisForModifiedBy = employeeKpisForModifiedBy;
		this.employeeAddresseses = employeeAddresseses;
		this.employeeKpisForCreateBy = employeeKpisForCreateBy;
		this.leaveEmployeeBalanceses = leaveEmployeeBalanceses;
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMPLOYEE_ID", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEEREPLACEID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENDER_ID", nullable = false)
	public MasterDatas getMasterDatasByGenderId() {
		return this.masterDatasByGenderId;
	}

	public void setMasterDatasByGenderId(MasterDatas masterDatasByGenderId) {
		this.masterDatasByGenderId = masterDatasByGenderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TITLE_ID")
	public MasterDatas getMasterDatasByTitleId() {
		return this.masterDatasByTitleId;
	}

	public void setMasterDatasByTitleId(MasterDatas masterDatasByTitleId) {
		this.masterDatasByTitleId = masterDatasByTitleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MARITAL_STATUS_ID", nullable = false)
	public MasterDatas getMasterDatasByMaritalStatusId() {
		return this.masterDatasByMaritalStatusId;
	}

	public void setMasterDatasByMaritalStatusId(MasterDatas masterDatasByMaritalStatusId) {
		this.masterDatasByMaritalStatusId = masterDatasByMaritalStatusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NATIONALITY_ID", nullable = false)
	public MasterDatas getMasterDatasByNationalityId() {
		return this.masterDatasByNationalityId;
	}

	public void setMasterDatasByNationalityId(MasterDatas masterDatasByNationalityId) {
		this.masterDatasByNationalityId = masterDatasByNationalityId;
	}

	@Column(name = "FIRST_NAME", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MIDDLE_NAME", nullable = false)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OF_BIRTH", length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "BIRTH_LOCATION")
	public String getBirthLocation() {
		return this.birthLocation;
	}

	public void setBirthLocation(String birthLocation) {
		this.birthLocation = birthLocation;
	}

	@Column(name = "IDENTIFY_COMPANY", nullable = false)
	public String getIdentifyCompany() {
		return this.identifyCompany;
	}

	public void setIdentifyCompany(String identifyCompany) {
		this.identifyCompany = identifyCompany;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "IS_FOREIGNER", nullable = false)
	public boolean isIsForeigner() {
		return this.isForeigner;
	}

	public void setIsForeigner(boolean isForeigner) {
		this.isForeigner = isForeigner;
	}

	@Column(name = "PHOTO")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "ID_CARD")
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ID_CARD_ISSUED_DATE", length = 10)
	public Date getIdCardIssuedDate() {
		return this.idCardIssuedDate;
	}

	public void setIdCardIssuedDate(Date idCardIssuedDate) {
		this.idCardIssuedDate = idCardIssuedDate;
	}

	@Column(name = "ID_CARD_ISSUED_PLACE")
	public String getIdCardIssuedPlace() {
		return this.idCardIssuedPlace;
	}

	public void setIdCardIssuedPlace(String idCardIssuedPlace) {
		this.idCardIssuedPlace = idCardIssuedPlace;
	}

	@Column(name = "PASSPORT_NUMBER")
	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PASSPORT_ISSUED_DATE", length = 10)
	public Date getPassportIssuedDate() {
		return this.passportIssuedDate;
	}

	public void setPassportIssuedDate(Date passportIssuedDate) {
		this.passportIssuedDate = passportIssuedDate;
	}

	@Column(name = "PASSPORT_ISSUED_PLACE")
	public String getPassportIssuedPlace() {
		return this.passportIssuedPlace;
	}

	public void setPassportIssuedPlace(String passportIssuedPlace) {
		this.passportIssuedPlace = passportIssuedPlace;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PASSPORT_EXPIRY_DATE", length = 10)
	public Date getPassportExpiryDate() {
		return this.passportExpiryDate;
	}

	public void setPassportExpiryDate(Date passportExpiryDate) {
		this.passportExpiryDate = passportExpiryDate;
	}

	@Column(name = "OTHER_NAME")
	public String getOtherName() {
		return this.otherName;
	}

	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}

	@Column(name = "MORE_INFORMATION")
	public String getMoreInformation() {
		return this.moreInformation;
	}

	public void setMoreInformation(String moreInformation) {
		this.moreInformation = moreInformation;
	}

	@Column(name = "PIT_CODE")
	public String getPitCode() {
		return this.pitCode;
	}

	public void setPitCode(String pitCode) {
		this.pitCode = pitCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "WORKING_START_DATE", length = 10)
	public Date getWorkingStartDate() {
		return this.workingStartDate;
	}

	public void setWorkingStartDate(Date workingStartDate) {
		this.workingStartDate = workingStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PROBATION_END_DATE", length = 10)
	public Date getProbationEndDate() {
		return this.probationEndDate;
	}

	public void setProbationEndDate(Date probationEndDate) {
		this.probationEndDate = probationEndDate;
	}

	@Column(name = "BIOGRAPHICAL")
	public String getBiographical() {
		return this.biographical;
	}

	public void setBiographical(String biographical) {
		this.biographical = biographical;
	}

	@Column(name = "CV_CONTENT")
	public String getCvContent() {
		return this.cvContent;
	}

	public void setCvContent(String cvContent) {
		this.cvContent = cvContent;
	}

	@Column(name = "SOCIAL_BOOK_NO")
	public String getSocialBookNo() {
		return this.socialBookNo;
	}

	public void setSocialBookNo(String socialBookNo) {
		this.socialBookNo = socialBookNo;
	}

	@Column(name = "IS_IN_UNION", nullable = false)
	public boolean isIsInUnion() {
		return this.isInUnion;
	}

	public void setIsInUnion(boolean isInUnion) {
		this.isInUnion = isInUnion;
	}

	@Column(name = "TRANSPORTATION_ALLOWANCE", precision = 18, scale = 4)
	public BigDecimal getTransportationAllowance() {
		return this.transportationAllowance;
	}

	public void setTransportationAllowance(BigDecimal transportationAllowance) {
		this.transportationAllowance = transportationAllowance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTER_STOP_WORKING", length = 10)
	public Date getRegisterStopWorking() {
		return this.registerStopWorking;
	}

	public void setRegisterStopWorking(Date registerStopWorking) {
		this.registerStopWorking = registerStopWorking;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACTUAL_STOP_WORKING", length = 10)
	public Date getActualStopWorking() {
		return this.actualStopWorking;
	}

	public void setActualStopWorking(Date actualStopWorking) {
		this.actualStopWorking = actualStopWorking;
	}

	@Column(name = "REASON_FOR_LEAVING")
	public String getReasonForLeaving() {
		return this.reasonForLeaving;
	}

	public void setReasonForLeaving(String reasonForLeaving) {
		this.reasonForLeaving = reasonForLeaving;
	}

	@Column(name = "OWE_COMPANY_EQUIPMENTS")
	public String getOweCompanyEquipments() {
		return this.oweCompanyEquipments;
	}

	public void setOweCompanyEquipments(String oweCompanyEquipments) {
		this.oweCompanyEquipments = oweCompanyEquipments;
	}

	@Column(name = "OWE_COMPANY_MONEY", precision = 18, scale = 4)
	public BigDecimal getOweCompanyMoney() {
		return this.oweCompanyMoney;
	}

	public void setOweCompanyMoney(BigDecimal oweCompanyMoney) {
		this.oweCompanyMoney = oweCompanyMoney;
	}

	@Column(name = "OWE_COMPANY_STATUS")
	public String getOweCompanyStatus() {
		return this.oweCompanyStatus;
	}

	public void setOweCompanyStatus(String oweCompanyStatus) {
		this.oweCompanyStatus = oweCompanyStatus;
	}

	@Column(name = "MIDDLE_NAME_NATIVE")
	public String getMiddleNameNative() {
		return this.middleNameNative;
	}

	public void setMiddleNameNative(String middleNameNative) {
		this.middleNameNative = middleNameNative;
	}

	@Column(name = "FIRST_NAME_NATIVE")
	public String getFirstNameNative() {
		return this.firstNameNative;
	}

	public void setFirstNameNative(String firstNameNative) {
		this.firstNameNative = firstNameNative;
	}

	@Column(name = "LAST_NAME_NATIVE")
	public String getLastNameNative() {
		return this.lastNameNative;
	}

	public void setLastNameNative(String lastNameNative) {
		this.lastNameNative = lastNameNative;
	}

	@Column(name = "NATIVE_COUNTRY")
	public String getNativeCountry() {
		return this.nativeCountry;
	}

	public void setNativeCountry(String nativeCountry) {
		this.nativeCountry = nativeCountry;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PLACE_OF_BIRTH", length = 10)
	public Date getPlaceOfBirth() {
		return this.placeOfBirth;
	}

	public void setPlaceOfBirth(Date placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	@Column(name = "PERMANENT_ADDRESS_ENGLISH")
	public String getPermanentAddressEnglish() {
		return this.permanentAddressEnglish;
	}

	public void setPermanentAddressEnglish(String permanentAddressEnglish) {
		this.permanentAddressEnglish = permanentAddressEnglish;
	}

	@Column(name = "PERMANENT_ADDRESS_VIETNAMESE")
	public String getPermanentAddressVietnamese() {
		return this.permanentAddressVietnamese;
	}

	public void setPermanentAddressVietnamese(String permanentAddressVietnamese) {
		this.permanentAddressVietnamese = permanentAddressVietnamese;
	}

	@Column(name = "CURRENT_SALARY_NET")
	public String getCurrentSalaryNet() {
		return this.currentSalaryNet;
	}

	public void setCurrentSalaryNet(String currentSalaryNet) {
		this.currentSalaryNet = currentSalaryNet;
	}

	@Column(name = "CURRENT_SALARY_GROSS")
	public String getCurrentSalaryGross() {
		return this.currentSalaryGross;
	}

	public void setCurrentSalaryGross(String currentSalaryGross) {
		this.currentSalaryGross = currentSalaryGross;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TITLE_DATE", length = 10)
	public Date getTitleDate() {
		return this.titleDate;
	}

	public void setTitleDate(Date titleDate) {
		this.titleDate = titleDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOIN_DATE", length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SERVICE_TIME", length = 10)
	public Date getServiceTime() {
		return this.serviceTime;
	}

	public void setServiceTime(Date serviceTime) {
		this.serviceTime = serviceTime;
	}

	@Column(name = "PROBATION_NET")
	public Integer getProbationNet() {
		return this.probationNet;
	}

	public void setProbationNet(Integer probationNet) {
		this.probationNet = probationNet;
	}

	@Column(name = "WORKING_STATUS")
	public String getWorkingStatus() {
		return this.workingStatus;
	}

	public void setWorkingStatus(String workingStatus) {
		this.workingStatus = workingStatus;
	}

	@Column(name = "ENGLISH_ABILITY")
	public String getEnglishAbility() {
		return this.englishAbility;
	}

	public void setEnglishAbility(String englishAbility) {
		this.englishAbility = englishAbility;
	}

	@Column(name = "TOEIC_SCORE")
	public Integer getToeicScore() {
		return this.toeicScore;
	}

	public void setToeicScore(Integer toeicScore) {
		this.toeicScore = toeicScore;
	}

	@Column(name = "CURRENT_DEPARTMENT")
	public String getCurrentDepartment() {
		return this.currentDepartment;
	}

	public void setCurrentDepartment(String currentDepartment) {
		this.currentDepartment = currentDepartment;
	}

	@Column(name = "PEOPLE")
	public String getPeople() {
		return this.people;
	}

	public void setPeople(String people) {
		this.people = people;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RESIGN_DATE", length = 10)
	public Date getResignDate() {
		return this.resignDate;
	}

	public void setResignDate(Date resignDate) {
		this.resignDate = resignDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_DAY", length = 10)
	public Date getLastDay() {
		return this.lastDay;
	}

	public void setLastDay(Date lastDay) {
		this.lastDay = lastDay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OFFICIAL_LAST_DAY", length = 10)
	public Date getOfficialLastDay() {
		return this.officialLastDay;
	}

	public void setOfficialLastDay(Date officialLastDay) {
		this.officialLastDay = officialLastDay;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ACCOUNT_NUMBER")
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "JAPANESE_ABILITY")
	public String getJapaneseAbility() {
		return this.japaneseAbility;
	}

	public void setJapaneseAbility(String japaneseAbility) {
		this.japaneseAbility = japaneseAbility;
	}

	@Column(name = "FOREIGNER_HOMEPHONE")
	public String getForeignerHomephone() {
		return this.foreignerHomephone;
	}

	public void setForeignerHomephone(String foreignerHomephone) {
		this.foreignerHomephone = foreignerHomephone;
	}

	@Column(name = "FOREIGNER_CELLPHONE")
	public String getForeignerCellphone() {
		return this.foreignerCellphone;
	}

	public void setForeignerCellphone(String foreignerCellphone) {
		this.foreignerCellphone = foreignerCellphone;
	}

	@Column(name = "FOREIGNER_CONTACT")
	public String getForeignerContact() {
		return this.foreignerContact;
	}

	public void setForeignerContact(String foreignerContact) {
		this.foreignerContact = foreignerContact;
	}

	@Column(name = "CURRENT_JOB_DESCRIP")
	public String getCurrentJobDescrip() {
		return this.currentJobDescrip;
	}

	public void setCurrentJobDescrip(String currentJobDescrip) {
		this.currentJobDescrip = currentJobDescrip;
	}

	@Column(name = "ISREPLACE")
	public Boolean getIsreplace() {
		return this.isreplace;
	}

	public void setIsreplace(Boolean isreplace) {
		this.isreplace = isreplace;
	}

	@Column(name = "ISCASHHANDLER")
	public Boolean getIscashhandler() {
		return this.iscashhandler;
	}

	public void setIscashhandler(Boolean iscashhandler) {
		this.iscashhandler = iscashhandler;
	}

	@Column(name = "REASON_ID")
	public Integer getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(Integer reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "ATTENDANCECODE")
	public String getAttendancecode() {
		return this.attendancecode;
	}

	public void setAttendancecode(String attendancecode) {
		this.attendancecode = attendancecode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TripRequestHistories> getTripRequestHistorieses() {
		return this.tripRequestHistorieses;
	}

	public void setTripRequestHistorieses(Set<TripRequestHistories> tripRequestHistorieses) {
		this.tripRequestHistorieses = tripRequestHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeLanguage> getEmployeeLanguages() {
		return this.employeeLanguages;
	}

	public void setEmployeeLanguages(Set<EmployeeLanguage> employeeLanguages) {
		this.employeeLanguages = employeeLanguages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LeaveCarryForwardRequestHistories> getLeaveCarryForwardRequestHistorieses() {
		return this.leaveCarryForwardRequestHistorieses;
	}

	public void setLeaveCarryForwardRequestHistorieses(
			Set<LeaveCarryForwardRequestHistories> leaveCarryForwardRequestHistorieses) {
		this.leaveCarryForwardRequestHistorieses = leaveCarryForwardRequestHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<ProjectDefaults> getProjectDefaultses() {
		return this.projectDefaultses;
	}

	public void setProjectDefaultses(Set<ProjectDefaults> projectDefaultses) {
		this.projectDefaultses = projectDefaultses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<OutBreakRequests> getOutBreakRequestses() {
		return this.outBreakRequestses;
	}

	public void setOutBreakRequestses(Set<OutBreakRequests> outBreakRequestses) {
		this.outBreakRequestses = outBreakRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeAttachmentFiles> getEmployeeAttachmentFileses() {
		return this.employeeAttachmentFileses;
	}

	public void setEmployeeAttachmentFileses(Set<EmployeeAttachmentFiles> employeeAttachmentFileses) {
		this.employeeAttachmentFileses = employeeAttachmentFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeWorkingTitles> getEmployeeWorkingTitleses() {
		return this.employeeWorkingTitleses;
	}

	public void setEmployeeWorkingTitleses(Set<EmployeeWorkingTitles> employeeWorkingTitleses) {
		this.employeeWorkingTitleses = employeeWorkingTitleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<IncomeConfigs> getIncomeConfigses() {
		return this.incomeConfigses;
	}

	public void setIncomeConfigses(Set<IncomeConfigs> incomeConfigses) {
		this.incomeConfigses = incomeConfigses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeWorkingDays> getEmployeeWorkingDayses() {
		return this.employeeWorkingDayses;
	}

	public void setEmployeeWorkingDayses(Set<EmployeeWorkingDays> employeeWorkingDayses) {
		this.employeeWorkingDayses = employeeWorkingDayses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LeaveCarryForwardRequests> getLeaveCarryForwardRequestses() {
		return this.leaveCarryForwardRequestses;
	}

	public void setLeaveCarryForwardRequestses(Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses) {
		this.leaveCarryForwardRequestses = leaveCarryForwardRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeEmails> getEmployeeEmailses() {
		return this.employeeEmailses;
	}

	public void setEmployeeEmailses(Set<EmployeeEmails> employeeEmailses) {
		this.employeeEmailses = employeeEmailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeEducationLevels> getEmployeeEducationLevelses() {
		return this.employeeEducationLevelses;
	}

	public void setEmployeeEducationLevelses(Set<EmployeeEducationLevels> employeeEducationLevelses) {
		this.employeeEducationLevelses = employeeEducationLevelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeUnits> getEmployeeUnitses() {
		return this.employeeUnitses;
	}

	public void setEmployeeUnitses(Set<EmployeeUnits> employeeUnitses) {
		this.employeeUnitses = employeeUnitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LeaveRequests> getLeaveRequestses() {
		return this.leaveRequestses;
	}

	public void setLeaveRequestses(Set<LeaveRequests> leaveRequestses) {
		this.leaveRequestses = leaveRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByEmployeeId")
	public Set<EmployeeKpi> getEmployeeKpisForEmployeeId() {
		return this.employeeKpisForEmployeeId;
	}

	public void setEmployeeKpisForEmployeeId(Set<EmployeeKpi> employeeKpisForEmployeeId) {
		this.employeeKpisForEmployeeId = employeeKpisForEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TaOvertimeSchedulesHistories> getTaOvertimeSchedulesHistorieses() {
		return this.taOvertimeSchedulesHistorieses;
	}

	public void setTaOvertimeSchedulesHistorieses(Set<TaOvertimeSchedulesHistories> taOvertimeSchedulesHistorieses) {
		this.taOvertimeSchedulesHistorieses = taOvertimeSchedulesHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<ManagerOnsides> getManagerOnsideses() {
		return this.managerOnsideses;
	}

	public void setManagerOnsideses(Set<ManagerOnsides> managerOnsideses) {
		this.managerOnsideses = managerOnsideses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByEmployeeId")
	public Set<EmployeeManagers> getEmployeeManagersesForEmployeeId() {
		return this.employeeManagersesForEmployeeId;
	}

	public void setEmployeeManagersesForEmployeeId(Set<EmployeeManagers> employeeManagersesForEmployeeId) {
		this.employeeManagersesForEmployeeId = employeeManagersesForEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<RoleDepartments> getRoleDepartmentses() {
		return this.roleDepartmentses;
	}

	public void setRoleDepartmentses(Set<RoleDepartments> roleDepartmentses) {
		this.roleDepartmentses = roleDepartmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByHrManagerId")
	public Set<Units> getUnitsesForHrManagerId() {
		return this.unitsesForHrManagerId;
	}

	public void setUnitsesForHrManagerId(Set<Units> unitsesForHrManagerId) {
		this.unitsesForHrManagerId = unitsesForHrManagerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByEmployeeIdEdited")
	public Set<TaOvertimeSchedules> getTaOvertimeSchedulesesForEmployeeIdEdited() {
		return this.taOvertimeSchedulesesForEmployeeIdEdited;
	}

	public void setTaOvertimeSchedulesesForEmployeeIdEdited(
			Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdEdited) {
		this.taOvertimeSchedulesesForEmployeeIdEdited = taOvertimeSchedulesesForEmployeeIdEdited;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeMboRecords> getEmployeeMboRecordses() {
		return this.employeeMboRecordses;
	}

	public void setEmployeeMboRecordses(Set<EmployeeMboRecords> employeeMboRecordses) {
		this.employeeMboRecordses = employeeMboRecordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<PersonalTargets> getPersonalTargetses() {
		return this.personalTargetses;
	}

	public void setPersonalTargetses(Set<PersonalTargets> personalTargetses) {
		this.personalTargetses = personalTargetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeDisciplines> getEmployeeDisciplineses() {
		return this.employeeDisciplineses;
	}

	public void setEmployeeDisciplineses(Set<EmployeeDisciplines> employeeDisciplineses) {
		this.employeeDisciplineses = employeeDisciplineses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<PerformanceAssessments> getPerformanceAssessmentses() {
		return this.performanceAssessmentses;
	}

	public void setPerformanceAssessmentses(Set<PerformanceAssessments> performanceAssessmentses) {
		this.performanceAssessmentses = performanceAssessmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeIncomeTaxStats> getEmployeeIncomeTaxStatses() {
		return this.employeeIncomeTaxStatses;
	}

	public void setEmployeeIncomeTaxStatses(Set<EmployeeIncomeTaxStats> employeeIncomeTaxStatses) {
		this.employeeIncomeTaxStatses = employeeIncomeTaxStatses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeEducations> getEmployeeEducationses() {
		return this.employeeEducationses;
	}

	public void setEmployeeEducationses(Set<EmployeeEducations> employeeEducationses) {
		this.employeeEducationses = employeeEducationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeIncomes> getEmployeeIncomeses() {
		return this.employeeIncomeses;
	}

	public void setEmployeeIncomeses(Set<EmployeeIncomes> employeeIncomeses) {
		this.employeeIncomeses = employeeIncomeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeAccounts> getEmployeeAccountses() {
		return this.employeeAccountses;
	}

	public void setEmployeeAccountses(Set<EmployeeAccounts> employeeAccountses) {
		this.employeeAccountses = employeeAccountses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Outsides> getOutsideses() {
		return this.outsideses;
	}

	public void setOutsideses(Set<Outsides> outsideses) {
		this.outsideses = outsideses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LeaveRequestHistories> getLeaveRequestHistorieses() {
		return this.leaveRequestHistorieses;
	}

	public void setLeaveRequestHistorieses(Set<LeaveRequestHistories> leaveRequestHistorieses) {
		this.leaveRequestHistorieses = leaveRequestHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeAssignments> getEmployeeAssignmentses() {
		return this.employeeAssignmentses;
	}

	public void setEmployeeAssignmentses(Set<EmployeeAssignments> employeeAssignmentses) {
		this.employeeAssignmentses = employeeAssignmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeRanks> getEmployeeRankses() {
		return this.employeeRankses;
	}

	public void setEmployeeRankses(Set<EmployeeRanks> employeeRankses) {
		this.employeeRankses = employeeRankses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeFiles> getEmployeeFileses() {
		return this.employeeFileses;
	}

	public void setEmployeeFileses(Set<EmployeeFiles> employeeFileses) {
		this.employeeFileses = employeeFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeKaizenAwards> getEmployeeKaizenAwardses() {
		return this.employeeKaizenAwardses;
	}

	public void setEmployeeKaizenAwardses(Set<EmployeeKaizenAwards> employeeKaizenAwardses) {
		this.employeeKaizenAwardses = employeeKaizenAwardses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeIncomeStats> getEmployeeIncomeStatses() {
		return this.employeeIncomeStatses;
	}

	public void setEmployeeIncomeStatses(Set<EmployeeIncomeStats> employeeIncomeStatses) {
		this.employeeIncomeStatses = employeeIncomeStatses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeMissions> getEmployeeMissionses() {
		return this.employeeMissionses;
	}

	public void setEmployeeMissionses(Set<EmployeeMissions> employeeMissionses) {
		this.employeeMissionses = employeeMissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LogTimeSheet> getLogTimeSheets() {
		return this.logTimeSheets;
	}

	public void setLogTimeSheets(Set<LogTimeSheet> logTimeSheets) {
		this.logTimeSheets = logTimeSheets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeWorkbooks> getEmployeeWorkbookses() {
		return this.employeeWorkbookses;
	}

	public void setEmployeeWorkbookses(Set<EmployeeWorkbooks> employeeWorkbookses) {
		this.employeeWorkbookses = employeeWorkbookses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByEmployeeId")
	public Set<TaOvertimeSchedules> getTaOvertimeSchedulesesForEmployeeId() {
		return this.taOvertimeSchedulesesForEmployeeId;
	}

	public void setTaOvertimeSchedulesesForEmployeeId(Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeId) {
		this.taOvertimeSchedulesesForEmployeeId = taOvertimeSchedulesesForEmployeeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeContracts> getEmployeeContractses() {
		return this.employeeContractses;
	}

	public void setEmployeeContractses(Set<EmployeeContracts> employeeContractses) {
		this.employeeContractses = employeeContractses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Employees> getEmployeeses_1() {
		return this.employeeses_1;
	}

	public void setEmployeeses_1(Set<Employees> employeeses_1) {
		this.employeeses_1 = employeeses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<PdfFile> getPdfFiles() {
		return this.pdfFiles;
	}

	public void setPdfFiles(Set<PdfFile> pdfFiles) {
		this.pdfFiles = pdfFiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByManagerId")
	public Set<EmployeeManagers> getEmployeeManagersesForManagerId() {
		return this.employeeManagersesForManagerId;
	}

	public void setEmployeeManagersesForManagerId(Set<EmployeeManagers> employeeManagersesForManagerId) {
		this.employeeManagersesForManagerId = employeeManagersesForManagerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeePhones> getEmployeePhoneses() {
		return this.employeePhoneses;
	}

	public void setEmployeePhoneses(Set<EmployeePhones> employeePhoneses) {
		this.employeePhoneses = employeePhoneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<AprovalTripcosts> getAprovalTripcostses() {
		return this.aprovalTripcostses;
	}

	public void setAprovalTripcostses(Set<AprovalTripcosts> aprovalTripcostses) {
		this.aprovalTripcostses = aprovalTripcostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeHierarchicals> getEmployeeHierarchicalses() {
		return this.employeeHierarchicalses;
	}

	public void setEmployeeHierarchicalses(Set<EmployeeHierarchicals> employeeHierarchicalses) {
		this.employeeHierarchicalses = employeeHierarchicalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeTaxes> getEmployeeTaxeses() {
		return this.employeeTaxeses;
	}

	public void setEmployeeTaxeses(Set<EmployeeTaxes> employeeTaxeses) {
		this.employeeTaxeses = employeeTaxeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TimeSheets> getTimeSheetses() {
		return this.timeSheetses;
	}

	public void setTimeSheetses(Set<TimeSheets> timeSheetses) {
		this.timeSheetses = timeSheetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TaWorkingSchedules> getTaWorkingScheduleses() {
		return this.taWorkingScheduleses;
	}

	public void setTaWorkingScheduleses(Set<TaWorkingSchedules> taWorkingScheduleses) {
		this.taWorkingScheduleses = taWorkingScheduleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByManagerId")
	public Set<Units> getUnitsesForManagerId() {
		return this.unitsesForManagerId;
	}

	public void setUnitsesForManagerId(Set<Units> unitsesForManagerId) {
		this.unitsesForManagerId = unitsesForManagerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<OutBreakRequestHistories> getOutBreakRequestHistorieses() {
		return this.outBreakRequestHistorieses;
	}

	public void setOutBreakRequestHistorieses(Set<OutBreakRequestHistories> outBreakRequestHistorieses) {
		this.outBreakRequestHistorieses = outBreakRequestHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByEmployeeIdCreated")
	public Set<TaOvertimeSchedules> getTaOvertimeSchedulesesForEmployeeIdCreated() {
		return this.taOvertimeSchedulesesForEmployeeIdCreated;
	}

	public void setTaOvertimeSchedulesesForEmployeeIdCreated(
			Set<TaOvertimeSchedules> taOvertimeSchedulesesForEmployeeIdCreated) {
		this.taOvertimeSchedulesesForEmployeeIdCreated = taOvertimeSchedulesesForEmployeeIdCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeePreviewjob> getEmployeePreviewjobs() {
		return this.employeePreviewjobs;
	}

	public void setEmployeePreviewjobs(Set<EmployeePreviewjob> employeePreviewjobs) {
		this.employeePreviewjobs = employeePreviewjobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeWages> getEmployeeWageses() {
		return this.employeeWageses;
	}

	public void setEmployeeWageses(Set<EmployeeWages> employeeWageses) {
		this.employeeWageses = employeeWageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TripRequests> getTripRequestses() {
		return this.tripRequestses;
	}

	public void setTripRequestses(Set<TripRequests> tripRequestses) {
		this.tripRequestses = tripRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeRelatives> getEmployeeRelativeses() {
		return this.employeeRelativeses;
	}

	public void setEmployeeRelativeses(Set<EmployeeRelatives> employeeRelativeses) {
		this.employeeRelativeses = employeeRelativeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByModifiedBy")
	public Set<EmployeeKpi> getEmployeeKpisForModifiedBy() {
		return this.employeeKpisForModifiedBy;
	}

	public void setEmployeeKpisForModifiedBy(Set<EmployeeKpi> employeeKpisForModifiedBy) {
		this.employeeKpisForModifiedBy = employeeKpisForModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<EmployeeAddresses> getEmployeeAddresseses() {
		return this.employeeAddresseses;
	}

	public void setEmployeeAddresseses(Set<EmployeeAddresses> employeeAddresseses) {
		this.employeeAddresseses = employeeAddresseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeesByCreateBy")
	public Set<EmployeeKpi> getEmployeeKpisForCreateBy() {
		return this.employeeKpisForCreateBy;
	}

	public void setEmployeeKpisForCreateBy(Set<EmployeeKpi> employeeKpisForCreateBy) {
		this.employeeKpisForCreateBy = employeeKpisForCreateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<LeaveEmployeeBalances> getLeaveEmployeeBalanceses() {
		return this.leaveEmployeeBalanceses;
	}

	public void setLeaveEmployeeBalanceses(Set<LeaveEmployeeBalances> leaveEmployeeBalanceses) {
		this.leaveEmployeeBalanceses = leaveEmployeeBalanceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<TaEmployeeTimesheets> getTaEmployeeTimesheetses() {
		return this.taEmployeeTimesheetses;
	}

	public void setTaEmployeeTimesheetses(Set<TaEmployeeTimesheets> taEmployeeTimesheetses) {
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
	}

}
