package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeHierarchicals generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_HIERARCHICALS", catalog = "eHRM_JavaResearching")
public class EmployeeHierarchicals implements java.io.Serializable {

	private Integer employeeHierarchicalId;
	private Employees employees;
	private Hierarchicals hierarchicals;
	private Date startDate;
	private Date endDate;

	public EmployeeHierarchicals() {
	}

	public EmployeeHierarchicals(Employees employees, Hierarchicals hierarchicals, Date startDate) {
		this.employees = employees;
		this.hierarchicals = hierarchicals;
		this.startDate = startDate;
	}

	public EmployeeHierarchicals(Employees employees, Hierarchicals hierarchicals, Date startDate, Date endDate) {
		this.employees = employees;
		this.hierarchicals = hierarchicals;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_HIERARCHICAL_ID", unique = true, nullable = false)
	public Integer getEmployeeHierarchicalId() {
		return this.employeeHierarchicalId;
	}

	public void setEmployeeHierarchicalId(Integer employeeHierarchicalId) {
		this.employeeHierarchicalId = employeeHierarchicalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HIERARCHICAL_ID", nullable = false)
	public Hierarchicals getHierarchicals() {
		return this.hierarchicals;
	}

	public void setHierarchicals(Hierarchicals hierarchicals) {
		this.hierarchicals = hierarchicals;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
