package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeLanguage generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_LANGUAGE", catalog = "eHRM_JavaResearching")
public class EmployeeLanguage implements java.io.Serializable {

	private Integer employeeLanguageId;
	private Employees employees;
	private Languages languages;
	private MasterDatas masterDatasByLanguageLevelId;
	private MasterDatas masterDatasByLanguageId;

	public EmployeeLanguage() {
	}

	public EmployeeLanguage(Employees employees, Languages languages, MasterDatas masterDatasByLanguageLevelId,
			MasterDatas masterDatasByLanguageId) {
		this.employees = employees;
		this.languages = languages;
		this.masterDatasByLanguageLevelId = masterDatasByLanguageLevelId;
		this.masterDatasByLanguageId = masterDatasByLanguageId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_LANGUAGE_ID", unique = true, nullable = false)
	public Integer getEmployeeLanguageId() {
		return this.employeeLanguageId;
	}

	public void setEmployeeLanguageId(Integer employeeLanguageId) {
		this.employeeLanguageId = employeeLanguageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID")
	public Languages getLanguages() {
		return this.languages;
	}

	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_LEVEL_ID")
	public MasterDatas getMasterDatasByLanguageLevelId() {
		return this.masterDatasByLanguageLevelId;
	}

	public void setMasterDatasByLanguageLevelId(MasterDatas masterDatasByLanguageLevelId) {
		this.masterDatasByLanguageLevelId = masterDatasByLanguageLevelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANGUAGE_ID", insertable = false, updatable = false)
	public MasterDatas getMasterDatasByLanguageId() {
		return this.masterDatasByLanguageId;
	}

	public void setMasterDatasByLanguageId(MasterDatas masterDatasByLanguageId) {
		this.masterDatasByLanguageId = masterDatasByLanguageId;
	}

}
