package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeePreviewjob generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_PREVIEWJOB", catalog = "eHRM_JavaResearching")
public class EmployeePreviewjob implements java.io.Serializable {

	private Integer employeePreviewjobId;
	private Employees employees;
	private Serializable position;
	private Serializable duration;
	private Serializable companyName;

	public EmployeePreviewjob() {
	}

	public EmployeePreviewjob(Employees employees, Serializable position, Serializable duration,
			Serializable companyName) {
		this.employees = employees;
		this.position = position;
		this.duration = duration;
		this.companyName = companyName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_PREVIEWJOB_ID", unique = true, nullable = false)
	public Integer getEmployeePreviewjobId() {
		return this.employeePreviewjobId;
	}

	public void setEmployeePreviewjobId(Integer employeePreviewjobId) {
		this.employeePreviewjobId = employeePreviewjobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "POSITION")
	public Serializable getPosition() {
		return this.position;
	}

	public void setPosition(Serializable position) {
		this.position = position;
	}

	@Column(name = "DURATION")
	public Serializable getDuration() {
		return this.duration;
	}

	public void setDuration(Serializable duration) {
		this.duration = duration;
	}

	@Column(name = "COMPANY_NAME")
	public Serializable getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(Serializable companyName) {
		this.companyName = companyName;
	}

}
