package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeEducations generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_EDUCATIONS", catalog = "eHRM_JavaResearching")
public class EmployeeEducations implements java.io.Serializable {

	private Integer employeeEducationId;
	private Employees employees;
	private Serializable educationName;
	private Date startDate;
	private Date endDate;
	private Serializable educationLocation;
	private Serializable major;

	public EmployeeEducations() {
	}

	public EmployeeEducations(Employees employees, Serializable educationName, Date startDate) {
		this.employees = employees;
		this.educationName = educationName;
		this.startDate = startDate;
	}

	public EmployeeEducations(Employees employees, Serializable educationName, Date startDate, Date endDate,
			Serializable educationLocation, Serializable major) {
		this.employees = employees;
		this.educationName = educationName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.educationLocation = educationLocation;
		this.major = major;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_EDUCATION_ID", unique = true, nullable = false)
	public Integer getEmployeeEducationId() {
		return this.employeeEducationId;
	}

	public void setEmployeeEducationId(Integer employeeEducationId) {
		this.employeeEducationId = employeeEducationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "EDUCATION_NAME", nullable = false)
	public Serializable getEducationName() {
		return this.educationName;
	}

	public void setEducationName(Serializable educationName) {
		this.educationName = educationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "EDUCATION_LOCATION")
	public Serializable getEducationLocation() {
		return this.educationLocation;
	}

	public void setEducationLocation(Serializable educationLocation) {
		this.educationLocation = educationLocation;
	}

	@Column(name = "MAJOR")
	public Serializable getMajor() {
		return this.major;
	}

	public void setMajor(Serializable major) {
		this.major = major;
	}

}
