package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeCertificate generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_CERTIFICATE", catalog = "eHRM_JavaResearching")
public class EmployeeCertificate implements java.io.Serializable {

	private Integer employeeCertificateId;
	private Integer employeeId;
	private Serializable universityName;
	private Serializable universityLocation;
	private Serializable major;
	private Date graduationDate;
	private Serializable professionalCertificate;
	private Boolean certificateType;

	public EmployeeCertificate() {
	}

	public EmployeeCertificate(Integer employeeId, Serializable universityName, Serializable universityLocation,
			Serializable major, Date graduationDate, Serializable professionalCertificate, Boolean certificateType) {
		this.employeeId = employeeId;
		this.universityName = universityName;
		this.universityLocation = universityLocation;
		this.major = major;
		this.graduationDate = graduationDate;
		this.professionalCertificate = professionalCertificate;
		this.certificateType = certificateType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_CERTIFICATE_ID", unique = true, nullable = false)
	public Integer getEmployeeCertificateId() {
		return this.employeeCertificateId;
	}

	public void setEmployeeCertificateId(Integer employeeCertificateId) {
		this.employeeCertificateId = employeeCertificateId;
	}

	@Column(name = "EMPLOYEE_ID")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "UNIVERSITY_NAME")
	public Serializable getUniversityName() {
		return this.universityName;
	}

	public void setUniversityName(Serializable universityName) {
		this.universityName = universityName;
	}

	@Column(name = "UNIVERSITY_LOCATION")
	public Serializable getUniversityLocation() {
		return this.universityLocation;
	}

	public void setUniversityLocation(Serializable universityLocation) {
		this.universityLocation = universityLocation;
	}

	@Column(name = "MAJOR")
	public Serializable getMajor() {
		return this.major;
	}

	public void setMajor(Serializable major) {
		this.major = major;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GRADUATION_DATE", length = 10)
	public Date getGraduationDate() {
		return this.graduationDate;
	}

	public void setGraduationDate(Date graduationDate) {
		this.graduationDate = graduationDate;
	}

	@Column(name = "PROFESSIONAL_CERTIFICATE")
	public Serializable getProfessionalCertificate() {
		return this.professionalCertificate;
	}

	public void setProfessionalCertificate(Serializable professionalCertificate) {
		this.professionalCertificate = professionalCertificate;
	}

	@Column(name = "CERTIFICATE_TYPE")
	public Boolean getCertificateType() {
		return this.certificateType;
	}

	public void setCertificateType(Boolean certificateType) {
		this.certificateType = certificateType;
	}

}
