package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeFiles generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_FILES", catalog = "eHRM_JavaResearching")
public class EmployeeFiles implements java.io.Serializable {

	private Integer employeeFileId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Serializable fileContent;

	public EmployeeFiles() {
	}

	public EmployeeFiles(Employees employees, MasterDatas masterDatas, Serializable fileContent) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.fileContent = fileContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_FILE_ID", unique = true, nullable = false)
	public Integer getEmployeeFileId() {
		return this.employeeFileId;
	}

	public void setEmployeeFileId(Integer employeeFileId) {
		this.employeeFileId = employeeFileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FILE_TYPE_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Column(name = "FILE_CONTENT", nullable = false)
	public Serializable getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(Serializable fileContent) {
		this.fileContent = fileContent;
	}

}
