package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeAttachmentFiles generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_ATTACHMENT_FILES", catalog = "eHRM_JavaResearching")
public class EmployeeAttachmentFiles implements java.io.Serializable {

	private Integer employeeAttachmentFileId;
	private Employees employees;
	private Serializable name;
	private Serializable description;
	private Serializable attachmentFileName;

	public EmployeeAttachmentFiles() {
	}

	public EmployeeAttachmentFiles(Employees employees, Serializable name) {
		this.employees = employees;
		this.name = name;
	}

	public EmployeeAttachmentFiles(Employees employees, Serializable name, Serializable description,
			Serializable attachmentFileName) {
		this.employees = employees;
		this.name = name;
		this.description = description;
		this.attachmentFileName = attachmentFileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_ATTACHMENT_FILE_ID", unique = true, nullable = false)
	public Integer getEmployeeAttachmentFileId() {
		return this.employeeAttachmentFileId;
	}

	public void setEmployeeAttachmentFileId(Integer employeeAttachmentFileId) {
		this.employeeAttachmentFileId = employeeAttachmentFileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "NAME", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "ATTACHMENT_FILE_NAME")
	public Serializable getAttachmentFileName() {
		return this.attachmentFileName;
	}

	public void setAttachmentFileName(Serializable attachmentFileName) {
		this.attachmentFileName = attachmentFileName;
	}

}
