package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeManagers generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_MANAGERS", catalog = "eHRM_JavaResearching")
public class EmployeeManagers implements java.io.Serializable {

	private Integer employeeManagerId;
	private Employees employeesByEmployeeId;
	private Employees employeesByManagerId;
	private Date startDate;
	private Date endDate;
	private boolean isDefault;
	private boolean notApprove;

	public EmployeeManagers() {
	}

	public EmployeeManagers(Employees employeesByEmployeeId, Employees employeesByManagerId, Date startDate,
			boolean isDefault, boolean notApprove) {
		this.employeesByEmployeeId = employeesByEmployeeId;
		this.employeesByManagerId = employeesByManagerId;
		this.startDate = startDate;
		this.isDefault = isDefault;
		this.notApprove = notApprove;
	}

	public EmployeeManagers(Employees employeesByEmployeeId, Employees employeesByManagerId, Date startDate,
			Date endDate, boolean isDefault, boolean notApprove) {
		this.employeesByEmployeeId = employeesByEmployeeId;
		this.employeesByManagerId = employeesByManagerId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isDefault = isDefault;
		this.notApprove = notApprove;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_MANAGER_ID", unique = true, nullable = false)
	public Integer getEmployeeManagerId() {
		return this.employeeManagerId;
	}

	public void setEmployeeManagerId(Integer employeeManagerId) {
		this.employeeManagerId = employeeManagerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployeesByEmployeeId() {
		return this.employeesByEmployeeId;
	}

	public void setEmployeesByEmployeeId(Employees employeesByEmployeeId) {
		this.employeesByEmployeeId = employeesByEmployeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_ID", nullable = false)
	public Employees getEmployeesByManagerId() {
		return this.employeesByManagerId;
	}

	public void setEmployeesByManagerId(Employees employeesByManagerId) {
		this.employeesByManagerId = employeesByManagerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "NOT_APPROVE", nullable = false)
	public boolean isNotApprove() {
		return this.notApprove;
	}

	public void setNotApprove(boolean notApprove) {
		this.notApprove = notApprove;
	}

}
