package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeTaxes generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_TAXES", catalog = "eHRM_JavaResearching")
public class EmployeeTaxes implements java.io.Serializable {

	private Integer employeeTaxId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Periods periods;
	private Taxes taxes;
	private BigDecimal taxValue;
	private BigDecimal exchangeRate;

	public EmployeeTaxes() {
	}

	public EmployeeTaxes(Employees employees, MasterDatas masterDatas, Periods periods, Taxes taxes,
			BigDecimal taxValue) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.periods = periods;
		this.taxes = taxes;
		this.taxValue = taxValue;
	}

	public EmployeeTaxes(Employees employees, MasterDatas masterDatas, Periods periods, Taxes taxes,
			BigDecimal taxValue, BigDecimal exchangeRate) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.periods = periods;
		this.taxes = taxes;
		this.taxValue = taxValue;
		this.exchangeRate = exchangeRate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_TAX_ID", unique = true, nullable = false)
	public Integer getEmployeeTaxId() {
		return this.employeeTaxId;
	}

	public void setEmployeeTaxId(Integer employeeTaxId) {
		this.employeeTaxId = employeeTaxId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIOD_ID", nullable = false)
	public Periods getPeriods() {
		return this.periods;
	}

	public void setPeriods(Periods periods) {
		this.periods = periods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAX_ID", nullable = false)
	public Taxes getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Taxes taxes) {
		this.taxes = taxes;
	}

	@Column(name = "TAX_VALUE", nullable = false, precision = 18, scale = 4)
	public BigDecimal getTaxValue() {
		return this.taxValue;
	}

	public void setTaxValue(BigDecimal taxValue) {
		this.taxValue = taxValue;
	}

	@Column(name = "EXCHANGE_RATE", precision = 18, scale = 4)
	public BigDecimal getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

}
