package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeUnits generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_UNITS", catalog = "eHRM_JavaResearching")
public class EmployeeUnits implements java.io.Serializable {

	private Integer employeeUnitId;
	private Employees employees;
	private Units units;
	private Date startDate;
	private Date endDate;

	public EmployeeUnits() {
	}

	public EmployeeUnits(Employees employees, Units units, Date startDate) {
		this.employees = employees;
		this.units = units;
		this.startDate = startDate;
	}

	public EmployeeUnits(Employees employees, Units units, Date startDate, Date endDate) {
		this.employees = employees;
		this.units = units;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_UNIT_ID", unique = true, nullable = false)
	public Integer getEmployeeUnitId() {
		return this.employeeUnitId;
	}

	public void setEmployeeUnitId(Integer employeeUnitId) {
		this.employeeUnitId = employeeUnitId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_ID", nullable = false)
	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
