package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeAssignments generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_ASSIGNMENTS", catalog = "eHRM_JavaResearching")
public class EmployeeAssignments implements java.io.Serializable {

	private Integer employeeAssignmentId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Date startDate;
	private Date endDate;
	private int assignmentPercentage;
	private Serializable content;
	private Serializable location;
	private Boolean isWorking;

	public EmployeeAssignments() {
	}

	public EmployeeAssignments(Employees employees, MasterDatas masterDatas, Date startDate, int assignmentPercentage) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.assignmentPercentage = assignmentPercentage;
	}

	public EmployeeAssignments(Employees employees, MasterDatas masterDatas, Date startDate, Date endDate,
			int assignmentPercentage, Serializable content, Serializable location, Boolean isWorking) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.endDate = endDate;
		this.assignmentPercentage = assignmentPercentage;
		this.content = content;
		this.location = location;
		this.isWorking = isWorking;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_ASSIGNMENT_ID", unique = true, nullable = false)
	public Integer getEmployeeAssignmentId() {
		return this.employeeAssignmentId;
	}

	public void setEmployeeAssignmentId(Integer employeeAssignmentId) {
		this.employeeAssignmentId = employeeAssignmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSIGNMENT_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ASSIGNMENT_PERCENTAGE", nullable = false)
	public int getAssignmentPercentage() {
		return this.assignmentPercentage;
	}

	public void setAssignmentPercentage(int assignmentPercentage) {
		this.assignmentPercentage = assignmentPercentage;
	}

	@Column(name = "CONTENT")
	public Serializable getContent() {
		return this.content;
	}

	public void setContent(Serializable content) {
		this.content = content;
	}

	@Column(name = "LOCATION")
	public Serializable getLocation() {
		return this.location;
	}

	public void setLocation(Serializable location) {
		this.location = location;
	}

	@Column(name = "IS_WORKING")
	public Boolean getIsWorking() {
		return this.isWorking;
	}

	public void setIsWorking(Boolean isWorking) {
		this.isWorking = isWorking;
	}

}
