package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeWages generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_WAGES", catalog = "eHRM_JavaResearching")
public class EmployeeWages implements java.io.Serializable {

	private Integer employeeWageId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Date startDate;
	private Date endDate;

	public EmployeeWages() {
	}

	public EmployeeWages(Employees employees, MasterDatas masterDatas, Date startDate) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
	}

	public EmployeeWages(Employees employees, MasterDatas masterDatas, Date startDate, Date endDate) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_WAGE_ID", unique = true, nullable = false)
	public Integer getEmployeeWageId() {
		return this.employeeWageId;
	}

	public void setEmployeeWageId(Integer employeeWageId) {
		this.employeeWageId = employeeWageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
