package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeWorkingDays generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_WORKING_DAYS", catalog = "eHRM_JavaResearching")
public class EmployeeWorkingDays implements java.io.Serializable {

	private Integer employeeWorkingDayId;
	private Employees employees;
	private Periods periods;
	private long workingDays;

	public EmployeeWorkingDays() {
	}

	public EmployeeWorkingDays(Employees employees, Periods periods, long workingDays) {
		this.employees = employees;
		this.periods = periods;
		this.workingDays = workingDays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_WORKING_DAY_ID", unique = true, nullable = false)
	public Integer getEmployeeWorkingDayId() {
		return this.employeeWorkingDayId;
	}

	public void setEmployeeWorkingDayId(Integer employeeWorkingDayId) {
		this.employeeWorkingDayId = employeeWorkingDayId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIOD_ID", nullable = false)
	public Periods getPeriods() {
		return this.periods;
	}

	public void setPeriods(Periods periods) {
		this.periods = periods;
	}

	@Column(name = "WORKING_DAYS", nullable = false, precision = 18, scale = 0)
	public long getWorkingDays() {
		return this.workingDays;
	}

	public void setWorkingDays(long workingDays) {
		this.workingDays = workingDays;
	}

}
