package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeContracts generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_CONTRACTS", catalog = "eHRM_JavaResearching")
public class EmployeeContracts implements java.io.Serializable {

	private Integer contractId;
	private Employees employees;
	private MasterDatas masterDatasByWorkingTypeId;
	private MasterDatas masterDatasByContractTypeId;
	private Units units;
	private String contractNumber;
	private Date startDate;
	private Date endDate;
	private Date signDate;
	private String contractContent;
	private BigDecimal workingTypeFixedValue;

	public EmployeeContracts() {
	}

	public EmployeeContracts(Employees employees, MasterDatas masterDatasByContractTypeId, Units units,
			String contractNumber, Date startDate, Date signDate) {
		this.employees = employees;
		this.masterDatasByContractTypeId = masterDatasByContractTypeId;
		this.units = units;
		this.contractNumber = contractNumber;
		this.startDate = startDate;
		this.signDate = signDate;
	}

	public EmployeeContracts(Employees employees, MasterDatas masterDatasByWorkingTypeId,
			MasterDatas masterDatasByContractTypeId, Units units, String contractNumber, Date startDate,
			Date endDate, Date signDate, String contractContent, BigDecimal workingTypeFixedValue) {
		this.employees = employees;
		this.masterDatasByWorkingTypeId = masterDatasByWorkingTypeId;
		this.masterDatasByContractTypeId = masterDatasByContractTypeId;
		this.units = units;
		this.contractNumber = contractNumber;
		this.startDate = startDate;
		this.endDate = endDate;
		this.signDate = signDate;
		this.contractContent = contractContent;
		this.workingTypeFixedValue = workingTypeFixedValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CONTRACT_ID", unique = true, nullable = false)
	public Integer getContractId() {
		return this.contractId;
	}

	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WORKING_TYPE_ID")
	public MasterDatas getMasterDatasByWorkingTypeId() {
		return this.masterDatasByWorkingTypeId;
	}

	public void setMasterDatasByWorkingTypeId(MasterDatas masterDatasByWorkingTypeId) {
		this.masterDatasByWorkingTypeId = masterDatasByWorkingTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTRACT_TYPE_ID", nullable = false)
	public MasterDatas getMasterDatasByContractTypeId() {
		return this.masterDatasByContractTypeId;
	}

	public void setMasterDatasByContractTypeId(MasterDatas masterDatasByContractTypeId) {
		this.masterDatasByContractTypeId = masterDatasByContractTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ID", nullable = false)
	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	@Column(name = "CONTRACT_NUMBER", nullable = false)
	public String getContractNumber() {
		return this.contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SIGN_DATE", nullable = false, length = 10)
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	@Column(name = "CONTRACT_CONTENT")
	public String getContractContent() {
		return this.contractContent;
	}

	public void setContractContent(String contractContent) {
		this.contractContent = contractContent;
	}

	@Column(name = "WORKING_TYPE_FIXED_VALUE", precision = 18, scale = 4)
	public BigDecimal getWorkingTypeFixedValue() {
		return this.workingTypeFixedValue;
	}

	public void setWorkingTypeFixedValue(BigDecimal workingTypeFixedValue) {
		this.workingTypeFixedValue = workingTypeFixedValue;
	}

}
