package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeDependants generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_DEPENDANTS", catalog = "eHRM_JavaResearching")
public class EmployeeDependants implements java.io.Serializable {

	private Integer employeeDependantId;
	private EmployeeRelatives employeeRelatives;
	private Date startDate;
	private Date endDate;

	public EmployeeDependants() {
	}

	public EmployeeDependants(EmployeeRelatives employeeRelatives, Date startDate) {
		this.employeeRelatives = employeeRelatives;
		this.startDate = startDate;
	}

	public EmployeeDependants(EmployeeRelatives employeeRelatives, Date startDate, Date endDate) {
		this.employeeRelatives = employeeRelatives;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_DEPENDANT_ID", unique = true, nullable = false)
	public Integer getEmployeeDependantId() {
		return this.employeeDependantId;
	}

	public void setEmployeeDependantId(Integer employeeDependantId) {
		this.employeeDependantId = employeeDependantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_RELATIVE_ID", nullable = false)
	public EmployeeRelatives getEmployeeRelatives() {
		return this.employeeRelatives;
	}

	public void setEmployeeRelatives(EmployeeRelatives employeeRelatives) {
		this.employeeRelatives = employeeRelatives;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
