package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeKaizenAwards generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_KAIZEN_AWARDS", catalog = "eHRM_JavaResearching")
public class EmployeeKaizenAwards implements java.io.Serializable {

	private Integer employeeKaizenAwardId;
	private Employees employees;
	private FinancialYears financialYears;
	private Serializable content;
	private Double score;
	private Serializable level;
	private BigDecimal amount;
	private int ordinal;

	public EmployeeKaizenAwards() {
	}

	public EmployeeKaizenAwards(Employees employees, FinancialYears financialYears, int ordinal) {
		this.employees = employees;
		this.financialYears = financialYears;
		this.ordinal = ordinal;
	}

	public EmployeeKaizenAwards(Employees employees, FinancialYears financialYears, Serializable content, Double score,
			Serializable level, BigDecimal amount, int ordinal) {
		this.employees = employees;
		this.financialYears = financialYears;
		this.content = content;
		this.score = score;
		this.level = level;
		this.amount = amount;
		this.ordinal = ordinal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_KAIZEN_AWARD_ID", unique = true, nullable = false)
	public Integer getEmployeeKaizenAwardId() {
		return this.employeeKaizenAwardId;
	}

	public void setEmployeeKaizenAwardId(Integer employeeKaizenAwardId) {
		this.employeeKaizenAwardId = employeeKaizenAwardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINANCIAL_YEAR_ID", nullable = false)
	public FinancialYears getFinancialYears() {
		return this.financialYears;
	}

	public void setFinancialYears(FinancialYears financialYears) {
		this.financialYears = financialYears;
	}

	@Column(name = "CONTENT")
	public Serializable getContent() {
		return this.content;
	}

	public void setContent(Serializable content) {
		this.content = content;
	}

	@Column(name = "SCORE", precision = 53, scale = 0)
	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	@Column(name = "LEVEL")
	public Serializable getLevel() {
		return this.level;
	}

	public void setLevel(Serializable level) {
		this.level = level;
	}

	@Column(name = "AMOUNT", precision = 18, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "ORDINAL", nullable = false)
	public int getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(int ordinal) {
		this.ordinal = ordinal;
	}

}
