package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeAddresses generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_ADDRESSES", catalog = "eHRM_JavaResearching")
public class EmployeeAddresses implements java.io.Serializable {

	private Integer employeeAddressId;
	private Employees employees;
	private MasterDatas masterDatasByAddressTypeId;
	private MasterDatas masterDatasByLocationId;
	private Serializable addressText;
	private boolean active;

	public EmployeeAddresses() {
	}

	public EmployeeAddresses(Employees employees, MasterDatas masterDatasByAddressTypeId,
			MasterDatas masterDatasByLocationId, Serializable addressText, boolean active) {
		this.employees = employees;
		this.masterDatasByAddressTypeId = masterDatasByAddressTypeId;
		this.masterDatasByLocationId = masterDatasByLocationId;
		this.addressText = addressText;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_ADDRESS_ID", unique = true, nullable = false)
	public Integer getEmployeeAddressId() {
		return this.employeeAddressId;
	}

	public void setEmployeeAddressId(Integer employeeAddressId) {
		this.employeeAddressId = employeeAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_TYPE_ID", nullable = false)
	public MasterDatas getMasterDatasByAddressTypeId() {
		return this.masterDatasByAddressTypeId;
	}

	public void setMasterDatasByAddressTypeId(MasterDatas masterDatasByAddressTypeId) {
		this.masterDatasByAddressTypeId = masterDatasByAddressTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_ID", nullable = false)
	public MasterDatas getMasterDatasByLocationId() {
		return this.masterDatasByLocationId;
	}

	public void setMasterDatasByLocationId(MasterDatas masterDatasByLocationId) {
		this.masterDatasByLocationId = masterDatasByLocationId;
	}

	@Column(name = "ADDRESS_TEXT", nullable = false)
	public Serializable getAddressText() {
		return this.addressText;
	}

	public void setAddressText(Serializable addressText) {
		this.addressText = addressText;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
