package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeMissions generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_MISSIONS", catalog = "eHRM_JavaResearching")
public class EmployeeMissions implements java.io.Serializable {

	private Integer employeeMissionId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Date startDate;
	private Date endDate;
	private Serializable missionNote;
	private Serializable projectCode;

	public EmployeeMissions() {
	}

	public EmployeeMissions(Employees employees, MasterDatas masterDatas, Date startDate) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
	}

	public EmployeeMissions(Employees employees, MasterDatas masterDatas, Date startDate, Date endDate,
			Serializable missionNote, Serializable projectCode) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.endDate = endDate;
		this.missionNote = missionNote;
		this.projectCode = projectCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_MISSION_ID", unique = true, nullable = false)
	public Integer getEmployeeMissionId() {
		return this.employeeMissionId;
	}

	public void setEmployeeMissionId(Integer employeeMissionId) {
		this.employeeMissionId = employeeMissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "MISSION_NOTE")
	public Serializable getMissionNote() {
		return this.missionNote;
	}

	public void setMissionNote(Serializable missionNote) {
		this.missionNote = missionNote;
	}

	@Column(name = "PROJECT_CODE")
	public Serializable getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(Serializable projectCode) {
		this.projectCode = projectCode;
	}

}
