package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeIncomeTaxStats generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_INCOME_TAX_STATS", catalog = "eHRM_JavaResearching")
public class EmployeeIncomeTaxStats implements java.io.Serializable {

	private Integer employeeIncomeTaxStatsId;
	private EmployeeIncomes employeeIncomes;
	private Employees employees;
	private MasterDatas masterDatas;
	private Taxes taxes;
	private int periodId;
	private BigDecimal value;

	public EmployeeIncomeTaxStats() {
	}

	public EmployeeIncomeTaxStats(EmployeeIncomes employeeIncomes, Employees employees, MasterDatas masterDatas,
			Taxes taxes, int periodId, BigDecimal value) {
		this.employeeIncomes = employeeIncomes;
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.taxes = taxes;
		this.periodId = periodId;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_INCOME_TAX_STATS_ID", unique = true, nullable = false)
	public Integer getEmployeeIncomeTaxStatsId() {
		return this.employeeIncomeTaxStatsId;
	}

	public void setEmployeeIncomeTaxStatsId(Integer employeeIncomeTaxStatsId) {
		this.employeeIncomeTaxStatsId = employeeIncomeTaxStatsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_INCOME_ID", nullable = false)
	public EmployeeIncomes getEmployeeIncomes() {
		return this.employeeIncomes;
	}

	public void setEmployeeIncomes(EmployeeIncomes employeeIncomes) {
		this.employeeIncomes = employeeIncomes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAX_ID", nullable = false)
	public Taxes getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Taxes taxes) {
		this.taxes = taxes;
	}

	@Column(name = "PERIOD_ID", nullable = false)
	public int getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(int periodId) {
		this.periodId = periodId;
	}

	@Column(name = "VALUE", nullable = false, precision = 18, scale = 4)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
