package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeEducationLevels generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_EDUCATION_LEVELS", catalog = "eHRM_JavaResearching")
public class EmployeeEducationLevels implements java.io.Serializable {

	private Integer employeeEducationLevelId;
	private Employees employees;
	private MasterDatas masterDatasByEducationLevelId;
	private MasterDatas masterDatasByProfessional;
	private Date issuedDate;
	private Serializable at;
	private Serializable universityLocation;

	public EmployeeEducationLevels() {
	}

	public EmployeeEducationLevels(Employees employees, MasterDatas masterDatasByEducationLevelId) {
		this.employees = employees;
		this.masterDatasByEducationLevelId = masterDatasByEducationLevelId;
	}

	public EmployeeEducationLevels(Employees employees, MasterDatas masterDatasByEducationLevelId,
			MasterDatas masterDatasByProfessional, Date issuedDate, Serializable at, Serializable universityLocation) {
		this.employees = employees;
		this.masterDatasByEducationLevelId = masterDatasByEducationLevelId;
		this.masterDatasByProfessional = masterDatasByProfessional;
		this.issuedDate = issuedDate;
		this.at = at;
		this.universityLocation = universityLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_EDUCATION_LEVEL_ID", unique = true, nullable = false)
	public Integer getEmployeeEducationLevelId() {
		return this.employeeEducationLevelId;
	}

	public void setEmployeeEducationLevelId(Integer employeeEducationLevelId) {
		this.employeeEducationLevelId = employeeEducationLevelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUCATION_LEVEL_ID", nullable = false)
	public MasterDatas getMasterDatasByEducationLevelId() {
		return this.masterDatasByEducationLevelId;
	}

	public void setMasterDatasByEducationLevelId(MasterDatas masterDatasByEducationLevelId) {
		this.masterDatasByEducationLevelId = masterDatasByEducationLevelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFESSIONAL")
	public MasterDatas getMasterDatasByProfessional() {
		return this.masterDatasByProfessional;
	}

	public void setMasterDatasByProfessional(MasterDatas masterDatasByProfessional) {
		this.masterDatasByProfessional = masterDatasByProfessional;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUED_DATE", length = 10)
	public Date getIssuedDate() {
		return this.issuedDate;
	}

	public void setIssuedDate(Date issuedDate) {
		this.issuedDate = issuedDate;
	}

	@Column(name = "AT")
	public Serializable getAt() {
		return this.at;
	}

	public void setAt(Serializable at) {
		this.at = at;
	}

	@Column(name = "UNIVERSITY_LOCATION")
	public Serializable getUniversityLocation() {
		return this.universityLocation;
	}

	public void setUniversityLocation(Serializable universityLocation) {
		this.universityLocation = universityLocation;
	}

}
