package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeMboRecords generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_MBO_RECORDS", catalog = "eHRM_JavaResearching")
public class EmployeeMboRecords implements java.io.Serializable {

	private Integer employeeMboRecordId;
	private Employees employees;
	private FinancialYears financialYears;
	private Serializable mboObject;
	private Serializable participation;
	private Serializable result;
	private Double initialPoint;
	private Serializable initialRank;
	private Serializable initialGrade;
	private Double finalPoint;
	private Serializable finalRank;
	private Serializable finalGrade;
	private BigDecimal bonus;
	private Serializable remark;

	public EmployeeMboRecords() {
	}

	public EmployeeMboRecords(Employees employees, FinancialYears financialYears) {
		this.employees = employees;
		this.financialYears = financialYears;
	}

	public EmployeeMboRecords(Employees employees, FinancialYears financialYears, Serializable mboObject,
			Serializable participation, Serializable result, Double initialPoint, Serializable initialRank,
			Serializable initialGrade, Double finalPoint, Serializable finalRank, Serializable finalGrade,
			BigDecimal bonus, Serializable remark) {
		this.employees = employees;
		this.financialYears = financialYears;
		this.mboObject = mboObject;
		this.participation = participation;
		this.result = result;
		this.initialPoint = initialPoint;
		this.initialRank = initialRank;
		this.initialGrade = initialGrade;
		this.finalPoint = finalPoint;
		this.finalRank = finalRank;
		this.finalGrade = finalGrade;
		this.bonus = bonus;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_MBO_RECORD_ID", unique = true, nullable = false)
	public Integer getEmployeeMboRecordId() {
		return this.employeeMboRecordId;
	}

	public void setEmployeeMboRecordId(Integer employeeMboRecordId) {
		this.employeeMboRecordId = employeeMboRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINANCIAL_YEAR_ID", nullable = false)
	public FinancialYears getFinancialYears() {
		return this.financialYears;
	}

	public void setFinancialYears(FinancialYears financialYears) {
		this.financialYears = financialYears;
	}

	@Column(name = "MBO_OBJECT")
	public Serializable getMboObject() {
		return this.mboObject;
	}

	public void setMboObject(Serializable mboObject) {
		this.mboObject = mboObject;
	}

	@Column(name = "PARTICIPATION")
	public Serializable getParticipation() {
		return this.participation;
	}

	public void setParticipation(Serializable participation) {
		this.participation = participation;
	}

	@Column(name = "RESULT")
	public Serializable getResult() {
		return this.result;
	}

	public void setResult(Serializable result) {
		this.result = result;
	}

	@Column(name = "INITIAL_POINT", precision = 53, scale = 0)
	public Double getInitialPoint() {
		return this.initialPoint;
	}

	public void setInitialPoint(Double initialPoint) {
		this.initialPoint = initialPoint;
	}

	@Column(name = "INITIAL_RANK")
	public Serializable getInitialRank() {
		return this.initialRank;
	}

	public void setInitialRank(Serializable initialRank) {
		this.initialRank = initialRank;
	}

	@Column(name = "INITIAL_GRADE")
	public Serializable getInitialGrade() {
		return this.initialGrade;
	}

	public void setInitialGrade(Serializable initialGrade) {
		this.initialGrade = initialGrade;
	}

	@Column(name = "FINAL_POINT", precision = 53, scale = 0)
	public Double getFinalPoint() {
		return this.finalPoint;
	}

	public void setFinalPoint(Double finalPoint) {
		this.finalPoint = finalPoint;
	}

	@Column(name = "FINAL_RANK")
	public Serializable getFinalRank() {
		return this.finalRank;
	}

	public void setFinalRank(Serializable finalRank) {
		this.finalRank = finalRank;
	}

	@Column(name = "FINAL_GRADE")
	public Serializable getFinalGrade() {
		return this.finalGrade;
	}

	public void setFinalGrade(Serializable finalGrade) {
		this.finalGrade = finalGrade;
	}

	@Column(name = "BONUS", precision = 18, scale = 4)
	public BigDecimal getBonus() {
		return this.bonus;
	}

	public void setBonus(BigDecimal bonus) {
		this.bonus = bonus;
	}

	@Column(name = "REMARK")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

}
