package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeKpi generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_KPI", catalog = "eHRM_JavaResearching")
public class EmployeeKpi implements java.io.Serializable {

	private Integer kpiId;
	private Employees employeesByEmployeeId;
	private Employees employeesByModifiedBy;
	private Employees employeesByCreateBy;
	private Serializable fileName;
	private Date kpiDate;
	private Date createDate;
	private Date modifiedDate;
	private Serializable url;
	private Serializable notes;

	public EmployeeKpi() {
	}

	public EmployeeKpi(Employees employeesByEmployeeId, Employees employeesByModifiedBy, Employees employeesByCreateBy,
			Serializable fileName, Date kpiDate, Date createDate, Date modifiedDate, Serializable url,
			Serializable notes) {
		this.employeesByEmployeeId = employeesByEmployeeId;
		this.employeesByModifiedBy = employeesByModifiedBy;
		this.employeesByCreateBy = employeesByCreateBy;
		this.fileName = fileName;
		this.kpiDate = kpiDate;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.url = url;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KPI_ID", unique = true, nullable = false)
	public Integer getKpiId() {
		return this.kpiId;
	}

	public void setKpiId(Integer kpiId) {
		this.kpiId = kpiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployeesByEmployeeId() {
		return this.employeesByEmployeeId;
	}

	public void setEmployeesByEmployeeId(Employees employeesByEmployeeId) {
		this.employeesByEmployeeId = employeesByEmployeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY")
	public Employees getEmployeesByModifiedBy() {
		return this.employeesByModifiedBy;
	}

	public void setEmployeesByModifiedBy(Employees employeesByModifiedBy) {
		this.employeesByModifiedBy = employeesByModifiedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_BY")
	public Employees getEmployeesByCreateBy() {
		return this.employeesByCreateBy;
	}

	public void setEmployeesByCreateBy(Employees employeesByCreateBy) {
		this.employeesByCreateBy = employeesByCreateBy;
	}

	@Column(name = "FILE_NAME")
	public Serializable getFileName() {
		return this.fileName;
	}

	public void setFileName(Serializable fileName) {
		this.fileName = fileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "KPI_DATE", length = 23)
	public Date getKpiDate() {
		return this.kpiDate;
	}

	public void setKpiDate(Date kpiDate) {
		this.kpiDate = kpiDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 23)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "URL")
	public Serializable getUrl() {
		return this.url;
	}

	public void setUrl(Serializable url) {
		this.url = url;
	}

	@Column(name = "NOTES")
	public Serializable getNotes() {
		return this.notes;
	}

	public void setNotes(Serializable notes) {
		this.notes = notes;
	}

}
