package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeIncomeStats generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_INCOME_STATS", catalog = "eHRM_JavaResearching")
public class EmployeeIncomeStats implements java.io.Serializable {

	private Integer employeeIncomeStatsId;
	private Employees employees;
	private MasterDatas masterDatas;
	private Periods periods;
	private BigDecimal totalIncome;
	private BigDecimal massIncome;
	private BigDecimal employeeContribution;
	private BigDecimal employerContribution;
	private BigDecimal impost;
	private BigDecimal exchangeRate;
	private BigDecimal netIncome;

	public EmployeeIncomeStats() {
	}

	public EmployeeIncomeStats(Employees employees, MasterDatas masterDatas, Periods periods, BigDecimal totalIncome,
			BigDecimal massIncome, BigDecimal employeeContribution, BigDecimal employerContribution, BigDecimal impost,
			BigDecimal exchangeRate, BigDecimal netIncome) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.periods = periods;
		this.totalIncome = totalIncome;
		this.massIncome = massIncome;
		this.employeeContribution = employeeContribution;
		this.employerContribution = employerContribution;
		this.impost = impost;
		this.exchangeRate = exchangeRate;
		this.netIncome = netIncome;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_INCOME_STATS_ID", unique = true, nullable = false)
	public Integer getEmployeeIncomeStatsId() {
		return this.employeeIncomeStatsId;
	}

	public void setEmployeeIncomeStatsId(Integer employeeIncomeStatsId) {
		this.employeeIncomeStatsId = employeeIncomeStatsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIOD_ID", nullable = false)
	public Periods getPeriods() {
		return this.periods;
	}

	public void setPeriods(Periods periods) {
		this.periods = periods;
	}

	@Column(name = "TOTAL_INCOME", nullable = false, precision = 18, scale = 4)
	public BigDecimal getTotalIncome() {
		return this.totalIncome;
	}

	public void setTotalIncome(BigDecimal totalIncome) {
		this.totalIncome = totalIncome;
	}

	@Column(name = "MASS_INCOME", nullable = false, precision = 18, scale = 4)
	public BigDecimal getMassIncome() {
		return this.massIncome;
	}

	public void setMassIncome(BigDecimal massIncome) {
		this.massIncome = massIncome;
	}

	@Column(name = "EMPLOYEE_CONTRIBUTION", nullable = false, precision = 18, scale = 4)
	public BigDecimal getEmployeeContribution() {
		return this.employeeContribution;
	}

	public void setEmployeeContribution(BigDecimal employeeContribution) {
		this.employeeContribution = employeeContribution;
	}

	@Column(name = "EMPLOYER_CONTRIBUTION", nullable = false, precision = 18, scale = 4)
	public BigDecimal getEmployerContribution() {
		return this.employerContribution;
	}

	public void setEmployerContribution(BigDecimal employerContribution) {
		this.employerContribution = employerContribution;
	}

	@Column(name = "IMPOST", nullable = false, precision = 18, scale = 4)
	public BigDecimal getImpost() {
		return this.impost;
	}

	public void setImpost(BigDecimal impost) {
		this.impost = impost;
	}

	@Column(name = "EXCHANGE_RATE", nullable = false, precision = 18, scale = 4)
	public BigDecimal getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "NET_INCOME", nullable = false, precision = 18)
	public BigDecimal getNetIncome() {
		return this.netIncome;
	}

	public void setNetIncome(BigDecimal netIncome) {
		this.netIncome = netIncome;
	}

}
