package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeEmails generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_EMAILS", catalog = "eHRM_JavaResearching")
public class EmployeeEmails implements java.io.Serializable {

	private Integer employeeEmailId;
	private Employees employees;
	private MasterDatas masterDatas;
	private String emailAddress;
	private boolean active;

	public EmployeeEmails() {
	}

	public EmployeeEmails(Employees employees, MasterDatas masterDatas, String emailAddress, boolean active) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.emailAddress = emailAddress;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_EMAIL_ID", unique = true, nullable = false)
	public Integer getEmployeeEmailId() {
		return this.employeeEmailId;
	}

	public void setEmployeeEmailId(Integer employeeEmailId) {
		this.employeeEmailId = employeeEmailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMAIL_TYPE_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
