package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinancialYears generated by hbm2java
 */
@Entity
@Table(name = "FINANCIAL_YEARS", catalog = "eHRM_JavaResearching")
public class FinancialYears implements java.io.Serializable {

	private Integer financialYearId;
	private String financialYearName;
	private Date financialYearStartDate;
	private Date financialYearEndDate;
	private Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses = new HashSet<LeaveCarryForwardRequests>(0);
	private Set<ReviewTimeConfig> reviewTimeConfigs = new HashSet<ReviewTimeConfig>(0);
	private Set<EmployeeDisciplines> employeeDisciplineses = new HashSet<EmployeeDisciplines>(0);
	private Set<EmployeeMboRecords> employeeMboRecordses = new HashSet<EmployeeMboRecords>(0);
	private Set<BudgetedConfig> budgetedConfigs = new HashSet<BudgetedConfig>(0);
	private Set<EmployeeKaizenAwards> employeeKaizenAwardses = new HashSet<EmployeeKaizenAwards>(0);
	private Set<Periods> periodses = new HashSet<Periods>(0);

	public FinancialYears() {
	}

	public FinancialYears(String financialYearName, Date financialYearStartDate, Date financialYearEndDate) {
		this.financialYearName = financialYearName;
		this.financialYearStartDate = financialYearStartDate;
		this.financialYearEndDate = financialYearEndDate;
	}

	public FinancialYears(String financialYearName, Date financialYearStartDate, Date financialYearEndDate,
			Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses, Set<ReviewTimeConfig> reviewTimeConfigs,
			Set<EmployeeDisciplines> employeeDisciplineses, Set<EmployeeMboRecords> employeeMboRecordses,
			Set<BudgetedConfig> budgetedConfigs, Set<EmployeeKaizenAwards> employeeKaizenAwardses,
			Set<Periods> periodses) {
		this.financialYearName = financialYearName;
		this.financialYearStartDate = financialYearStartDate;
		this.financialYearEndDate = financialYearEndDate;
		this.leaveCarryForwardRequestses = leaveCarryForwardRequestses;
		this.reviewTimeConfigs = reviewTimeConfigs;
		this.employeeDisciplineses = employeeDisciplineses;
		this.employeeMboRecordses = employeeMboRecordses;
		this.budgetedConfigs = budgetedConfigs;
		this.employeeKaizenAwardses = employeeKaizenAwardses;
		this.periodses = periodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FINANCIAL_YEAR_ID", unique = true, nullable = false)
	public Integer getFinancialYearId() {
		return this.financialYearId;
	}

	public void setFinancialYearId(Integer financialYearId) {
		this.financialYearId = financialYearId;
	}

	@Column(name = "FINANCIAL_YEAR_NAME", nullable = false)
	public String getFinancialYearName() {
		return this.financialYearName;
	}

	public void setFinancialYearName(String financialYearName) {
		this.financialYearName = financialYearName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FINANCIAL_YEAR_START_DATE", nullable = false, length = 10)
	public Date getFinancialYearStartDate() {
		return this.financialYearStartDate;
	}

	public void setFinancialYearStartDate(Date financialYearStartDate) {
		this.financialYearStartDate = financialYearStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FINANCIAL_YEAR_END_DATE", nullable = false, length = 10)
	public Date getFinancialYearEndDate() {
		return this.financialYearEndDate;
	}

	public void setFinancialYearEndDate(Date financialYearEndDate) {
		this.financialYearEndDate = financialYearEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<LeaveCarryForwardRequests> getLeaveCarryForwardRequestses() {
		return this.leaveCarryForwardRequestses;
	}

	public void setLeaveCarryForwardRequestses(Set<LeaveCarryForwardRequests> leaveCarryForwardRequestses) {
		this.leaveCarryForwardRequestses = leaveCarryForwardRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<ReviewTimeConfig> getReviewTimeConfigs() {
		return this.reviewTimeConfigs;
	}

	public void setReviewTimeConfigs(Set<ReviewTimeConfig> reviewTimeConfigs) {
		this.reviewTimeConfigs = reviewTimeConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<EmployeeDisciplines> getEmployeeDisciplineses() {
		return this.employeeDisciplineses;
	}

	public void setEmployeeDisciplineses(Set<EmployeeDisciplines> employeeDisciplineses) {
		this.employeeDisciplineses = employeeDisciplineses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<EmployeeMboRecords> getEmployeeMboRecordses() {
		return this.employeeMboRecordses;
	}

	public void setEmployeeMboRecordses(Set<EmployeeMboRecords> employeeMboRecordses) {
		this.employeeMboRecordses = employeeMboRecordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<BudgetedConfig> getBudgetedConfigs() {
		return this.budgetedConfigs;
	}

	public void setBudgetedConfigs(Set<BudgetedConfig> budgetedConfigs) {
		this.budgetedConfigs = budgetedConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<EmployeeKaizenAwards> getEmployeeKaizenAwardses() {
		return this.employeeKaizenAwardses;
	}

	public void setEmployeeKaizenAwardses(Set<EmployeeKaizenAwards> employeeKaizenAwardses) {
		this.employeeKaizenAwardses = employeeKaizenAwardses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialYears")
	public Set<Periods> getPeriodses() {
		return this.periodses;
	}

	public void setPeriodses(Set<Periods> periodses) {
		this.periodses = periodses;
	}

	@Override
	public String toString() {
		return "FinancialYears [financialYearId=" + financialYearId + ", financialYearName=" + financialYearName.toString()
				+ ", financialYearStartDate=" + financialYearStartDate.toString() + ", financialYearEndDate="
				+ financialYearEndDate.toString() + "]";
	}
	
}
