package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hierarchicals generated by hbm2java
 */
@Entity
@Table(name = "HIERARCHICALS", catalog = "eHRM_JavaResearching")
public class Hierarchicals implements java.io.Serializable {

	private Integer hierarchicalId;
	private Hierarchicals hierarchicals;
	private Serializable hierarchicalLevel;
	private Serializable hierarchicalCode;
	private Serializable hierarchicalDescription;
	private Set<Hierarchicals> hierarchicalses = new HashSet<Hierarchicals>(0);
	private Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses = new HashSet<LeaveCoefficientHierarchicals>(
			0);
	private Set<EmployeeHierarchicals> employeeHierarchicalses = new HashSet<EmployeeHierarchicals>(0);

	public Hierarchicals() {
	}

	public Hierarchicals(Serializable hierarchicalLevel, Serializable hierarchicalCode) {
		this.hierarchicalLevel = hierarchicalLevel;
		this.hierarchicalCode = hierarchicalCode;
	}

	public Hierarchicals(Hierarchicals hierarchicals, Serializable hierarchicalLevel, Serializable hierarchicalCode,
			Serializable hierarchicalDescription, Set<Hierarchicals> hierarchicalses,
			Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses,
			Set<EmployeeHierarchicals> employeeHierarchicalses) {
		this.hierarchicals = hierarchicals;
		this.hierarchicalLevel = hierarchicalLevel;
		this.hierarchicalCode = hierarchicalCode;
		this.hierarchicalDescription = hierarchicalDescription;
		this.hierarchicalses = hierarchicalses;
		this.leaveCoefficientHierarchicalses = leaveCoefficientHierarchicalses;
		this.employeeHierarchicalses = employeeHierarchicalses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "HIERARCHICAL_ID", unique = true, nullable = false)
	public Integer getHierarchicalId() {
		return this.hierarchicalId;
	}

	public void setHierarchicalId(Integer hierarchicalId) {
		this.hierarchicalId = hierarchicalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HIERARCHICAL_PARENT_ID")
	public Hierarchicals getHierarchicals() {
		return this.hierarchicals;
	}

	public void setHierarchicals(Hierarchicals hierarchicals) {
		this.hierarchicals = hierarchicals;
	}

	@Column(name = "HIERARCHICAL_LEVEL", nullable = false)
	public Serializable getHierarchicalLevel() {
		return this.hierarchicalLevel;
	}

	public void setHierarchicalLevel(Serializable hierarchicalLevel) {
		this.hierarchicalLevel = hierarchicalLevel;
	}

	@Column(name = "HIERARCHICAL_CODE", nullable = false)
	public Serializable getHierarchicalCode() {
		return this.hierarchicalCode;
	}

	public void setHierarchicalCode(Serializable hierarchicalCode) {
		this.hierarchicalCode = hierarchicalCode;
	}

	@Column(name = "HIERARCHICAL_DESCRIPTION")
	public Serializable getHierarchicalDescription() {
		return this.hierarchicalDescription;
	}

	public void setHierarchicalDescription(Serializable hierarchicalDescription) {
		this.hierarchicalDescription = hierarchicalDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hierarchicals")
	public Set<Hierarchicals> getHierarchicalses() {
		return this.hierarchicalses;
	}

	public void setHierarchicalses(Set<Hierarchicals> hierarchicalses) {
		this.hierarchicalses = hierarchicalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hierarchicals")
	public Set<LeaveCoefficientHierarchicals> getLeaveCoefficientHierarchicalses() {
		return this.leaveCoefficientHierarchicalses;
	}

	public void setLeaveCoefficientHierarchicalses(Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses) {
		this.leaveCoefficientHierarchicalses = leaveCoefficientHierarchicalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hierarchicals")
	public Set<EmployeeHierarchicals> getEmployeeHierarchicalses() {
		return this.employeeHierarchicalses;
	}

	public void setEmployeeHierarchicalses(Set<EmployeeHierarchicals> employeeHierarchicalses) {
		this.employeeHierarchicalses = employeeHierarchicalses;
	}

}
