package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IncomeModels generated by hbm2java
 */
@Entity
@Table(name = "INCOME_MODELS", catalog = "eHRM_JavaResearching")
public class IncomeModels implements java.io.Serializable {

	private Integer incomeModelId;
	private Incomes incomes;
	private MasterDatas masterDatas;
	private BigDecimal incomeModelValue;
	private Date startDate;
	private Date endDate;

	public IncomeModels() {
	}

	public IncomeModels(Incomes incomes, MasterDatas masterDatas) {
		this.incomes = incomes;
		this.masterDatas = masterDatas;
	}

	public IncomeModels(Incomes incomes, MasterDatas masterDatas, BigDecimal incomeModelValue, Date startDate,
			Date endDate) {
		this.incomes = incomes;
		this.masterDatas = masterDatas;
		this.incomeModelValue = incomeModelValue;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INCOME_MODEL_ID", unique = true, nullable = false)
	public Integer getIncomeModelId() {
		return this.incomeModelId;
	}

	public void setIncomeModelId(Integer incomeModelId) {
		this.incomeModelId = incomeModelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INCOME_ID", nullable = false)
	public Incomes getIncomes() {
		return this.incomes;
	}

	public void setIncomes(Incomes incomes) {
		this.incomes = incomes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODEL_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Column(name = "INCOME_MODEL_VALUE", precision = 18, scale = 4)
	public BigDecimal getIncomeModelValue() {
		return this.incomeModelValue;
	}

	public void setIncomeModelValue(BigDecimal incomeModelValue) {
		this.incomeModelValue = incomeModelValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
