package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LeaveCoefficients generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_COEFFICIENTS", catalog = "eHRM_JavaResearching")
public class LeaveCoefficients implements java.io.Serializable {

	private Integer leaveCoefficientId;
	private Serializable leaveCoefficientCode;
	private Serializable leaveCoefficientName;
	private Serializable leaveCoefficientDescription;
	private double defaultCoefficient;
	private int orderIndex;
	private Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses = new HashSet<LeaveCoefficientLeaveTypes>(0);
	private Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses = new HashSet<LeaveCoefficientHierarchicals>(
			0);

	public LeaveCoefficients() {
	}

	public LeaveCoefficients(Serializable leaveCoefficientCode, Serializable leaveCoefficientName,
			double defaultCoefficient, int orderIndex) {
		this.leaveCoefficientCode = leaveCoefficientCode;
		this.leaveCoefficientName = leaveCoefficientName;
		this.defaultCoefficient = defaultCoefficient;
		this.orderIndex = orderIndex;
	}

	public LeaveCoefficients(Serializable leaveCoefficientCode, Serializable leaveCoefficientName,
			Serializable leaveCoefficientDescription, double defaultCoefficient, int orderIndex,
			Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses,
			Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses) {
		this.leaveCoefficientCode = leaveCoefficientCode;
		this.leaveCoefficientName = leaveCoefficientName;
		this.leaveCoefficientDescription = leaveCoefficientDescription;
		this.defaultCoefficient = defaultCoefficient;
		this.orderIndex = orderIndex;
		this.leaveCoefficientLeaveTypeses = leaveCoefficientLeaveTypeses;
		this.leaveCoefficientHierarchicalses = leaveCoefficientHierarchicalses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_COEFFICIENT_ID", unique = true, nullable = false)
	public Integer getLeaveCoefficientId() {
		return this.leaveCoefficientId;
	}

	public void setLeaveCoefficientId(Integer leaveCoefficientId) {
		this.leaveCoefficientId = leaveCoefficientId;
	}

	@Column(name = "LEAVE_COEFFICIENT_CODE", nullable = false)
	public Serializable getLeaveCoefficientCode() {
		return this.leaveCoefficientCode;
	}

	public void setLeaveCoefficientCode(Serializable leaveCoefficientCode) {
		this.leaveCoefficientCode = leaveCoefficientCode;
	}

	@Column(name = "LEAVE_COEFFICIENT_NAME", nullable = false)
	public Serializable getLeaveCoefficientName() {
		return this.leaveCoefficientName;
	}

	public void setLeaveCoefficientName(Serializable leaveCoefficientName) {
		this.leaveCoefficientName = leaveCoefficientName;
	}

	@Column(name = "LEAVE_COEFFICIENT_DESCRIPTION")
	public Serializable getLeaveCoefficientDescription() {
		return this.leaveCoefficientDescription;
	}

	public void setLeaveCoefficientDescription(Serializable leaveCoefficientDescription) {
		this.leaveCoefficientDescription = leaveCoefficientDescription;
	}

	@Column(name = "DEFAULT_COEFFICIENT", nullable = false, precision = 53, scale = 0)
	public double getDefaultCoefficient() {
		return this.defaultCoefficient;
	}

	public void setDefaultCoefficient(double defaultCoefficient) {
		this.defaultCoefficient = defaultCoefficient;
	}

	@Column(name = "ORDER_INDEX", nullable = false)
	public int getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(int orderIndex) {
		this.orderIndex = orderIndex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveCoefficients")
	public Set<LeaveCoefficientLeaveTypes> getLeaveCoefficientLeaveTypeses() {
		return this.leaveCoefficientLeaveTypeses;
	}

	public void setLeaveCoefficientLeaveTypeses(Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses) {
		this.leaveCoefficientLeaveTypeses = leaveCoefficientLeaveTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveCoefficients")
	public Set<LeaveCoefficientHierarchicals> getLeaveCoefficientHierarchicalses() {
		return this.leaveCoefficientHierarchicalses;
	}

	public void setLeaveCoefficientHierarchicalses(Set<LeaveCoefficientHierarchicals> leaveCoefficientHierarchicalses) {
		this.leaveCoefficientHierarchicalses = leaveCoefficientHierarchicalses;
	}

}
