package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveEmployeeBalances generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_EMPLOYEE_BALANCES", catalog = "eHRM_JavaResearching")
public class LeaveEmployeeBalances implements java.io.Serializable {

	private Integer leaveEmployeeBalanceId;
	private Employees employees;
	private LeaveTypesetting leaveTypesetting;
	private double initialBalance;
	private double coefficient;
	private Date startDate;
	private Date endDate;
	private Serializable notes;
	private Boolean isUpdate;
	private Double movedBalance;

	public LeaveEmployeeBalances() {
	}

	public LeaveEmployeeBalances(Employees employees, LeaveTypesetting leaveTypesetting, double initialBalance,
			double coefficient, Date startDate, Date endDate) {
		this.employees = employees;
		this.leaveTypesetting = leaveTypesetting;
		this.initialBalance = initialBalance;
		this.coefficient = coefficient;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public LeaveEmployeeBalances(Employees employees, LeaveTypesetting leaveTypesetting, double initialBalance,
			double coefficient, Date startDate, Date endDate, Serializable notes, Boolean isUpdate,
			Double movedBalance) {
		this.employees = employees;
		this.leaveTypesetting = leaveTypesetting;
		this.initialBalance = initialBalance;
		this.coefficient = coefficient;
		this.startDate = startDate;
		this.endDate = endDate;
		this.notes = notes;
		this.isUpdate = isUpdate;
		this.movedBalance = movedBalance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_EMPLOYEE_BALANCE_ID", unique = true, nullable = false)
	public Integer getLeaveEmployeeBalanceId() {
		return this.leaveEmployeeBalanceId;
	}

	public void setLeaveEmployeeBalanceId(Integer leaveEmployeeBalanceId) {
		this.leaveEmployeeBalanceId = leaveEmployeeBalanceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_TYPE_ID", nullable = false)
	public LeaveTypesetting getLeaveTypesetting() {
		return this.leaveTypesetting;
	}

	public void setLeaveTypesetting(LeaveTypesetting leaveTypesetting) {
		this.leaveTypesetting = leaveTypesetting;
	}

	@Column(name = "INITIAL_BALANCE", nullable = false, precision = 53, scale = 0)
	public double getInitialBalance() {
		return this.initialBalance;
	}

	public void setInitialBalance(double initialBalance) {
		this.initialBalance = initialBalance;
	}

	@Column(name = "COEFFICIENT", nullable = false, precision = 53, scale = 0)
	public double getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(double coefficient) {
		this.coefficient = coefficient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "NOTES")
	public Serializable getNotes() {
		return this.notes;
	}

	public void setNotes(Serializable notes) {
		this.notes = notes;
	}

	@Column(name = "IS_UPDATE")
	public Boolean getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(Boolean isUpdate) {
		this.isUpdate = isUpdate;
	}

	@Column(name = "MOVED_BALANCE", precision = 53, scale = 0)
	public Double getMovedBalance() {
		return this.movedBalance;
	}

	public void setMovedBalance(Double movedBalance) {
		this.movedBalance = movedBalance;
	}

}
