package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveRequests generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_REQUESTS", catalog = "eHRM_JavaResearching")
public class LeaveRequests implements java.io.Serializable {

	private Integer leaveRequestId;
	private Employees employees;
	private LeaveRequests leaveRequests;
	private LeaveTypesetting leaveTypesetting;
	private MasterDatas masterDatas;
	private Date startDate;
	private String startDateTime;
	private Date endDate;
	private String endDateTime;
	private double noOfWorkingDays;
	private double noOfCalendarDays;
	private Date requestDate;
	private Serializable requestContent;
	private int countApprove;
	private Integer overtimeScheduleId;
	private Double hoursCompensation;
	private Set<LeaveRequestHistories> leaveRequestHistorieses = new HashSet<LeaveRequestHistories>(0);
	private Set<LeaveRequests> leaveRequestses = new HashSet<LeaveRequests>(0);

	public LeaveRequests() {
	}

	public LeaveRequests(Employees employees, LeaveTypesetting leaveTypesetting, MasterDatas masterDatas,
			Date startDate, String startDateTime, Date endDate, String endDateTime, double noOfWorkingDays,
			double noOfCalendarDays, Serializable requestContent, int countApprove) {
		this.employees = employees;
		this.leaveTypesetting = leaveTypesetting;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.startDateTime = startDateTime;
		this.endDate = endDate;
		this.endDateTime = endDateTime;
		this.noOfWorkingDays = noOfWorkingDays;
		this.noOfCalendarDays = noOfCalendarDays;
		this.requestContent = requestContent;
		this.countApprove = countApprove;
	}

	public LeaveRequests(Employees employees, LeaveRequests leaveRequests, LeaveTypesetting leaveTypesetting,
			MasterDatas masterDatas, Date startDate, String startDateTime, Date endDate, String endDateTime,
			double noOfWorkingDays, double noOfCalendarDays, Date requestDate, Serializable requestContent,
			int countApprove, Integer overtimeScheduleId, Double hoursCompensation,
			Set<LeaveRequestHistories> leaveRequestHistorieses, Set<LeaveRequests> leaveRequestses) {
		this.employees = employees;
		this.leaveRequests = leaveRequests;
		this.leaveTypesetting = leaveTypesetting;
		this.masterDatas = masterDatas;
		this.startDate = startDate;
		this.startDateTime = startDateTime;
		this.endDate = endDate;
		this.endDateTime = endDateTime;
		this.noOfWorkingDays = noOfWorkingDays;
		this.noOfCalendarDays = noOfCalendarDays;
		this.requestDate = requestDate;
		this.requestContent = requestContent;
		this.countApprove = countApprove;
		this.overtimeScheduleId = overtimeScheduleId;
		this.hoursCompensation = hoursCompensation;
		this.leaveRequestHistorieses = leaveRequestHistorieses;
		this.leaveRequestses = leaveRequestses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_REQUEST_ID", unique = true, nullable = false)
	public Integer getLeaveRequestId() {
		return this.leaveRequestId;
	}

	public void setLeaveRequestId(Integer leaveRequestId) {
		this.leaveRequestId = leaveRequestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_REQUESTSREPLACEID")
	public LeaveRequests getLeaveRequests() {
		return this.leaveRequests;
	}

	public void setLeaveRequests(LeaveRequests leaveRequests) {
		this.leaveRequests = leaveRequests;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_TYPE_ID", nullable = false)
	public LeaveTypesetting getLeaveTypesetting() {
		return this.leaveTypesetting;
	}

	public void setLeaveTypesetting(LeaveTypesetting leaveTypesetting) {
		this.leaveTypesetting = leaveTypesetting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_REQUEST_STATUS_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "START_DATE_TIME", nullable = false, length = 2)
	public String getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(String startDateTime) {
		this.startDateTime = startDateTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "END_DATE_TIME", nullable = false, length = 2)
	public String getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(String endDateTime) {
		this.endDateTime = endDateTime;
	}

	@Column(name = "NO_OF_WORKING_DAYS", nullable = false, precision = 53, scale = 0)
	public double getNoOfWorkingDays() {
		return this.noOfWorkingDays;
	}

	public void setNoOfWorkingDays(double noOfWorkingDays) {
		this.noOfWorkingDays = noOfWorkingDays;
	}

	@Column(name = "NO_OF_CALENDAR_DAYS", nullable = false, precision = 53, scale = 0)
	public double getNoOfCalendarDays() {
		return this.noOfCalendarDays;
	}

	public void setNoOfCalendarDays(double noOfCalendarDays) {
		this.noOfCalendarDays = noOfCalendarDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_DATE", length = 23)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Column(name = "REQUEST_CONTENT", nullable = false)
	public Serializable getRequestContent() {
		return this.requestContent;
	}

	public void setRequestContent(Serializable requestContent) {
		this.requestContent = requestContent;
	}

	@Column(name = "COUNT_APPROVE", nullable = false)
	public int getCountApprove() {
		return this.countApprove;
	}

	public void setCountApprove(int countApprove) {
		this.countApprove = countApprove;
	}

	@Column(name = "OVERTIME_SCHEDULE_ID")
	public Integer getOvertimeScheduleId() {
		return this.overtimeScheduleId;
	}

	public void setOvertimeScheduleId(Integer overtimeScheduleId) {
		this.overtimeScheduleId = overtimeScheduleId;
	}

	@Column(name = "HOURS_COMPENSATION", precision = 53, scale = 0)
	public Double getHoursCompensation() {
		return this.hoursCompensation;
	}

	public void setHoursCompensation(Double hoursCompensation) {
		this.hoursCompensation = hoursCompensation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveRequests")
	public Set<LeaveRequestHistories> getLeaveRequestHistorieses() {
		return this.leaveRequestHistorieses;
	}

	public void setLeaveRequestHistorieses(Set<LeaveRequestHistories> leaveRequestHistorieses) {
		this.leaveRequestHistorieses = leaveRequestHistorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveRequests")
	public Set<LeaveRequests> getLeaveRequestses() {
		return this.leaveRequestses;
	}

	public void setLeaveRequestses(Set<LeaveRequests> leaveRequestses) {
		this.leaveRequestses = leaveRequestses;
	}

}
