package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LeaveCoefficientLeaveTypes generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_COEFFICIENT_LEAVE_TYPES", catalog = "eHRM_JavaResearching")
public class LeaveCoefficientLeaveTypes implements java.io.Serializable {

	private Integer leaveCoefficientLeaveTypeId;
	private LeaveCoefficients leaveCoefficients;
	private LeaveTypesetting leaveTypesetting;

	public LeaveCoefficientLeaveTypes() {
	}

	public LeaveCoefficientLeaveTypes(LeaveCoefficients leaveCoefficients, LeaveTypesetting leaveTypesetting) {
		this.leaveCoefficients = leaveCoefficients;
		this.leaveTypesetting = leaveTypesetting;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_COEFFICIENT_LEAVE_TYPE_ID", unique = true, nullable = false)
	public Integer getLeaveCoefficientLeaveTypeId() {
		return this.leaveCoefficientLeaveTypeId;
	}

	public void setLeaveCoefficientLeaveTypeId(Integer leaveCoefficientLeaveTypeId) {
		this.leaveCoefficientLeaveTypeId = leaveCoefficientLeaveTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_COEFFICIENT_ID", nullable = false)
	public LeaveCoefficients getLeaveCoefficients() {
		return this.leaveCoefficients;
	}

	public void setLeaveCoefficients(LeaveCoefficients leaveCoefficients) {
		this.leaveCoefficients = leaveCoefficients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_TYPE_ID", nullable = false)
	public LeaveTypesetting getLeaveTypesetting() {
		return this.leaveTypesetting;
	}

	public void setLeaveTypesetting(LeaveTypesetting leaveTypesetting) {
		this.leaveTypesetting = leaveTypesetting;
	}

}
