package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LeaveTypesetting generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_TYPESETTING", catalog = "eHRM_JavaResearching")
public class LeaveTypesetting implements java.io.Serializable {

	private Integer leaveTypesettingId;
	private Serializable leaveTypesettingCode;
	private Serializable leaveTypesettingName;
	private boolean isPaidLeave;
	private boolean isSickLeave;
	private boolean isBankpay;
	private Integer orderIndex;
	private boolean isDefault;
	private Set<LeaveRequests> leaveRequestses = new HashSet<LeaveRequests>(0);
	private Set<LeaveEmployeeBalances> leaveEmployeeBalanceses = new HashSet<LeaveEmployeeBalances>(0);
	private Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses = new HashSet<LeaveCoefficientLeaveTypes>(0);
	private Set<LeaveTypes> leaveTypeses = new HashSet<LeaveTypes>(0);
	private Set<LeaveTypeCountries> leaveTypeCountrieses = new HashSet<LeaveTypeCountries>(0);

	public LeaveTypesetting() {
	}

	public LeaveTypesetting(Serializable leaveTypesettingCode, Serializable leaveTypesettingName, boolean isPaidLeave,
			boolean isSickLeave, boolean isBankpay, boolean isDefault) {
		this.leaveTypesettingCode = leaveTypesettingCode;
		this.leaveTypesettingName = leaveTypesettingName;
		this.isPaidLeave = isPaidLeave;
		this.isSickLeave = isSickLeave;
		this.isBankpay = isBankpay;
		this.isDefault = isDefault;
	}

	public LeaveTypesetting(Serializable leaveTypesettingCode, Serializable leaveTypesettingName, boolean isPaidLeave,
			boolean isSickLeave, boolean isBankpay, Integer orderIndex, boolean isDefault,
			Set<LeaveRequests> leaveRequestses, Set<LeaveEmployeeBalances> leaveEmployeeBalanceses,
			Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses, Set<LeaveTypes> leaveTypeses,
			Set<LeaveTypeCountries> leaveTypeCountrieses) {
		this.leaveTypesettingCode = leaveTypesettingCode;
		this.leaveTypesettingName = leaveTypesettingName;
		this.isPaidLeave = isPaidLeave;
		this.isSickLeave = isSickLeave;
		this.isBankpay = isBankpay;
		this.orderIndex = orderIndex;
		this.isDefault = isDefault;
		this.leaveRequestses = leaveRequestses;
		this.leaveEmployeeBalanceses = leaveEmployeeBalanceses;
		this.leaveCoefficientLeaveTypeses = leaveCoefficientLeaveTypeses;
		this.leaveTypeses = leaveTypeses;
		this.leaveTypeCountrieses = leaveTypeCountrieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_TYPESETTING_ID", unique = true, nullable = false)
	public Integer getLeaveTypesettingId() {
		return this.leaveTypesettingId;
	}

	public void setLeaveTypesettingId(Integer leaveTypesettingId) {
		this.leaveTypesettingId = leaveTypesettingId;
	}

	@Column(name = "LEAVE_TYPESETTING_CODE", nullable = false)
	public Serializable getLeaveTypesettingCode() {
		return this.leaveTypesettingCode;
	}

	public void setLeaveTypesettingCode(Serializable leaveTypesettingCode) {
		this.leaveTypesettingCode = leaveTypesettingCode;
	}

	@Column(name = "LEAVE_TYPESETTING_NAME", nullable = false)
	public Serializable getLeaveTypesettingName() {
		return this.leaveTypesettingName;
	}

	public void setLeaveTypesettingName(Serializable leaveTypesettingName) {
		this.leaveTypesettingName = leaveTypesettingName;
	}

	@Column(name = "IS_PAID_LEAVE", nullable = false)
	public boolean isIsPaidLeave() {
		return this.isPaidLeave;
	}

	public void setIsPaidLeave(boolean isPaidLeave) {
		this.isPaidLeave = isPaidLeave;
	}

	@Column(name = "IS_SICK_LEAVE", nullable = false)
	public boolean isIsSickLeave() {
		return this.isSickLeave;
	}

	public void setIsSickLeave(boolean isSickLeave) {
		this.isSickLeave = isSickLeave;
	}

	@Column(name = "IS_BANKPAY", nullable = false)
	public boolean isIsBankpay() {
		return this.isBankpay;
	}

	public void setIsBankpay(boolean isBankpay) {
		this.isBankpay = isBankpay;
	}

	@Column(name = "ORDER_INDEX")
	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveTypesetting")
	public Set<LeaveRequests> getLeaveRequestses() {
		return this.leaveRequestses;
	}

	public void setLeaveRequestses(Set<LeaveRequests> leaveRequestses) {
		this.leaveRequestses = leaveRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveTypesetting")
	public Set<LeaveEmployeeBalances> getLeaveEmployeeBalanceses() {
		return this.leaveEmployeeBalanceses;
	}

	public void setLeaveEmployeeBalanceses(Set<LeaveEmployeeBalances> leaveEmployeeBalanceses) {
		this.leaveEmployeeBalanceses = leaveEmployeeBalanceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveTypesetting")
	public Set<LeaveCoefficientLeaveTypes> getLeaveCoefficientLeaveTypeses() {
		return this.leaveCoefficientLeaveTypeses;
	}

	public void setLeaveCoefficientLeaveTypeses(Set<LeaveCoefficientLeaveTypes> leaveCoefficientLeaveTypeses) {
		this.leaveCoefficientLeaveTypeses = leaveCoefficientLeaveTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveTypesetting")
	public Set<LeaveTypes> getLeaveTypeses() {
		return this.leaveTypeses;
	}

	public void setLeaveTypeses(Set<LeaveTypes> leaveTypeses) {
		this.leaveTypeses = leaveTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "leaveTypesetting")
	public Set<LeaveTypeCountries> getLeaveTypeCountrieses() {
		return this.leaveTypeCountrieses;
	}

	public void setLeaveTypeCountrieses(Set<LeaveTypeCountries> leaveTypeCountrieses) {
		this.leaveTypeCountrieses = leaveTypeCountrieses;
	}

}
