package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LeaveTypes generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_TYPES", catalog = "eHRM_JavaResearching")
public class LeaveTypes implements java.io.Serializable {

	private Integer leaveTypeId;
	private ApprovalLevels approvalLevels;
	private LeaveTypesetting leaveTypesetting;
	private RoleApprovalLevel roleApprovalLevel;
	private Integer leaveContinuous;
	private Integer valueDayLeaveContinuous;
	private Integer leaveCompensation;
	private String approvedOrder;

	public LeaveTypes() {
	}

	public LeaveTypes(ApprovalLevels approvalLevels, LeaveTypesetting leaveTypesetting,
			RoleApprovalLevel roleApprovalLevel, Integer leaveContinuous, Integer valueDayLeaveContinuous,
			Integer leaveCompensation, String approvedOrder) {
		this.approvalLevels = approvalLevels;
		this.leaveTypesetting = leaveTypesetting;
		this.roleApprovalLevel = roleApprovalLevel;
		this.leaveContinuous = leaveContinuous;
		this.valueDayLeaveContinuous = valueDayLeaveContinuous;
		this.leaveCompensation = leaveCompensation;
		this.approvedOrder = approvedOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_TYPE_ID", unique = true, nullable = false)
	public Integer getLeaveTypeId() {
		return this.leaveTypeId;
	}

	public void setLeaveTypeId(Integer leaveTypeId) {
		this.leaveTypeId = leaveTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVAL_LEVEL_ID")
	public ApprovalLevels getApprovalLevels() {
		return this.approvalLevels;
	}

	public void setApprovalLevels(ApprovalLevels approvalLevels) {
		this.approvalLevels = approvalLevels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASTER_DATA_ID")
	public LeaveTypesetting getLeaveTypesetting() {
		return this.leaveTypesetting;
	}

	public void setLeaveTypesetting(LeaveTypesetting leaveTypesetting) {
		this.leaveTypesetting = leaveTypesetting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_APPROVAL_LEVEL_ID")
	public RoleApprovalLevel getRoleApprovalLevel() {
		return this.roleApprovalLevel;
	}

	public void setRoleApprovalLevel(RoleApprovalLevel roleApprovalLevel) {
		this.roleApprovalLevel = roleApprovalLevel;
	}

	@Column(name = "LEAVE_CONTINUOUS")
	public Integer getLeaveContinuous() {
		return this.leaveContinuous;
	}

	public void setLeaveContinuous(Integer leaveContinuous) {
		this.leaveContinuous = leaveContinuous;
	}

	@Column(name = "VALUE_DAY_LEAVE_CONTINUOUS")
	public Integer getValueDayLeaveContinuous() {
		return this.valueDayLeaveContinuous;
	}

	public void setValueDayLeaveContinuous(Integer valueDayLeaveContinuous) {
		this.valueDayLeaveContinuous = valueDayLeaveContinuous;
	}

	@Column(name = "LEAVE_COMPENSATION")
	public Integer getLeaveCompensation() {
		return this.leaveCompensation;
	}

	public void setLeaveCompensation(Integer leaveCompensation) {
		this.leaveCompensation = leaveCompensation;
	}

	@Column(name = "APPROVED_ORDER", length = 50)
	public String getApprovedOrder() {
		return this.approvedOrder;
	}

	public void setApprovedOrder(String approvedOrder) {
		this.approvedOrder = approvedOrder;
	}

}
