package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveRequestHistories generated by hbm2java
 */
@Entity
@Table(name = "LEAVE_REQUEST_HISTORIES", catalog = "eHRM_JavaResearching")
public class LeaveRequestHistories implements java.io.Serializable {

	private Integer leaveRequestHistoryId;
	private Employees employees;
	private LeaveRequests leaveRequests;
	private MasterDatas masterDatas;
	private Date modifiedDate;
	private Serializable comment;

	public LeaveRequestHistories() {
	}

	public LeaveRequestHistories(Employees employees, LeaveRequests leaveRequests, MasterDatas masterDatas,
			Date modifiedDate) {
		this.employees = employees;
		this.leaveRequests = leaveRequests;
		this.masterDatas = masterDatas;
		this.modifiedDate = modifiedDate;
	}

	public LeaveRequestHistories(Employees employees, LeaveRequests leaveRequests, MasterDatas masterDatas,
			Date modifiedDate, Serializable comment) {
		this.employees = employees;
		this.leaveRequests = leaveRequests;
		this.masterDatas = masterDatas;
		this.modifiedDate = modifiedDate;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LEAVE_REQUEST_HISTORY_ID", unique = true, nullable = false)
	public Integer getLeaveRequestHistoryId() {
		return this.leaveRequestHistoryId;
	}

	public void setLeaveRequestHistoryId(Integer leaveRequestHistoryId) {
		this.leaveRequestHistoryId = leaveRequestHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVER_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_REQUEST_ID", nullable = false)
	public LeaveRequests getLeaveRequests() {
		return this.leaveRequests;
	}

	public void setLeaveRequests(LeaveRequests leaveRequests) {
		this.leaveRequests = leaveRequests;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_REQUEST_STATUS_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 23)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "COMMENT")
	public Serializable getComment() {
		return this.comment;
	}

	public void setComment(Serializable comment) {
		this.comment = comment;
	}

}
