package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "LOCATIONS", catalog = "eHRM_JavaResearching")
public class Locations implements java.io.Serializable {

	private Integer locationId;
	private Locations locations;
	private Serializable name;
	private Integer areaType;
	private boolean active;
	private Set<TripcostLocations> tripcostLocationses = new HashSet<TripcostLocations>(0);
	private Set<TripLocations> tripLocationses = new HashSet<TripLocations>(0);
	private Set<Locations> locationses = new HashSet<Locations>(0);
	private Set<AprovalTripcosts> aprovalTripcostses = new HashSet<AprovalTripcosts>(0);

	public Locations() {
	}

	public Locations(boolean active) {
		this.active = active;
	}

	public Locations(Locations locations, Serializable name, Integer areaType, boolean active,
			Set<TripcostLocations> tripcostLocationses, Set<TripLocations> tripLocationses, Set<Locations> locationses,
			Set<AprovalTripcosts> aprovalTripcostses) {
		this.locations = locations;
		this.name = name;
		this.areaType = areaType;
		this.active = active;
		this.tripcostLocationses = tripcostLocationses;
		this.tripLocationses = tripLocationses;
		this.locationses = locationses;
		this.aprovalTripcostses = aprovalTripcostses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LOCATION_ID", unique = true, nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	@Column(name = "NAME")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "AREA_TYPE")
	public Integer getAreaType() {
		return this.areaType;
	}

	public void setAreaType(Integer areaType) {
		this.areaType = areaType;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<TripcostLocations> getTripcostLocationses() {
		return this.tripcostLocationses;
	}

	public void setTripcostLocationses(Set<TripcostLocations> tripcostLocationses) {
		this.tripcostLocationses = tripcostLocationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<TripLocations> getTripLocationses() {
		return this.tripLocationses;
	}

	public void setTripLocationses(Set<TripLocations> tripLocationses) {
		this.tripLocationses = tripLocationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<Locations> getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set<Locations> locationses) {
		this.locationses = locationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<AprovalTripcosts> getAprovalTripcostses() {
		return this.aprovalTripcostses;
	}

	public void setAprovalTripcostses(Set<AprovalTripcosts> aprovalTripcostses) {
		this.aprovalTripcostses = aprovalTripcostses;
	}

}
