package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MasterDataTypeLanguages generated by hbm2java
 */
@Entity
@Table(name = "MASTER_DATA_TYPE_LANGUAGES", catalog = "eHRM_JavaResearching")
public class MasterDataTypeLanguages implements java.io.Serializable {

	private Integer masterDataTypeLanguageId;
	private MasterDataTypes masterDataTypes;
	private String languageCode;
	private Serializable masterDataTypeName;
	private Serializable masterDataTypeDescription;

	public MasterDataTypeLanguages() {
	}

	public MasterDataTypeLanguages(MasterDataTypes masterDataTypes, String languageCode,
			Serializable masterDataTypeName) {
		this.masterDataTypes = masterDataTypes;
		this.languageCode = languageCode;
		this.masterDataTypeName = masterDataTypeName;
	}

	public MasterDataTypeLanguages(MasterDataTypes masterDataTypes, String languageCode,
			Serializable masterDataTypeName, Serializable masterDataTypeDescription) {
		this.masterDataTypes = masterDataTypes;
		this.languageCode = languageCode;
		this.masterDataTypeName = masterDataTypeName;
		this.masterDataTypeDescription = masterDataTypeDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MASTER_DATA_TYPE_LANGUAGE_ID", unique = true, nullable = false)
	public Integer getMasterDataTypeLanguageId() {
		return this.masterDataTypeLanguageId;
	}

	public void setMasterDataTypeLanguageId(Integer masterDataTypeLanguageId) {
		this.masterDataTypeLanguageId = masterDataTypeLanguageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASTER_DATA_TYPE_ID", nullable = false)
	public MasterDataTypes getMasterDataTypes() {
		return this.masterDataTypes;
	}

	public void setMasterDataTypes(MasterDataTypes masterDataTypes) {
		this.masterDataTypes = masterDataTypes;
	}

	@Column(name = "LANGUAGE_CODE", nullable = false, length = 5)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "MASTER_DATA_TYPE_NAME", nullable = false)
	public Serializable getMasterDataTypeName() {
		return this.masterDataTypeName;
	}

	public void setMasterDataTypeName(Serializable masterDataTypeName) {
		this.masterDataTypeName = masterDataTypeName;
	}

	@Column(name = "MASTER_DATA_TYPE_DESCRIPTION")
	public Serializable getMasterDataTypeDescription() {
		return this.masterDataTypeDescription;
	}

	public void setMasterDataTypeDescription(Serializable masterDataTypeDescription) {
		this.masterDataTypeDescription = masterDataTypeDescription;
	}

}
