package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MasterDataTypes generated by hbm2java
 */
@Entity
@Table(name = "MASTER_DATA_TYPES", catalog = "eHRM_JavaResearching")
public class MasterDataTypes implements java.io.Serializable {

	private Integer masterdataTypeId;
	private String masterdataTypeName;
	private String masterdataTypeDescription;
	private int orderIndex;
	private Set<MasterDatas> masterDatases = new HashSet<MasterDatas>(0);
	private Set<MasterDataTypeLanguages> masterDataTypeLanguageses = new HashSet<MasterDataTypeLanguages>(0);

	public MasterDataTypes() {
	}

	public MasterDataTypes(String masterdataTypeName, int orderIndex) {
		this.masterdataTypeName = masterdataTypeName;
		this.orderIndex = orderIndex;
	}

	public MasterDataTypes(String masterdataTypeName, String masterdataTypeDescription, int orderIndex,
			Set<MasterDatas> masterDatases, Set<MasterDataTypeLanguages> masterDataTypeLanguageses) {
		this.masterdataTypeName = masterdataTypeName;
		this.masterdataTypeDescription = masterdataTypeDescription;
		this.orderIndex = orderIndex;
		this.masterDatases = masterDatases;
		this.masterDataTypeLanguageses = masterDataTypeLanguageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MASTERDATA_TYPE_ID", unique = true, nullable = false)
	public Integer getMasterdataTypeId() {
		return this.masterdataTypeId;
	}

	public void setMasterdataTypeId(Integer masterdataTypeId) {
		this.masterdataTypeId = masterdataTypeId;
	}

	@Column(name = "MASTERDATA_TYPE_NAME", nullable = false)
	public String getMasterdataTypeName() {
		return this.masterdataTypeName;
	}

	public void setMasterdataTypeName(String masterdataTypeName) {
		this.masterdataTypeName = masterdataTypeName;
	}

	@Column(name = "MASTERDATA_TYPE_DESCRIPTION")
	public String getMasterdataTypeDescription() {
		return this.masterdataTypeDescription;
	}

	public void setMasterdataTypeDescription(String masterdataTypeDescription) {
		this.masterdataTypeDescription = masterdataTypeDescription;
	}

	@Column(name = "ORDER_INDEX", nullable = false)
	public int getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(int orderIndex) {
		this.orderIndex = orderIndex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterDataTypes")
	public Set<MasterDatas> getMasterDatases() {
		return this.masterDatases;
	}

	public void setMasterDatases(Set<MasterDatas> masterDatases) {
		this.masterDatases = masterDatases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterDataTypes")
	public Set<MasterDataTypeLanguages> getMasterDataTypeLanguageses() {
		return this.masterDataTypeLanguageses;
	}

	public void setMasterDataTypeLanguageses(Set<MasterDataTypeLanguages> masterDataTypeLanguageses) {
		this.masterDataTypeLanguageses = masterDataTypeLanguageses;
	}

}
