package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ModuleLanguages generated by hbm2java
 */
@Entity
@Table(name = "MODULE_LANGUAGES", catalog = "eHRM_JavaResearching")
public class ModuleLanguages implements java.io.Serializable {

	private Integer moduleLanguageId;
	private Modules modules;
	private String languageCode;
	private Serializable moduleName;
	private Serializable moduleDescription;

	public ModuleLanguages() {
	}

	public ModuleLanguages(Modules modules, String languageCode, Serializable moduleName) {
		this.modules = modules;
		this.languageCode = languageCode;
		this.moduleName = moduleName;
	}

	public ModuleLanguages(Modules modules, String languageCode, Serializable moduleName,
			Serializable moduleDescription) {
		this.modules = modules;
		this.languageCode = languageCode;
		this.moduleName = moduleName;
		this.moduleDescription = moduleDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MODULE_LANGUAGE_ID", unique = true, nullable = false)
	public Integer getModuleLanguageId() {
		return this.moduleLanguageId;
	}

	public void setModuleLanguageId(Integer moduleLanguageId) {
		this.moduleLanguageId = moduleLanguageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_ID", nullable = false)
	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	@Column(name = "LANGUAGE_CODE", nullable = false, length = 5)
	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	@Column(name = "MODULE_NAME", nullable = false)
	public Serializable getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(Serializable moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "MODULE_DESCRIPTION")
	public Serializable getModuleDescription() {
		return this.moduleDescription;
	}

	public void setModuleDescription(Serializable moduleDescription) {
		this.moduleDescription = moduleDescription;
	}

}
