package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModuleRights generated by hbm2java
 */
@Entity
@Table(name = "MODULE_RIGHTS", catalog = "eHRM_JavaResearching")
public class ModuleRights implements java.io.Serializable {

	private Integer moduleRightId;
	private MasterDatas masterDatas;
	private Modules modules;
	private Set<RoleModuleRights> roleModuleRightses = new HashSet<RoleModuleRights>(0);
	private Set<UserModuleRights> userModuleRightses = new HashSet<UserModuleRights>(0);

	public ModuleRights() {
	}

	public ModuleRights(MasterDatas masterDatas, Modules modules) {
		this.masterDatas = masterDatas;
		this.modules = modules;
	}

	public ModuleRights(MasterDatas masterDatas, Modules modules, Set<RoleModuleRights> roleModuleRightses,
			Set<UserModuleRights> userModuleRightses) {
		this.masterDatas = masterDatas;
		this.modules = modules;
		this.roleModuleRightses = roleModuleRightses;
		this.userModuleRightses = userModuleRightses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MODULE_RIGHT_ID", unique = true, nullable = false)
	public Integer getModuleRightId() {
		return this.moduleRightId;
	}

	public void setModuleRightId(Integer moduleRightId) {
		this.moduleRightId = moduleRightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RIGHT_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_ID", nullable = false)
	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moduleRights")
	public Set<RoleModuleRights> getRoleModuleRightses() {
		return this.roleModuleRightses;
	}

	public void setRoleModuleRightses(Set<RoleModuleRights> roleModuleRightses) {
		this.roleModuleRightses = roleModuleRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moduleRights")
	public Set<UserModuleRights> getUserModuleRightses() {
		return this.userModuleRightses;
	}

	public void setUserModuleRightses(Set<UserModuleRights> userModuleRightses) {
		this.userModuleRightses = userModuleRightses;
	}

}
