package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name = "MODULES", catalog = "eHRM_JavaResearching")
public class Modules implements java.io.Serializable {

	private Integer moduleId;
	private Modules modules;
	private Serializable moduleName;
	private Serializable moduleDescription;
	private boolean isModule;
	private Serializable rawUrl;
	private Boolean isDefault;
	private Integer orderIndex;
	private Integer position;
	private boolean active;
	private Set<Modules> moduleses = new HashSet<Modules>(0);
	private Set<ModuleRights> moduleRightses = new HashSet<ModuleRights>(0);
	private Set<ModuleLanguages> moduleLanguageses = new HashSet<ModuleLanguages>(0);
	private Set<UserModuleRoles> userModuleRoleses = new HashSet<UserModuleRoles>(0);

	public Modules() {
	}

	public Modules(Serializable moduleName, boolean isModule, boolean active) {
		this.moduleName = moduleName;
		this.isModule = isModule;
		this.active = active;
	}

	public Modules(Modules modules, Serializable moduleName, Serializable moduleDescription, boolean isModule,
			Serializable rawUrl, Boolean isDefault, Integer orderIndex, Integer position, boolean active,
			Set<Modules> moduleses, Set<ModuleRights> moduleRightses, Set<ModuleLanguages> moduleLanguageses,
			Set<UserModuleRoles> userModuleRoleses) {
		this.modules = modules;
		this.moduleName = moduleName;
		this.moduleDescription = moduleDescription;
		this.isModule = isModule;
		this.rawUrl = rawUrl;
		this.isDefault = isDefault;
		this.orderIndex = orderIndex;
		this.position = position;
		this.active = active;
		this.moduleses = moduleses;
		this.moduleRightses = moduleRightses;
		this.moduleLanguageses = moduleLanguageses;
		this.userModuleRoleses = userModuleRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MODULE_ID", unique = true, nullable = false)
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_PARENT_ID")
	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	@Column(name = "MODULE_NAME", nullable = false)
	public Serializable getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(Serializable moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "MODULE_DESCRIPTION")
	public Serializable getModuleDescription() {
		return this.moduleDescription;
	}

	public void setModuleDescription(Serializable moduleDescription) {
		this.moduleDescription = moduleDescription;
	}

	@Column(name = "IS_MODULE", nullable = false)
	public boolean isIsModule() {
		return this.isModule;
	}

	public void setIsModule(boolean isModule) {
		this.isModule = isModule;
	}

	@Column(name = "RAW_URL")
	public Serializable getRawUrl() {
		return this.rawUrl;
	}

	public void setRawUrl(Serializable rawUrl) {
		this.rawUrl = rawUrl;
	}

	@Column(name = "IS_DEFAULT")
	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "ORDER_INDEX")
	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	@Column(name = "POSITION")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
	public Set<Modules> getModuleses() {
		return this.moduleses;
	}

	public void setModuleses(Set<Modules> moduleses) {
		this.moduleses = moduleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
	public Set<ModuleRights> getModuleRightses() {
		return this.moduleRightses;
	}

	public void setModuleRightses(Set<ModuleRights> moduleRightses) {
		this.moduleRightses = moduleRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
	public Set<ModuleLanguages> getModuleLanguageses() {
		return this.moduleLanguageses;
	}

	public void setModuleLanguageses(Set<ModuleLanguages> moduleLanguageses) {
		this.moduleLanguageses = moduleLanguageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modules")
	public Set<UserModuleRoles> getUserModuleRoleses() {
		return this.userModuleRoleses;
	}

	public void setUserModuleRoleses(Set<UserModuleRoles> userModuleRoleses) {
		this.userModuleRoleses = userModuleRoleses;
	}

}
