package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtTravel generated by hbm2java
 */
@Entity
@Table(name = "OT_TRAVEL", catalog = "eHRM_JavaResearching")
public class OtTravel implements java.io.Serializable {

	private Integer otTravelId;
	private TimeSheets timeSheets;
	private Date startOtTime;
	private Date endOtTime;
	private BigDecimal otHour;
	private Serializable description;
	private Date dateCreate;

	public OtTravel() {
	}

	public OtTravel(TimeSheets timeSheets) {
		this.timeSheets = timeSheets;
	}

	public OtTravel(TimeSheets timeSheets, Date startOtTime, Date endOtTime, BigDecimal otHour,
			Serializable description, Date dateCreate) {
		this.timeSheets = timeSheets;
		this.startOtTime = startOtTime;
		this.endOtTime = endOtTime;
		this.otHour = otHour;
		this.description = description;
		this.dateCreate = dateCreate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OT_TRAVEL_ID", unique = true, nullable = false)
	public Integer getOtTravelId() {
		return this.otTravelId;
	}

	public void setOtTravelId(Integer otTravelId) {
		this.otTravelId = otTravelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIME_SHEET_ID", nullable = false)
	public TimeSheets getTimeSheets() {
		return this.timeSheets;
	}

	public void setTimeSheets(TimeSheets timeSheets) {
		this.timeSheets = timeSheets;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_OT_TIME", length = 23)
	public Date getStartOtTime() {
		return this.startOtTime;
	}

	public void setStartOtTime(Date startOtTime) {
		this.startOtTime = startOtTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_OT_TIME", length = 23)
	public Date getEndOtTime() {
		return this.endOtTime;
	}

	public void setEndOtTime(Date endOtTime) {
		this.endOtTime = endOtTime;
	}

	@Column(name = "OT_HOUR", precision = 18)
	public BigDecimal getOtHour() {
		return this.otHour;
	}

	public void setOtHour(BigDecimal otHour) {
		this.otHour = otHour;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATE", length = 23)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

}
