package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OutBreakOvertime generated by hbm2java
 */
@Entity
@Table(name = "OUT_BREAK_OVERTIME", catalog = "eHRM_JavaResearching")
public class OutBreakOvertime implements java.io.Serializable {

	private Integer outBreakOvertimeId;
	private OutBreakRequests outBreakRequests;
	private TaOvertimeSchedules taOvertimeSchedules;

	public OutBreakOvertime() {
	}

	public OutBreakOvertime(OutBreakRequests outBreakRequests, TaOvertimeSchedules taOvertimeSchedules) {
		this.outBreakRequests = outBreakRequests;
		this.taOvertimeSchedules = taOvertimeSchedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OUT_BREAK_OVERTIME_ID", unique = true, nullable = false)
	public Integer getOutBreakOvertimeId() {
		return this.outBreakOvertimeId;
	}

	public void setOutBreakOvertimeId(Integer outBreakOvertimeId) {
		this.outBreakOvertimeId = outBreakOvertimeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUT_BREAK_REQUEST_ID")
	public OutBreakRequests getOutBreakRequests() {
		return this.outBreakRequests;
	}

	public void setOutBreakRequests(OutBreakRequests outBreakRequests) {
		this.outBreakRequests = outBreakRequests;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OVERTIME_SCHEDULE_ID")
	public TaOvertimeSchedules getTaOvertimeSchedules() {
		return this.taOvertimeSchedules;
	}

	public void setTaOvertimeSchedules(TaOvertimeSchedules taOvertimeSchedules) {
		this.taOvertimeSchedules = taOvertimeSchedules;
	}

}
