package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OutBreakRequestHistories generated by hbm2java
 */
@Entity
@Table(name = "OUT_BREAK_REQUEST_HISTORIES", catalog = "eHRM_JavaResearching")
public class OutBreakRequestHistories implements java.io.Serializable {

	private Integer outBreakRequestHistoryId;
	private Employees employees;
	private MasterDatas masterDatas;
	private OutBreakRequests outBreakRequests;
	private Date modifiedDate;
	private Serializable comment;

	public OutBreakRequestHistories() {
	}

	public OutBreakRequestHistories(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public OutBreakRequestHistories(Employees employees, MasterDatas masterDatas, OutBreakRequests outBreakRequests,
			Date modifiedDate, Serializable comment) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.outBreakRequests = outBreakRequests;
		this.modifiedDate = modifiedDate;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OUT_BREAK_REQUEST_HISTORY_ID", unique = true, nullable = false)
	public Integer getOutBreakRequestHistoryId() {
		return this.outBreakRequestHistoryId;
	}

	public void setOutBreakRequestHistoryId(Integer outBreakRequestHistoryId) {
		this.outBreakRequestHistoryId = outBreakRequestHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVER_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUT_BREAK_REQUEST_STATUS_ID")
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUT_BREAK_REQUEST_ID")
	public OutBreakRequests getOutBreakRequests() {
		return this.outBreakRequests;
	}

	public void setOutBreakRequests(OutBreakRequests outBreakRequests) {
		this.outBreakRequests = outBreakRequests;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "COMMENT")
	public Serializable getComment() {
		return this.comment;
	}

	public void setComment(Serializable comment) {
		this.comment = comment;
	}

}
