package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdfFile generated by hbm2java
 */
@Entity
@Table(name = "PDF_FILE", catalog = "eHRM_JavaResearching")
public class PdfFile implements java.io.Serializable {

	private Integer documentId;
	private Employees employees;
	private Serializable documentName;
	private Serializable path;
	private Serializable decription;
	private Date uploadDate;
	private Serializable identifyCode;
	private Serializable nameEmployee;

	public PdfFile() {
	}

	public PdfFile(Employees employees, Serializable documentName, Serializable path, Serializable decription,
			Date uploadDate, Serializable identifyCode, Serializable nameEmployee) {
		this.employees = employees;
		this.documentName = documentName;
		this.path = path;
		this.decription = decription;
		this.uploadDate = uploadDate;
		this.identifyCode = identifyCode;
		this.nameEmployee = nameEmployee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DOCUMENT_ID", unique = true, nullable = false)
	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "DOCUMENT_NAME")
	public Serializable getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(Serializable documentName) {
		this.documentName = documentName;
	}

	@Column(name = "PATH")
	public Serializable getPath() {
		return this.path;
	}

	public void setPath(Serializable path) {
		this.path = path;
	}

	@Column(name = "DECRIPTION")
	public Serializable getDecription() {
		return this.decription;
	}

	public void setDecription(Serializable decription) {
		this.decription = decription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPLOAD_DATE", length = 10)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "IDENTIFY_CODE")
	public Serializable getIdentifyCode() {
		return this.identifyCode;
	}

	public void setIdentifyCode(Serializable identifyCode) {
		this.identifyCode = identifyCode;
	}

	@Column(name = "NAME_EMPLOYEE")
	public Serializable getNameEmployee() {
		return this.nameEmployee;
	}

	public void setNameEmployee(Serializable nameEmployee) {
		this.nameEmployee = nameEmployee;
	}

}
