package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerformanceAssessments generated by hbm2java
 */
@Entity
@Table(name = "PERFORMANCE_ASSESSMENTS", catalog = "eHRM_JavaResearching")
public class PerformanceAssessments implements java.io.Serializable {

	private Integer performanceAssessmentId;
	private Employees employees;
	private ReviewTimeConfig reviewTimeConfig;
	private Integer rank;
	private Boolean eligible;
	private Serializable staffComments;
	private Serializable managementComments;
	private Serializable dhComments;
	private Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses = new HashSet<PerformanceAssessmentHistories>(
			0);

	public PerformanceAssessments() {
	}

	public PerformanceAssessments(Employees employees, ReviewTimeConfig reviewTimeConfig) {
		this.employees = employees;
		this.reviewTimeConfig = reviewTimeConfig;
	}

	public PerformanceAssessments(Employees employees, ReviewTimeConfig reviewTimeConfig, Integer rank,
			Boolean eligible, Serializable staffComments, Serializable managementComments, Serializable dhComments,
			Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses) {
		this.employees = employees;
		this.reviewTimeConfig = reviewTimeConfig;
		this.rank = rank;
		this.eligible = eligible;
		this.staffComments = staffComments;
		this.managementComments = managementComments;
		this.dhComments = dhComments;
		this.performanceAssessmentHistorieses = performanceAssessmentHistorieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERFORMANCE_ASSESSMENT_ID", unique = true, nullable = false)
	public Integer getPerformanceAssessmentId() {
		return this.performanceAssessmentId;
	}

	public void setPerformanceAssessmentId(Integer performanceAssessmentId) {
		this.performanceAssessmentId = performanceAssessmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REVIEW_TIME_ID", nullable = false)
	public ReviewTimeConfig getReviewTimeConfig() {
		return this.reviewTimeConfig;
	}

	public void setReviewTimeConfig(ReviewTimeConfig reviewTimeConfig) {
		this.reviewTimeConfig = reviewTimeConfig;
	}

	@Column(name = "RANK")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "ELIGIBLE")
	public Boolean getEligible() {
		return this.eligible;
	}

	public void setEligible(Boolean eligible) {
		this.eligible = eligible;
	}

	@Column(name = "STAFF_COMMENTS")
	public Serializable getStaffComments() {
		return this.staffComments;
	}

	public void setStaffComments(Serializable staffComments) {
		this.staffComments = staffComments;
	}

	@Column(name = "MANAGEMENT_COMMENTS")
	public Serializable getManagementComments() {
		return this.managementComments;
	}

	public void setManagementComments(Serializable managementComments) {
		this.managementComments = managementComments;
	}

	@Column(name = "DH_COMMENTS")
	public Serializable getDhComments() {
		return this.dhComments;
	}

	public void setDhComments(Serializable dhComments) {
		this.dhComments = dhComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "performanceAssessments")
	public Set<PerformanceAssessmentHistories> getPerformanceAssessmentHistorieses() {
		return this.performanceAssessmentHistorieses;
	}

	public void setPerformanceAssessmentHistorieses(
			Set<PerformanceAssessmentHistories> performanceAssessmentHistorieses) {
		this.performanceAssessmentHistorieses = performanceAssessmentHistorieses;
	}

}
