package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Periodicities generated by hbm2java
 */
@Entity
@Table(name = "PERIODICITIES", catalog = "eHRM_JavaResearching")
public class Periodicities implements java.io.Serializable {

	private Integer periodicityId;
	private Serializable periodicityName;
	private int periodicityValue;
	private Integer orderIndex;
	private int periodicityStarting;
	private boolean isMonthlyPay;
	private Set<Incomes> incomeses = new HashSet<Incomes>(0);

	public Periodicities() {
	}

	public Periodicities(Serializable periodicityName, int periodicityValue, int periodicityStarting,
			boolean isMonthlyPay) {
		this.periodicityName = periodicityName;
		this.periodicityValue = periodicityValue;
		this.periodicityStarting = periodicityStarting;
		this.isMonthlyPay = isMonthlyPay;
	}

	public Periodicities(Serializable periodicityName, int periodicityValue, Integer orderIndex,
			int periodicityStarting, boolean isMonthlyPay, Set<Incomes> incomeses) {
		this.periodicityName = periodicityName;
		this.periodicityValue = periodicityValue;
		this.orderIndex = orderIndex;
		this.periodicityStarting = periodicityStarting;
		this.isMonthlyPay = isMonthlyPay;
		this.incomeses = incomeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERIODICITY_ID", unique = true, nullable = false)
	public Integer getPeriodicityId() {
		return this.periodicityId;
	}

	public void setPeriodicityId(Integer periodicityId) {
		this.periodicityId = periodicityId;
	}

	@Column(name = "PERIODICITY_NAME", nullable = false)
	public Serializable getPeriodicityName() {
		return this.periodicityName;
	}

	public void setPeriodicityName(Serializable periodicityName) {
		this.periodicityName = periodicityName;
	}

	@Column(name = "PERIODICITY_VALUE", nullable = false)
	public int getPeriodicityValue() {
		return this.periodicityValue;
	}

	public void setPeriodicityValue(int periodicityValue) {
		this.periodicityValue = periodicityValue;
	}

	@Column(name = "ORDER_INDEX")
	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	@Column(name = "PERIODICITY_STARTING", nullable = false)
	public int getPeriodicityStarting() {
		return this.periodicityStarting;
	}

	public void setPeriodicityStarting(int periodicityStarting) {
		this.periodicityStarting = periodicityStarting;
	}

	@Column(name = "IS_MONTHLY_PAY", nullable = false)
	public boolean isIsMonthlyPay() {
		return this.isMonthlyPay;
	}

	public void setIsMonthlyPay(boolean isMonthlyPay) {
		this.isMonthlyPay = isMonthlyPay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicities")
	public Set<Incomes> getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set<Incomes> incomeses) {
		this.incomeses = incomeses;
	}

}
