package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonalTargetHistories generated by hbm2java
 */
@Entity
@Table(name = "PERSONAL_TARGET_HISTORIES", catalog = "eHRM_JavaResearching")
public class PersonalTargetHistories implements java.io.Serializable {

	private Integer personalTargetHistoryId;
	private MasterDatas masterDatas;
	private PersonalTargets personalTargets;
	private Serializable target;
	private Serializable results;
	private Serializable evaluation;
	private Integer staffScore;
	private Integer supervisorScore;
	private Integer dhScore;

	public PersonalTargetHistories() {
	}

	public PersonalTargetHistories(MasterDatas masterDatas, PersonalTargets personalTargets) {
		this.masterDatas = masterDatas;
		this.personalTargets = personalTargets;
	}

	public PersonalTargetHistories(MasterDatas masterDatas, PersonalTargets personalTargets, Serializable target,
			Serializable results, Serializable evaluation, Integer staffScore, Integer supervisorScore,
			Integer dhScore) {
		this.masterDatas = masterDatas;
		this.personalTargets = personalTargets;
		this.target = target;
		this.results = results;
		this.evaluation = evaluation;
		this.staffScore = staffScore;
		this.supervisorScore = supervisorScore;
		this.dhScore = dhScore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERSONAL_TARGET_HISTORY_ID", unique = true, nullable = false)
	public Integer getPersonalTargetHistoryId() {
		return this.personalTargetHistoryId;
	}

	public void setPersonalTargetHistoryId(Integer personalTargetHistoryId) {
		this.personalTargetHistoryId = personalTargetHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TARGET_GROUP_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONAL_TARGET_ID", nullable = false)
	public PersonalTargets getPersonalTargets() {
		return this.personalTargets;
	}

	public void setPersonalTargets(PersonalTargets personalTargets) {
		this.personalTargets = personalTargets;
	}

	@Column(name = "TARGET")
	public Serializable getTarget() {
		return this.target;
	}

	public void setTarget(Serializable target) {
		this.target = target;
	}

	@Column(name = "RESULTS")
	public Serializable getResults() {
		return this.results;
	}

	public void setResults(Serializable results) {
		this.results = results;
	}

	@Column(name = "EVALUATION")
	public Serializable getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Serializable evaluation) {
		this.evaluation = evaluation;
	}

	@Column(name = "STAFF_SCORE")
	public Integer getStaffScore() {
		return this.staffScore;
	}

	public void setStaffScore(Integer staffScore) {
		this.staffScore = staffScore;
	}

	@Column(name = "SUPERVISOR_SCORE")
	public Integer getSupervisorScore() {
		return this.supervisorScore;
	}

	public void setSupervisorScore(Integer supervisorScore) {
		this.supervisorScore = supervisorScore;
	}

	@Column(name = "DH_SCORE")
	public Integer getDhScore() {
		return this.dhScore;
	}

	public void setDhScore(Integer dhScore) {
		this.dhScore = dhScore;
	}

}
