package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalTargets generated by hbm2java
 */
@Entity
@Table(name = "PERSONAL_TARGETS", catalog = "eHRM_JavaResearching")
public class PersonalTargets implements java.io.Serializable {

	private Integer personalTargetId;
	private Employees employees;
	private ReviewTimeConfig reviewTimeConfig;
	private Date targetDate;
	private Date resultDate;
	private Date evaluationDate;
	private Serializable staffComments;
	private Serializable supervisorComments;
	private String dhComments;
	private Set<PersonalTargetHistories> personalTargetHistorieses = new HashSet<PersonalTargetHistories>(0);

	public PersonalTargets() {
	}

	public PersonalTargets(Employees employees, ReviewTimeConfig reviewTimeConfig) {
		this.employees = employees;
		this.reviewTimeConfig = reviewTimeConfig;
	}

	public PersonalTargets(Employees employees, ReviewTimeConfig reviewTimeConfig, Date targetDate, Date resultDate,
			Date evaluationDate, Serializable staffComments, Serializable supervisorComments, String dhComments,
			Set<PersonalTargetHistories> personalTargetHistorieses) {
		this.employees = employees;
		this.reviewTimeConfig = reviewTimeConfig;
		this.targetDate = targetDate;
		this.resultDate = resultDate;
		this.evaluationDate = evaluationDate;
		this.staffComments = staffComments;
		this.supervisorComments = supervisorComments;
		this.dhComments = dhComments;
		this.personalTargetHistorieses = personalTargetHistorieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PERSONAL_TARGET_ID", unique = true, nullable = false)
	public Integer getPersonalTargetId() {
		return this.personalTargetId;
	}

	public void setPersonalTargetId(Integer personalTargetId) {
		this.personalTargetId = personalTargetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REVIEW_TIME_ID", nullable = false)
	public ReviewTimeConfig getReviewTimeConfig() {
		return this.reviewTimeConfig;
	}

	public void setReviewTimeConfig(ReviewTimeConfig reviewTimeConfig) {
		this.reviewTimeConfig = reviewTimeConfig;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TARGET_DATE", length = 10)
	public Date getTargetDate() {
		return this.targetDate;
	}

	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RESULT_DATE", length = 10)
	public Date getResultDate() {
		return this.resultDate;
	}

	public void setResultDate(Date resultDate) {
		this.resultDate = resultDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EVALUATION_DATE", length = 10)
	public Date getEvaluationDate() {
		return this.evaluationDate;
	}

	public void setEvaluationDate(Date evaluationDate) {
		this.evaluationDate = evaluationDate;
	}

	@Column(name = "STAFF_COMMENTS")
	public Serializable getStaffComments() {
		return this.staffComments;
	}

	public void setStaffComments(Serializable staffComments) {
		this.staffComments = staffComments;
	}

	@Column(name = "SUPERVISOR_COMMENTS")
	public Serializable getSupervisorComments() {
		return this.supervisorComments;
	}

	public void setSupervisorComments(Serializable supervisorComments) {
		this.supervisorComments = supervisorComments;
	}

	@Column(name = "DH_COMMENTS", length = 1500)
	public String getDhComments() {
		return this.dhComments;
	}

	public void setDhComments(String dhComments) {
		this.dhComments = dhComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalTargets")
	public Set<PersonalTargetHistories> getPersonalTargetHistorieses() {
		return this.personalTargetHistorieses;
	}

	public void setPersonalTargetHistorieses(Set<PersonalTargetHistories> personalTargetHistorieses) {
		this.personalTargetHistorieses = personalTargetHistorieses;
	}

}
