package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProjectMms generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_MMS", catalog = "eHRM_JavaResearching")
public class ProjectMms implements java.io.Serializable {

	private Integer projectMmsId;
	private Serializable projectCode;
	private Serializable identifyCode;
	private BigDecimal hours;
	private int date;
	private Integer timeIn;
	private Integer timeOut;
	private Serializable description;

	public ProjectMms() {
	}

	public ProjectMms(Serializable projectCode, Serializable identifyCode, BigDecimal hours, int date) {
		this.projectCode = projectCode;
		this.identifyCode = identifyCode;
		this.hours = hours;
		this.date = date;
	}

	public ProjectMms(Serializable projectCode, Serializable identifyCode, BigDecimal hours, int date, Integer timeIn,
			Integer timeOut, Serializable description) {
		this.projectCode = projectCode;
		this.identifyCode = identifyCode;
		this.hours = hours;
		this.date = date;
		this.timeIn = timeIn;
		this.timeOut = timeOut;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROJECT_MMS_ID", unique = true, nullable = false)
	public Integer getProjectMmsId() {
		return this.projectMmsId;
	}

	public void setProjectMmsId(Integer projectMmsId) {
		this.projectMmsId = projectMmsId;
	}

	@Column(name = "PROJECT_CODE", nullable = false)
	public Serializable getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(Serializable projectCode) {
		this.projectCode = projectCode;
	}

	@Column(name = "IDENTIFY_CODE", nullable = false)
	public Serializable getIdentifyCode() {
		return this.identifyCode;
	}

	public void setIdentifyCode(Serializable identifyCode) {
		this.identifyCode = identifyCode;
	}

	@Column(name = "HOURS", nullable = false, precision = 8)
	public BigDecimal getHours() {
		return this.hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	@Column(name = "DATE", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	@Column(name = "TIME_IN")
	public Integer getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Integer timeIn) {
		this.timeIn = timeIn;
	}

	@Column(name = "TIME_OUT")
	public Integer getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(Integer timeOut) {
		this.timeOut = timeOut;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

}
