package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReviewTimeConfig generated by hbm2java
 */
@Entity
@Table(name = "REVIEW_TIME_CONFIG", catalog = "eHRM_JavaResearching")
public class ReviewTimeConfig implements java.io.Serializable {

	private Integer reviewTimeId;
	private FinancialYears financialYears;
	private Serializable reviewTimeName;
	private Date periodStartDate;
	private Date periodEndDate;
	private Date startDate;
	private Date endDate;
	private Set<PerformanceAssessments> performanceAssessmentses = new HashSet<PerformanceAssessments>(0);
	private Set<PersonalTargets> personalTargetses = new HashSet<PersonalTargets>(0);

	public ReviewTimeConfig() {
	}

	public ReviewTimeConfig(FinancialYears financialYears, Serializable reviewTimeName, Date periodStartDate,
			Date periodEndDate, Date startDate, Date endDate) {
		this.financialYears = financialYears;
		this.reviewTimeName = reviewTimeName;
		this.periodStartDate = periodStartDate;
		this.periodEndDate = periodEndDate;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public ReviewTimeConfig(FinancialYears financialYears, Serializable reviewTimeName, Date periodStartDate,
			Date periodEndDate, Date startDate, Date endDate, Set<PerformanceAssessments> performanceAssessmentses,
			Set<PersonalTargets> personalTargetses) {
		this.financialYears = financialYears;
		this.reviewTimeName = reviewTimeName;
		this.periodStartDate = periodStartDate;
		this.periodEndDate = periodEndDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.performanceAssessmentses = performanceAssessmentses;
		this.personalTargetses = personalTargetses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REVIEW_TIME_ID", unique = true, nullable = false)
	public Integer getReviewTimeId() {
		return this.reviewTimeId;
	}

	public void setReviewTimeId(Integer reviewTimeId) {
		this.reviewTimeId = reviewTimeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINANCIAL_YEAR_ID", nullable = false)
	public FinancialYears getFinancialYears() {
		return this.financialYears;
	}

	public void setFinancialYears(FinancialYears financialYears) {
		this.financialYears = financialYears;
	}

	@Column(name = "REVIEW_TIME_NAME", nullable = false)
	public Serializable getReviewTimeName() {
		return this.reviewTimeName;
	}

	public void setReviewTimeName(Serializable reviewTimeName) {
		this.reviewTimeName = reviewTimeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIOD_START_DATE", nullable = false, length = 10)
	public Date getPeriodStartDate() {
		return this.periodStartDate;
	}

	public void setPeriodStartDate(Date periodStartDate) {
		this.periodStartDate = periodStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIOD_END_DATE", nullable = false, length = 10)
	public Date getPeriodEndDate() {
		return this.periodEndDate;
	}

	public void setPeriodEndDate(Date periodEndDate) {
		this.periodEndDate = periodEndDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reviewTimeConfig")
	public Set<PerformanceAssessments> getPerformanceAssessmentses() {
		return this.performanceAssessmentses;
	}

	public void setPerformanceAssessmentses(Set<PerformanceAssessments> performanceAssessmentses) {
		this.performanceAssessmentses = performanceAssessmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reviewTimeConfig")
	public Set<PersonalTargets> getPersonalTargetses() {
		return this.personalTargetses;
	}

	public void setPersonalTargetses(Set<PersonalTargets> personalTargetses) {
		this.personalTargetses = personalTargetses;
	}

}
