package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleModuleRights generated by hbm2java
 */
@Entity
@Table(name = "ROLE_MODULE_RIGHTS", catalog = "eHRM_JavaResearching")
public class RoleModuleRights implements java.io.Serializable {

	private Integer roleModuleRightId;
	private MasterDatas masterDatas;
	private ModuleRights moduleRights;

	public RoleModuleRights() {
	}

	public RoleModuleRights(MasterDatas masterDatas, ModuleRights moduleRights) {
		this.masterDatas = masterDatas;
		this.moduleRights = moduleRights;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROLE_MODULE_RIGHT_ID", unique = true, nullable = false)
	public Integer getRoleModuleRightId() {
		return this.roleModuleRightId;
	}

	public void setRoleModuleRightId(Integer roleModuleRightId) {
		this.roleModuleRightId = roleModuleRightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_RIGHT_ID", nullable = false)
	public ModuleRights getModuleRights() {
		return this.moduleRights;
	}

	public void setModuleRights(ModuleRights moduleRights) {
		this.moduleRights = moduleRights;
	}

}
