package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleApprovalLevel generated by hbm2java
 */
@Entity
@Table(name = "ROLE_APPROVAL_LEVEL", catalog = "eHRM_JavaResearching")
public class RoleApprovalLevel implements java.io.Serializable {

	private Integer roleApprovalLevelId;
	private MasterDatas masterDatas;
	private Integer orderApproval;
	private Set<LeaveTypes> leaveTypeses = new HashSet<LeaveTypes>(0);
	private Set<TripTypes> tripTypeses = new HashSet<TripTypes>(0);
	private Set<OutBreakTypes> outBreakTypeses = new HashSet<OutBreakTypes>(0);
	private Set<OvertimeTypes> overtimeTypeses = new HashSet<OvertimeTypes>(0);

	public RoleApprovalLevel() {
	}

	public RoleApprovalLevel(MasterDatas masterDatas, Integer orderApproval, Set<LeaveTypes> leaveTypeses,
			Set<TripTypes> tripTypeses, Set<OutBreakTypes> outBreakTypeses, Set<OvertimeTypes> overtimeTypeses) {
		this.masterDatas = masterDatas;
		this.orderApproval = orderApproval;
		this.leaveTypeses = leaveTypeses;
		this.tripTypeses = tripTypeses;
		this.outBreakTypeses = outBreakTypeses;
		this.overtimeTypeses = overtimeTypeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROLE_APPROVAL_LEVEL_ID", unique = true, nullable = false)
	public Integer getRoleApprovalLevelId() {
		return this.roleApprovalLevelId;
	}

	public void setRoleApprovalLevelId(Integer roleApprovalLevelId) {
		this.roleApprovalLevelId = roleApprovalLevelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASTER_DATA_ID")
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@Column(name = "ORDER_APPROVAL")
	public Integer getOrderApproval() {
		return this.orderApproval;
	}

	public void setOrderApproval(Integer orderApproval) {
		this.orderApproval = orderApproval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleApprovalLevel")
	public Set<LeaveTypes> getLeaveTypeses() {
		return this.leaveTypeses;
	}

	public void setLeaveTypeses(Set<LeaveTypes> leaveTypeses) {
		this.leaveTypeses = leaveTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleApprovalLevel")
	public Set<TripTypes> getTripTypeses() {
		return this.tripTypeses;
	}

	public void setTripTypeses(Set<TripTypes> tripTypeses) {
		this.tripTypeses = tripTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleApprovalLevel")
	public Set<OutBreakTypes> getOutBreakTypeses() {
		return this.outBreakTypeses;
	}

	public void setOutBreakTypeses(Set<OutBreakTypes> outBreakTypeses) {
		this.outBreakTypeses = outBreakTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleApprovalLevel")
	public Set<OvertimeTypes> getOvertimeTypeses() {
		return this.overtimeTypeses;
	}

	public void setOvertimeTypeses(Set<OvertimeTypes> overtimeTypeses) {
		this.overtimeTypeses = overtimeTypeses;
	}

}
