package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaEmployeeLateInEarlyOut generated by hbm2java
 */
@Entity
@Table(name = "TA_EMPLOYEE_LATE_IN_EARLY_OUT", catalog = "eHRM_JavaResearching")
public class TaEmployeeLateInEarlyOut implements java.io.Serializable {

	private Integer employeeLateInEarlyOutId;
	private MasterDatas masterDatas;
	private TaEmployeeTimesheets taEmployeeTimesheets;
	private Double approvedLateInHours;
	private Boolean approvedLateIn;
	private Double approvedEarlyOutHours;
	private Boolean approvedEarlyOut;
	private Serializable remark;
	private Double actualLateInHours;
	private Double actualEarlyOutHours;
	private Double scheduledLateInMinute;
	private Double scheduledEarlyOutMinute;
	private Double scheduledGoOutMinute;

	public TaEmployeeLateInEarlyOut() {
	}

	public TaEmployeeLateInEarlyOut(MasterDatas masterDatas, TaEmployeeTimesheets taEmployeeTimesheets) {
		this.masterDatas = masterDatas;
		this.taEmployeeTimesheets = taEmployeeTimesheets;
	}

	public TaEmployeeLateInEarlyOut(MasterDatas masterDatas, TaEmployeeTimesheets taEmployeeTimesheets,
			Double approvedLateInHours, Boolean approvedLateIn, Double approvedEarlyOutHours, Boolean approvedEarlyOut,
			Serializable remark, Double actualLateInHours, Double actualEarlyOutHours, Double scheduledLateInMinute,
			Double scheduledEarlyOutMinute, Double scheduledGoOutMinute) {
		this.masterDatas = masterDatas;
		this.taEmployeeTimesheets = taEmployeeTimesheets;
		this.approvedLateInHours = approvedLateInHours;
		this.approvedLateIn = approvedLateIn;
		this.approvedEarlyOutHours = approvedEarlyOutHours;
		this.approvedEarlyOut = approvedEarlyOut;
		this.remark = remark;
		this.actualLateInHours = actualLateInHours;
		this.actualEarlyOutHours = actualEarlyOutHours;
		this.scheduledLateInMinute = scheduledLateInMinute;
		this.scheduledEarlyOutMinute = scheduledEarlyOutMinute;
		this.scheduledGoOutMinute = scheduledGoOutMinute;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_LATE_IN_EARLY_OUT_ID", unique = true, nullable = false)
	public Integer getEmployeeLateInEarlyOutId() {
		return this.employeeLateInEarlyOutId;
	}

	public void setEmployeeLateInEarlyOutId(Integer employeeLateInEarlyOutId) {
		this.employeeLateInEarlyOutId = employeeLateInEarlyOutId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_LATE_IN_EARLY_OUT_STATUS_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_TIMESHEET_ID", nullable = false)
	public TaEmployeeTimesheets getTaEmployeeTimesheets() {
		return this.taEmployeeTimesheets;
	}

	public void setTaEmployeeTimesheets(TaEmployeeTimesheets taEmployeeTimesheets) {
		this.taEmployeeTimesheets = taEmployeeTimesheets;
	}

	@Column(name = "APPROVED_LATE_IN_HOURS", precision = 53, scale = 0)
	public Double getApprovedLateInHours() {
		return this.approvedLateInHours;
	}

	public void setApprovedLateInHours(Double approvedLateInHours) {
		this.approvedLateInHours = approvedLateInHours;
	}

	@Column(name = "APPROVED_LATE_IN")
	public Boolean getApprovedLateIn() {
		return this.approvedLateIn;
	}

	public void setApprovedLateIn(Boolean approvedLateIn) {
		this.approvedLateIn = approvedLateIn;
	}

	@Column(name = "APPROVED_EARLY_OUT_HOURS", precision = 53, scale = 0)
	public Double getApprovedEarlyOutHours() {
		return this.approvedEarlyOutHours;
	}

	public void setApprovedEarlyOutHours(Double approvedEarlyOutHours) {
		this.approvedEarlyOutHours = approvedEarlyOutHours;
	}

	@Column(name = "APPROVED_EARLY_OUT")
	public Boolean getApprovedEarlyOut() {
		return this.approvedEarlyOut;
	}

	public void setApprovedEarlyOut(Boolean approvedEarlyOut) {
		this.approvedEarlyOut = approvedEarlyOut;
	}

	@Column(name = "REMARK")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

	@Column(name = "ACTUAL_LATE_IN_HOURS", precision = 53, scale = 0)
	public Double getActualLateInHours() {
		return this.actualLateInHours;
	}

	public void setActualLateInHours(Double actualLateInHours) {
		this.actualLateInHours = actualLateInHours;
	}

	@Column(name = "ACTUAL_EARLY_OUT_HOURS", precision = 53, scale = 0)
	public Double getActualEarlyOutHours() {
		return this.actualEarlyOutHours;
	}

	public void setActualEarlyOutHours(Double actualEarlyOutHours) {
		this.actualEarlyOutHours = actualEarlyOutHours;
	}

	@Column(name = "SCHEDULED_LATE_IN_MINUTE", precision = 53, scale = 0)
	public Double getScheduledLateInMinute() {
		return this.scheduledLateInMinute;
	}

	public void setScheduledLateInMinute(Double scheduledLateInMinute) {
		this.scheduledLateInMinute = scheduledLateInMinute;
	}

	@Column(name = "SCHEDULED_EARLY_OUT_MINUTE", precision = 53, scale = 0)
	public Double getScheduledEarlyOutMinute() {
		return this.scheduledEarlyOutMinute;
	}

	public void setScheduledEarlyOutMinute(Double scheduledEarlyOutMinute) {
		this.scheduledEarlyOutMinute = scheduledEarlyOutMinute;
	}

	@Column(name = "SCHEDULED_GO_OUT_MINUTE", precision = 53, scale = 0)
	public Double getScheduledGoOutMinute() {
		return this.scheduledGoOutMinute;
	}

	public void setScheduledGoOutMinute(Double scheduledGoOutMinute) {
		this.scheduledGoOutMinute = scheduledGoOutMinute;
	}

}
