package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaOvertimeSetting generated by hbm2java
 */
@Entity
@Table(name = "TA_OVERTIME_SETTING", catalog = "eHRM_JavaResearching")
public class TaOvertimeSetting implements java.io.Serializable {

	private Integer overtimeSettingId;
	private Serializable overtimeName;
	private Date overtimeFrom;
	private Date overtimeTo;
	private Serializable remark;
	private Set<TaEmployeeOvertimes> taEmployeeOvertimeses = new HashSet<TaEmployeeOvertimes>(0);

	public TaOvertimeSetting() {
	}

	public TaOvertimeSetting(Serializable overtimeName, Date overtimeFrom, Date overtimeTo) {
		this.overtimeName = overtimeName;
		this.overtimeFrom = overtimeFrom;
		this.overtimeTo = overtimeTo;
	}

	public TaOvertimeSetting(Serializable overtimeName, Date overtimeFrom, Date overtimeTo, Serializable remark,
			Set<TaEmployeeOvertimes> taEmployeeOvertimeses) {
		this.overtimeName = overtimeName;
		this.overtimeFrom = overtimeFrom;
		this.overtimeTo = overtimeTo;
		this.remark = remark;
		this.taEmployeeOvertimeses = taEmployeeOvertimeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OVERTIME_SETTING_ID", unique = true, nullable = false)
	public Integer getOvertimeSettingId() {
		return this.overtimeSettingId;
	}

	public void setOvertimeSettingId(Integer overtimeSettingId) {
		this.overtimeSettingId = overtimeSettingId;
	}

	@Column(name = "OVERTIME_NAME", nullable = false)
	public Serializable getOvertimeName() {
		return this.overtimeName;
	}

	public void setOvertimeName(Serializable overtimeName) {
		this.overtimeName = overtimeName;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "OVERTIME_FROM", nullable = false, length = 16)
	public Date getOvertimeFrom() {
		return this.overtimeFrom;
	}

	public void setOvertimeFrom(Date overtimeFrom) {
		this.overtimeFrom = overtimeFrom;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "OVERTIME_TO", nullable = false, length = 16)
	public Date getOvertimeTo() {
		return this.overtimeTo;
	}

	public void setOvertimeTo(Date overtimeTo) {
		this.overtimeTo = overtimeTo;
	}

	@Column(name = "REMARK")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taOvertimeSetting")
	public Set<TaEmployeeOvertimes> getTaEmployeeOvertimeses() {
		return this.taEmployeeOvertimeses;
	}

	public void setTaEmployeeOvertimeses(Set<TaEmployeeOvertimes> taEmployeeOvertimeses) {
		this.taEmployeeOvertimeses = taEmployeeOvertimeses;
	}

}
