package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaShiftChangeSetting generated by hbm2java
 */
@Entity
@Table(name = "TA_SHIFT_CHANGE_SETTING", catalog = "eHRM_JavaResearching")
public class TaShiftChangeSetting implements java.io.Serializable {

	private Integer shiftChangeSettingId;
	private TaWorkingShifts taWorkingShiftsByPreviousWorkingShiftId;
	private TaWorkingShifts taWorkingShiftsByMovedWorkingShiftId;
	private TaWorkingShifts taWorkingShiftsByCurrentWorkingShiftId;
	private Date startDate;
	private Date endDate;
	private Serializable remark;

	public TaShiftChangeSetting() {
	}

	public TaShiftChangeSetting(TaWorkingShifts taWorkingShiftsByMovedWorkingShiftId,
			TaWorkingShifts taWorkingShiftsByCurrentWorkingShiftId, Date startDate) {
		this.taWorkingShiftsByMovedWorkingShiftId = taWorkingShiftsByMovedWorkingShiftId;
		this.taWorkingShiftsByCurrentWorkingShiftId = taWorkingShiftsByCurrentWorkingShiftId;
		this.startDate = startDate;
	}

	public TaShiftChangeSetting(TaWorkingShifts taWorkingShiftsByPreviousWorkingShiftId,
			TaWorkingShifts taWorkingShiftsByMovedWorkingShiftId,
			TaWorkingShifts taWorkingShiftsByCurrentWorkingShiftId, Date startDate, Date endDate, Serializable remark) {
		this.taWorkingShiftsByPreviousWorkingShiftId = taWorkingShiftsByPreviousWorkingShiftId;
		this.taWorkingShiftsByMovedWorkingShiftId = taWorkingShiftsByMovedWorkingShiftId;
		this.taWorkingShiftsByCurrentWorkingShiftId = taWorkingShiftsByCurrentWorkingShiftId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SHIFT_CHANGE_SETTING_ID", unique = true, nullable = false)
	public Integer getShiftChangeSettingId() {
		return this.shiftChangeSettingId;
	}

	public void setShiftChangeSettingId(Integer shiftChangeSettingId) {
		this.shiftChangeSettingId = shiftChangeSettingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PREVIOUS_WORKING_SHIFT_ID")
	public TaWorkingShifts getTaWorkingShiftsByPreviousWorkingShiftId() {
		return this.taWorkingShiftsByPreviousWorkingShiftId;
	}

	public void setTaWorkingShiftsByPreviousWorkingShiftId(TaWorkingShifts taWorkingShiftsByPreviousWorkingShiftId) {
		this.taWorkingShiftsByPreviousWorkingShiftId = taWorkingShiftsByPreviousWorkingShiftId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOVED_WORKING_SHIFT_ID", nullable = false)
	public TaWorkingShifts getTaWorkingShiftsByMovedWorkingShiftId() {
		return this.taWorkingShiftsByMovedWorkingShiftId;
	}

	public void setTaWorkingShiftsByMovedWorkingShiftId(TaWorkingShifts taWorkingShiftsByMovedWorkingShiftId) {
		this.taWorkingShiftsByMovedWorkingShiftId = taWorkingShiftsByMovedWorkingShiftId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENT_WORKING_SHIFT_ID", nullable = false)
	public TaWorkingShifts getTaWorkingShiftsByCurrentWorkingShiftId() {
		return this.taWorkingShiftsByCurrentWorkingShiftId;
	}

	public void setTaWorkingShiftsByCurrentWorkingShiftId(TaWorkingShifts taWorkingShiftsByCurrentWorkingShiftId) {
		this.taWorkingShiftsByCurrentWorkingShiftId = taWorkingShiftsByCurrentWorkingShiftId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "REMARK")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

}
