package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaWorkingCalendars generated by hbm2java
 */
@Entity
@Table(name = "TA_WORKING_CALENDARS", catalog = "eHRM_JavaResearching")
public class TaWorkingCalendars implements java.io.Serializable {

	private Integer workingCalendarId;
	private Units units;
	private Serializable dayoffTitle;
	private Date companyDayoff;
	private Serializable remark;

	public TaWorkingCalendars() {
	}

	public TaWorkingCalendars(Date companyDayoff) {
		this.companyDayoff = companyDayoff;
	}

	public TaWorkingCalendars(Units units, Serializable dayoffTitle, Date companyDayoff, Serializable remark) {
		this.units = units;
		this.dayoffTitle = dayoffTitle;
		this.companyDayoff = companyDayoff;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "WORKING_CALENDAR_ID", unique = true, nullable = false)
	public Integer getWorkingCalendarId() {
		return this.workingCalendarId;
	}

	public void setWorkingCalendarId(Integer workingCalendarId) {
		this.workingCalendarId = workingCalendarId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_ID")
	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	@Column(name = "DAYOFF_TITLE")
	public Serializable getDayoffTitle() {
		return this.dayoffTitle;
	}

	public void setDayoffTitle(Serializable dayoffTitle) {
		this.dayoffTitle = dayoffTitle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COMPANY_DAYOFF", nullable = false, length = 10)
	public Date getCompanyDayoff() {
		return this.companyDayoff;
	}

	public void setCompanyDayoff(Date companyDayoff) {
		this.companyDayoff = companyDayoff;
	}

	@Column(name = "REMARK")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

}
