package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaWorkingTypes generated by hbm2java
 */
@Entity
@Table(name = "TA_WORKING_TYPES", catalog = "eHRM_JavaResearching")
public class TaWorkingTypes implements java.io.Serializable {

	private Integer workingTypeId;
	private Serializable workingTypeName;
	private double coefficient;
	private Boolean isNightShift;
	private Boolean isProbation;
	private Boolean isTraining;
	private Boolean isHoliday;
	private Set<TaEmployeeTimesheets> taEmployeeTimesheetses = new HashSet<TaEmployeeTimesheets>(0);

	public TaWorkingTypes() {
	}

	public TaWorkingTypes(Serializable workingTypeName, double coefficient) {
		this.workingTypeName = workingTypeName;
		this.coefficient = coefficient;
	}

	public TaWorkingTypes(Serializable workingTypeName, double coefficient, Boolean isNightShift, Boolean isProbation,
			Boolean isTraining, Boolean isHoliday, Set<TaEmployeeTimesheets> taEmployeeTimesheetses) {
		this.workingTypeName = workingTypeName;
		this.coefficient = coefficient;
		this.isNightShift = isNightShift;
		this.isProbation = isProbation;
		this.isTraining = isTraining;
		this.isHoliday = isHoliday;
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "WORKING_TYPE_ID", unique = true, nullable = false)
	public Integer getWorkingTypeId() {
		return this.workingTypeId;
	}

	public void setWorkingTypeId(Integer workingTypeId) {
		this.workingTypeId = workingTypeId;
	}

	@Column(name = "WORKING_TYPE_NAME", nullable = false)
	public Serializable getWorkingTypeName() {
		return this.workingTypeName;
	}

	public void setWorkingTypeName(Serializable workingTypeName) {
		this.workingTypeName = workingTypeName;
	}

	@Column(name = "COEFFICIENT", nullable = false, precision = 53, scale = 0)
	public double getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(double coefficient) {
		this.coefficient = coefficient;
	}

	@Column(name = "IS_NIGHT_SHIFT")
	public Boolean getIsNightShift() {
		return this.isNightShift;
	}

	public void setIsNightShift(Boolean isNightShift) {
		this.isNightShift = isNightShift;
	}

	@Column(name = "IS_PROBATION")
	public Boolean getIsProbation() {
		return this.isProbation;
	}

	public void setIsProbation(Boolean isProbation) {
		this.isProbation = isProbation;
	}

	@Column(name = "IS_TRAINING")
	public Boolean getIsTraining() {
		return this.isTraining;
	}

	public void setIsTraining(Boolean isTraining) {
		this.isTraining = isTraining;
	}

	@Column(name = "IS_HOLIDAY")
	public Boolean getIsHoliday() {
		return this.isHoliday;
	}

	public void setIsHoliday(Boolean isHoliday) {
		this.isHoliday = isHoliday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taWorkingTypes")
	public Set<TaEmployeeTimesheets> getTaEmployeeTimesheetses() {
		return this.taEmployeeTimesheetses;
	}

	public void setTaEmployeeTimesheetses(Set<TaEmployeeTimesheets> taEmployeeTimesheetses) {
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
	}

}
