package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TimeSheetHistories generated by hbm2java
 */
@Entity
@Table(name = "TIME_SHEET_HISTORIES", catalog = "eHRM_JavaResearching")
public class TimeSheetHistories implements java.io.Serializable {

	private Integer timeSheetHistoryId;
	private Projects projects;
	private TimeSheets timeSheets;
	private BigDecimal hours;
	private Serializable description;

	public TimeSheetHistories() {
	}

	public TimeSheetHistories(Projects projects, TimeSheets timeSheets, BigDecimal hours) {
		this.projects = projects;
		this.timeSheets = timeSheets;
		this.hours = hours;
	}

	public TimeSheetHistories(Projects projects, TimeSheets timeSheets, BigDecimal hours, Serializable description) {
		this.projects = projects;
		this.timeSheets = timeSheets;
		this.hours = hours;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TIME_SHEET_HISTORY_ID", unique = true, nullable = false)
	public Integer getTimeSheetHistoryId() {
		return this.timeSheetHistoryId;
	}

	public void setTimeSheetHistoryId(Integer timeSheetHistoryId) {
		this.timeSheetHistoryId = timeSheetHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIME_SHEET_ID", nullable = false)
	public TimeSheets getTimeSheets() {
		return this.timeSheets;
	}

	public void setTimeSheets(TimeSheets timeSheets) {
		this.timeSheets = timeSheets;
	}

	@Column(name = "HOURS", nullable = false, precision = 8)
	public BigDecimal getHours() {
		return this.hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

}
