package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeSheets generated by hbm2java
 */
@Entity
@Table(name = "TIME_SHEETS", catalog = "eHRM_JavaResearching")
public class TimeSheets implements java.io.Serializable {

	private Integer timeSheetId;
	private Employees employees;
	private Date timeSheetDate;
	private Date timeIn;
	private Date timeOut;
	private Date realTimeIn;
	private Date realTimeOut;
	private Serializable description;
	private Boolean isApproved;
	private Boolean isModifiedbyStaff;
	private BigDecimal otHour;
	private BigDecimal lunchHour;
	private BigDecimal totalTime;
	private Long countAproval;
	private Date startOtTime;
	private Date endOtTime;
	private Boolean gotTimeattendanceData;
	private Integer flagColor;
	private Date dateApproval;
	private Set<TaEmployeeTimesheets> taEmployeeTimesheetses = new HashSet<TaEmployeeTimesheets>(0);
	private Set<LogTimeSheet> logTimeSheets = new HashSet<LogTimeSheet>(0);
	private Set<OtTravel> otTravels = new HashSet<OtTravel>(0);
	private Set<TimeSheetHistories> timeSheetHistorieses = new HashSet<TimeSheetHistories>(0);

	public TimeSheets() {
	}

	public TimeSheets(Employees employees, Date timeSheetDate) {
		this.employees = employees;
		this.timeSheetDate = timeSheetDate;
	}

	public TimeSheets(Employees employees, Date timeSheetDate, Date timeIn, Date timeOut, Date realTimeIn,
			Date realTimeOut, Serializable description, Boolean isApproved, Boolean isModifiedbyStaff,
			BigDecimal otHour, BigDecimal lunchHour, BigDecimal totalTime, Long countAproval, Date startOtTime,
			Date endOtTime, Boolean gotTimeattendanceData, Integer flagColor, Date dateApproval,
			Set<TaEmployeeTimesheets> taEmployeeTimesheetses, Set<LogTimeSheet> logTimeSheets, Set<OtTravel> otTravels,
			Set<TimeSheetHistories> timeSheetHistorieses) {
		this.employees = employees;
		this.timeSheetDate = timeSheetDate;
		this.timeIn = timeIn;
		this.timeOut = timeOut;
		this.realTimeIn = realTimeIn;
		this.realTimeOut = realTimeOut;
		this.description = description;
		this.isApproved = isApproved;
		this.isModifiedbyStaff = isModifiedbyStaff;
		this.otHour = otHour;
		this.lunchHour = lunchHour;
		this.totalTime = totalTime;
		this.countAproval = countAproval;
		this.startOtTime = startOtTime;
		this.endOtTime = endOtTime;
		this.gotTimeattendanceData = gotTimeattendanceData;
		this.flagColor = flagColor;
		this.dateApproval = dateApproval;
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
		this.logTimeSheets = logTimeSheets;
		this.otTravels = otTravels;
		this.timeSheetHistorieses = timeSheetHistorieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TIME_SHEET_ID", unique = true, nullable = false)
	public Integer getTimeSheetId() {
		return this.timeSheetId;
	}

	public void setTimeSheetId(Integer timeSheetId) {
		this.timeSheetId = timeSheetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIME_SHEET_DATE", nullable = false, length = 10)
	public Date getTimeSheetDate() {
		return this.timeSheetDate;
	}

	public void setTimeSheetDate(Date timeSheetDate) {
		this.timeSheetDate = timeSheetDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_IN", length = 23)
	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME_OUT", length = 23)
	public Date getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(Date timeOut) {
		this.timeOut = timeOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REAL_TIME_IN", length = 23)
	public Date getRealTimeIn() {
		return this.realTimeIn;
	}

	public void setRealTimeIn(Date realTimeIn) {
		this.realTimeIn = realTimeIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REAL_TIME_OUT", length = 23)
	public Date getRealTimeOut() {
		return this.realTimeOut;
	}

	public void setRealTimeOut(Date realTimeOut) {
		this.realTimeOut = realTimeOut;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "IS_APPROVED")
	public Boolean getIsApproved() {
		return this.isApproved;
	}

	public void setIsApproved(Boolean isApproved) {
		this.isApproved = isApproved;
	}

	@Column(name = "IS_MODIFIEDBY_STAFF")
	public Boolean getIsModifiedbyStaff() {
		return this.isModifiedbyStaff;
	}

	public void setIsModifiedbyStaff(Boolean isModifiedbyStaff) {
		this.isModifiedbyStaff = isModifiedbyStaff;
	}

	@Column(name = "OT_HOUR", precision = 8)
	public BigDecimal getOtHour() {
		return this.otHour;
	}

	public void setOtHour(BigDecimal otHour) {
		this.otHour = otHour;
	}

	@Column(name = "LUNCH_HOUR", precision = 8)
	public BigDecimal getLunchHour() {
		return this.lunchHour;
	}

	public void setLunchHour(BigDecimal lunchHour) {
		this.lunchHour = lunchHour;
	}

	@Column(name = "TOTAL_TIME", precision = 8)
	public BigDecimal getTotalTime() {
		return this.totalTime;
	}

	public void setTotalTime(BigDecimal totalTime) {
		this.totalTime = totalTime;
	}

	@Column(name = "COUNT_APROVAL", precision = 18, scale = 0)
	public Long getCountAproval() {
		return this.countAproval;
	}

	public void setCountAproval(Long countAproval) {
		this.countAproval = countAproval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_OT_TIME", length = 23)
	public Date getStartOtTime() {
		return this.startOtTime;
	}

	public void setStartOtTime(Date startOtTime) {
		this.startOtTime = startOtTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_OT_TIME", length = 23)
	public Date getEndOtTime() {
		return this.endOtTime;
	}

	public void setEndOtTime(Date endOtTime) {
		this.endOtTime = endOtTime;
	}

	@Column(name = "GOT_TIMEATTENDANCE_DATA")
	public Boolean getGotTimeattendanceData() {
		return this.gotTimeattendanceData;
	}

	public void setGotTimeattendanceData(Boolean gotTimeattendanceData) {
		this.gotTimeattendanceData = gotTimeattendanceData;
	}

	@Column(name = "FLAG_COLOR")
	public Integer getFlagColor() {
		return this.flagColor;
	}

	public void setFlagColor(Integer flagColor) {
		this.flagColor = flagColor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_APPROVAL", length = 23)
	public Date getDateApproval() {
		return this.dateApproval;
	}

	public void setDateApproval(Date dateApproval) {
		this.dateApproval = dateApproval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeSheets")
	public Set<TaEmployeeTimesheets> getTaEmployeeTimesheetses() {
		return this.taEmployeeTimesheetses;
	}

	public void setTaEmployeeTimesheetses(Set<TaEmployeeTimesheets> taEmployeeTimesheetses) {
		this.taEmployeeTimesheetses = taEmployeeTimesheetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeSheets")
	public Set<LogTimeSheet> getLogTimeSheets() {
		return this.logTimeSheets;
	}

	public void setLogTimeSheets(Set<LogTimeSheet> logTimeSheets) {
		this.logTimeSheets = logTimeSheets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeSheets")
	public Set<OtTravel> getOtTravels() {
		return this.otTravels;
	}

	public void setOtTravels(Set<OtTravel> otTravels) {
		this.otTravels = otTravels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeSheets")
	public Set<TimeSheetHistories> getTimeSheetHistorieses() {
		return this.timeSheetHistorieses;
	}

	public void setTimeSheetHistorieses(Set<TimeSheetHistories> timeSheetHistorieses) {
		this.timeSheetHistorieses = timeSheetHistorieses;
	}

}
