package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmpEmployeeIncomeTotalStatsId generated by hbm2java
 */
@Embeddable
public class TmpEmployeeIncomeTotalStatsId implements java.io.Serializable {

	private int employeeIncomeTotalStatsId;
	private BigDecimal basicSalary;
	private BigDecimal employeeContribution;
	private BigDecimal employerContribution;
	private BigDecimal impost;
	private BigDecimal totalAffectedIncome;
	private BigDecimal totalNetIncome;
	private BigDecimal totalMassIncome;
	private BigDecimal workingSalary;
	private BigDecimal salaryBeforePit;
	private Integer numberOfDependants;
	private BigDecimal decreaseFamily;
	private BigDecimal decreaseOtOther;
	private BigDecimal decreaseOneself;
	private BigDecimal decreaseDependants;
	private BigDecimal salaryAfterDiscountPit;
	private Integer currencies;
	private BigDecimal employeeSi;
	private BigDecimal employeeHi;
	private BigDecimal employeeUi;
	private BigDecimal employeeUnion;
	private BigDecimal employerSi;
	private BigDecimal employerHi;
	private BigDecimal employerUi;
	private BigDecimal employerUnion;
	private BigDecimal taxableIncome;
	private BigDecimal insuranceIncome;
	private BigDecimal overtimeIncome;
	private Integer employeeId;
	private Integer periodId;

	public TmpEmployeeIncomeTotalStatsId() {
	}

	public TmpEmployeeIncomeTotalStatsId(int employeeIncomeTotalStatsId, BigDecimal employeeUi) {
		this.employeeIncomeTotalStatsId = employeeIncomeTotalStatsId;
		this.employeeUi = employeeUi;
	}

	public TmpEmployeeIncomeTotalStatsId(int employeeIncomeTotalStatsId, BigDecimal basicSalary,
			BigDecimal employeeContribution, BigDecimal employerContribution, BigDecimal impost,
			BigDecimal totalAffectedIncome, BigDecimal totalNetIncome, BigDecimal totalMassIncome,
			BigDecimal workingSalary, BigDecimal salaryBeforePit, Integer numberOfDependants, BigDecimal decreaseFamily,
			BigDecimal decreaseOtOther, BigDecimal decreaseOneself, BigDecimal decreaseDependants,
			BigDecimal salaryAfterDiscountPit, Integer currencies, BigDecimal employeeSi, BigDecimal employeeHi,
			BigDecimal employeeUi, BigDecimal employeeUnion, BigDecimal employerSi, BigDecimal employerHi,
			BigDecimal employerUi, BigDecimal employerUnion, BigDecimal taxableIncome, BigDecimal insuranceIncome,
			BigDecimal overtimeIncome, Integer employeeId, Integer periodId) {
		this.employeeIncomeTotalStatsId = employeeIncomeTotalStatsId;
		this.basicSalary = basicSalary;
		this.employeeContribution = employeeContribution;
		this.employerContribution = employerContribution;
		this.impost = impost;
		this.totalAffectedIncome = totalAffectedIncome;
		this.totalNetIncome = totalNetIncome;
		this.totalMassIncome = totalMassIncome;
		this.workingSalary = workingSalary;
		this.salaryBeforePit = salaryBeforePit;
		this.numberOfDependants = numberOfDependants;
		this.decreaseFamily = decreaseFamily;
		this.decreaseOtOther = decreaseOtOther;
		this.decreaseOneself = decreaseOneself;
		this.decreaseDependants = decreaseDependants;
		this.salaryAfterDiscountPit = salaryAfterDiscountPit;
		this.currencies = currencies;
		this.employeeSi = employeeSi;
		this.employeeHi = employeeHi;
		this.employeeUi = employeeUi;
		this.employeeUnion = employeeUnion;
		this.employerSi = employerSi;
		this.employerHi = employerHi;
		this.employerUi = employerUi;
		this.employerUnion = employerUnion;
		this.taxableIncome = taxableIncome;
		this.insuranceIncome = insuranceIncome;
		this.overtimeIncome = overtimeIncome;
		this.employeeId = employeeId;
		this.periodId = periodId;
	}

	@Column(name = "EMPLOYEE_INCOME_TOTAL_STATS_ID", nullable = false)
	public int getEmployeeIncomeTotalStatsId() {
		return this.employeeIncomeTotalStatsId;
	}

	public void setEmployeeIncomeTotalStatsId(int employeeIncomeTotalStatsId) {
		this.employeeIncomeTotalStatsId = employeeIncomeTotalStatsId;
	}

	@Column(name = "BASIC_SALARY", precision = 18, scale = 10)
	public BigDecimal getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(BigDecimal basicSalary) {
		this.basicSalary = basicSalary;
	}

	@Column(name = "EMPLOYEE_CONTRIBUTION", precision = 18, scale = 6)
	public BigDecimal getEmployeeContribution() {
		return this.employeeContribution;
	}

	public void setEmployeeContribution(BigDecimal employeeContribution) {
		this.employeeContribution = employeeContribution;
	}

	@Column(name = "EMPLOYER_CONTRIBUTION", precision = 18, scale = 6)
	public BigDecimal getEmployerContribution() {
		return this.employerContribution;
	}

	public void setEmployerContribution(BigDecimal employerContribution) {
		this.employerContribution = employerContribution;
	}

	@Column(name = "IMPOST", precision = 18, scale = 6)
	public BigDecimal getImpost() {
		return this.impost;
	}

	public void setImpost(BigDecimal impost) {
		this.impost = impost;
	}

	@Column(name = "TOTAL_AFFECTED_INCOME", precision = 18, scale = 6)
	public BigDecimal getTotalAffectedIncome() {
		return this.totalAffectedIncome;
	}

	public void setTotalAffectedIncome(BigDecimal totalAffectedIncome) {
		this.totalAffectedIncome = totalAffectedIncome;
	}

	@Column(name = "TOTAL_NET_INCOME", precision = 18, scale = 6)
	public BigDecimal getTotalNetIncome() {
		return this.totalNetIncome;
	}

	public void setTotalNetIncome(BigDecimal totalNetIncome) {
		this.totalNetIncome = totalNetIncome;
	}

	@Column(name = "TOTAL_MASS_INCOME", precision = 18, scale = 6)
	public BigDecimal getTotalMassIncome() {
		return this.totalMassIncome;
	}

	public void setTotalMassIncome(BigDecimal totalMassIncome) {
		this.totalMassIncome = totalMassIncome;
	}

	@Column(name = "WORKING_SALARY", precision = 18, scale = 6)
	public BigDecimal getWorkingSalary() {
		return this.workingSalary;
	}

	public void setWorkingSalary(BigDecimal workingSalary) {
		this.workingSalary = workingSalary;
	}

	@Column(name = "SALARY_BEFORE_PIT", precision = 18, scale = 6)
	public BigDecimal getSalaryBeforePit() {
		return this.salaryBeforePit;
	}

	public void setSalaryBeforePit(BigDecimal salaryBeforePit) {
		this.salaryBeforePit = salaryBeforePit;
	}

	@Column(name = "NUMBER_OF_DEPENDANTS")
	public Integer getNumberOfDependants() {
		return this.numberOfDependants;
	}

	public void setNumberOfDependants(Integer numberOfDependants) {
		this.numberOfDependants = numberOfDependants;
	}

	@Column(name = "DECREASE_FAMILY", precision = 18, scale = 6)
	public BigDecimal getDecreaseFamily() {
		return this.decreaseFamily;
	}

	public void setDecreaseFamily(BigDecimal decreaseFamily) {
		this.decreaseFamily = decreaseFamily;
	}

	@Column(name = "DECREASE_OT_OTHER", precision = 18, scale = 6)
	public BigDecimal getDecreaseOtOther() {
		return this.decreaseOtOther;
	}

	public void setDecreaseOtOther(BigDecimal decreaseOtOther) {
		this.decreaseOtOther = decreaseOtOther;
	}

	@Column(name = "DECREASE_ONESELF", precision = 18, scale = 6)
	public BigDecimal getDecreaseOneself() {
		return this.decreaseOneself;
	}

	public void setDecreaseOneself(BigDecimal decreaseOneself) {
		this.decreaseOneself = decreaseOneself;
	}

	@Column(name = "DECREASE_DEPENDANTS", precision = 18, scale = 6)
	public BigDecimal getDecreaseDependants() {
		return this.decreaseDependants;
	}

	public void setDecreaseDependants(BigDecimal decreaseDependants) {
		this.decreaseDependants = decreaseDependants;
	}

	@Column(name = "SALARY_AFTER_DISCOUNT_PIT", precision = 18, scale = 6)
	public BigDecimal getSalaryAfterDiscountPit() {
		return this.salaryAfterDiscountPit;
	}

	public void setSalaryAfterDiscountPit(BigDecimal salaryAfterDiscountPit) {
		this.salaryAfterDiscountPit = salaryAfterDiscountPit;
	}

	@Column(name = "CURRENCIES")
	public Integer getCurrencies() {
		return this.currencies;
	}

	public void setCurrencies(Integer currencies) {
		this.currencies = currencies;
	}

	@Column(name = "EMPLOYEE_SI", precision = 18, scale = 6)
	public BigDecimal getEmployeeSi() {
		return this.employeeSi;
	}

	public void setEmployeeSi(BigDecimal employeeSi) {
		this.employeeSi = employeeSi;
	}

	@Column(name = "EMPLOYEE_HI", precision = 18, scale = 6)
	public BigDecimal getEmployeeHi() {
		return this.employeeHi;
	}

	public void setEmployeeHi(BigDecimal employeeHi) {
		this.employeeHi = employeeHi;
	}

	@Column(name = "EMPLOYEE_UI", nullable = false, precision = 18, scale = 6)
	public BigDecimal getEmployeeUi() {
		return this.employeeUi;
	}

	public void setEmployeeUi(BigDecimal employeeUi) {
		this.employeeUi = employeeUi;
	}

	@Column(name = "EMPLOYEE_UNION", precision = 18, scale = 6)
	public BigDecimal getEmployeeUnion() {
		return this.employeeUnion;
	}

	public void setEmployeeUnion(BigDecimal employeeUnion) {
		this.employeeUnion = employeeUnion;
	}

	@Column(name = "EMPLOYER_SI", precision = 18, scale = 6)
	public BigDecimal getEmployerSi() {
		return this.employerSi;
	}

	public void setEmployerSi(BigDecimal employerSi) {
		this.employerSi = employerSi;
	}

	@Column(name = "EMPLOYER_HI", precision = 18, scale = 6)
	public BigDecimal getEmployerHi() {
		return this.employerHi;
	}

	public void setEmployerHi(BigDecimal employerHi) {
		this.employerHi = employerHi;
	}

	@Column(name = "EMPLOYER_UI", precision = 18, scale = 6)
	public BigDecimal getEmployerUi() {
		return this.employerUi;
	}

	public void setEmployerUi(BigDecimal employerUi) {
		this.employerUi = employerUi;
	}

	@Column(name = "EMPLOYER_UNION", precision = 18, scale = 6)
	public BigDecimal getEmployerUnion() {
		return this.employerUnion;
	}

	public void setEmployerUnion(BigDecimal employerUnion) {
		this.employerUnion = employerUnion;
	}

	@Column(name = "TAXABLE_INCOME", precision = 18, scale = 6)
	public BigDecimal getTaxableIncome() {
		return this.taxableIncome;
	}

	public void setTaxableIncome(BigDecimal taxableIncome) {
		this.taxableIncome = taxableIncome;
	}

	@Column(name = "INSURANCE_INCOME", precision = 18, scale = 6)
	public BigDecimal getInsuranceIncome() {
		return this.insuranceIncome;
	}

	public void setInsuranceIncome(BigDecimal insuranceIncome) {
		this.insuranceIncome = insuranceIncome;
	}

	@Column(name = "OVERTIME_INCOME", precision = 18, scale = 6)
	public BigDecimal getOvertimeIncome() {
		return this.overtimeIncome;
	}

	public void setOvertimeIncome(BigDecimal overtimeIncome) {
		this.overtimeIncome = overtimeIncome;
	}

	@Column(name = "EMPLOYEE_ID")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "PERIOD_ID")
	public Integer getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(Integer periodId) {
		this.periodId = periodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpEmployeeIncomeTotalStatsId))
			return false;
		TmpEmployeeIncomeTotalStatsId castOther = (TmpEmployeeIncomeTotalStatsId) other;

		return (this.getEmployeeIncomeTotalStatsId() == castOther.getEmployeeIncomeTotalStatsId())
				&& ((this.getBasicSalary() == castOther.getBasicSalary())
						|| (this.getBasicSalary() != null && castOther.getBasicSalary() != null
								&& this.getBasicSalary().equals(castOther.getBasicSalary())))
				&& ((this.getEmployeeContribution() == castOther.getEmployeeContribution())
						|| (this.getEmployeeContribution() != null && castOther.getEmployeeContribution() != null
								&& this.getEmployeeContribution().equals(castOther.getEmployeeContribution())))
				&& ((this.getEmployerContribution() == castOther.getEmployerContribution())
						|| (this.getEmployerContribution() != null && castOther.getEmployerContribution() != null
								&& this.getEmployerContribution().equals(castOther.getEmployerContribution())))
				&& ((this.getImpost() == castOther.getImpost()) || (this.getImpost() != null
						&& castOther.getImpost() != null && this.getImpost().equals(castOther.getImpost())))
				&& ((this.getTotalAffectedIncome() == castOther.getTotalAffectedIncome())
						|| (this.getTotalAffectedIncome() != null && castOther.getTotalAffectedIncome() != null
								&& this.getTotalAffectedIncome().equals(castOther.getTotalAffectedIncome())))
				&& ((this.getTotalNetIncome() == castOther.getTotalNetIncome())
						|| (this.getTotalNetIncome() != null && castOther.getTotalNetIncome() != null
								&& this.getTotalNetIncome().equals(castOther.getTotalNetIncome())))
				&& ((this.getTotalMassIncome() == castOther.getTotalMassIncome())
						|| (this.getTotalMassIncome() != null && castOther.getTotalMassIncome() != null
								&& this.getTotalMassIncome().equals(castOther.getTotalMassIncome())))
				&& ((this.getWorkingSalary() == castOther.getWorkingSalary())
						|| (this.getWorkingSalary() != null && castOther.getWorkingSalary() != null
								&& this.getWorkingSalary().equals(castOther.getWorkingSalary())))
				&& ((this.getSalaryBeforePit() == castOther.getSalaryBeforePit())
						|| (this.getSalaryBeforePit() != null && castOther.getSalaryBeforePit() != null
								&& this.getSalaryBeforePit().equals(castOther.getSalaryBeforePit())))
				&& ((this.getNumberOfDependants() == castOther.getNumberOfDependants())
						|| (this.getNumberOfDependants() != null && castOther.getNumberOfDependants() != null
								&& this.getNumberOfDependants().equals(castOther.getNumberOfDependants())))
				&& ((this.getDecreaseFamily() == castOther.getDecreaseFamily())
						|| (this.getDecreaseFamily() != null && castOther.getDecreaseFamily() != null
								&& this.getDecreaseFamily().equals(castOther.getDecreaseFamily())))
				&& ((this.getDecreaseOtOther() == castOther.getDecreaseOtOther())
						|| (this.getDecreaseOtOther() != null && castOther.getDecreaseOtOther() != null
								&& this.getDecreaseOtOther().equals(castOther.getDecreaseOtOther())))
				&& ((this.getDecreaseOneself() == castOther.getDecreaseOneself())
						|| (this.getDecreaseOneself() != null && castOther.getDecreaseOneself() != null
								&& this.getDecreaseOneself().equals(castOther.getDecreaseOneself())))
				&& ((this.getDecreaseDependants() == castOther.getDecreaseDependants())
						|| (this.getDecreaseDependants() != null && castOther.getDecreaseDependants() != null
								&& this.getDecreaseDependants().equals(castOther.getDecreaseDependants())))
				&& ((this.getSalaryAfterDiscountPit() == castOther.getSalaryAfterDiscountPit())
						|| (this.getSalaryAfterDiscountPit() != null && castOther.getSalaryAfterDiscountPit() != null
								&& this.getSalaryAfterDiscountPit().equals(castOther.getSalaryAfterDiscountPit())))
				&& ((this.getCurrencies() == castOther.getCurrencies()) || (this.getCurrencies() != null
						&& castOther.getCurrencies() != null && this.getCurrencies().equals(castOther.getCurrencies())))
				&& ((this.getEmployeeSi() == castOther.getEmployeeSi()) || (this.getEmployeeSi() != null
						&& castOther.getEmployeeSi() != null && this.getEmployeeSi().equals(castOther.getEmployeeSi())))
				&& ((this.getEmployeeHi() == castOther.getEmployeeHi()) || (this.getEmployeeHi() != null
						&& castOther.getEmployeeHi() != null && this.getEmployeeHi().equals(castOther.getEmployeeHi())))
				&& ((this.getEmployeeUi() == castOther.getEmployeeUi()) || (this.getEmployeeUi() != null
						&& castOther.getEmployeeUi() != null && this.getEmployeeUi().equals(castOther.getEmployeeUi())))
				&& ((this.getEmployeeUnion() == castOther.getEmployeeUnion())
						|| (this.getEmployeeUnion() != null && castOther.getEmployeeUnion() != null
								&& this.getEmployeeUnion().equals(castOther.getEmployeeUnion())))
				&& ((this.getEmployerSi() == castOther.getEmployerSi()) || (this.getEmployerSi() != null
						&& castOther.getEmployerSi() != null && this.getEmployerSi().equals(castOther.getEmployerSi())))
				&& ((this.getEmployerHi() == castOther.getEmployerHi()) || (this.getEmployerHi() != null
						&& castOther.getEmployerHi() != null && this.getEmployerHi().equals(castOther.getEmployerHi())))
				&& ((this.getEmployerUi() == castOther.getEmployerUi()) || (this.getEmployerUi() != null
						&& castOther.getEmployerUi() != null && this.getEmployerUi().equals(castOther.getEmployerUi())))
				&& ((this.getEmployerUnion() == castOther.getEmployerUnion())
						|| (this.getEmployerUnion() != null && castOther.getEmployerUnion() != null
								&& this.getEmployerUnion().equals(castOther.getEmployerUnion())))
				&& ((this.getTaxableIncome() == castOther.getTaxableIncome())
						|| (this.getTaxableIncome() != null && castOther.getTaxableIncome() != null
								&& this.getTaxableIncome().equals(castOther.getTaxableIncome())))
				&& ((this.getInsuranceIncome() == castOther.getInsuranceIncome())
						|| (this.getInsuranceIncome() != null && castOther.getInsuranceIncome() != null
								&& this.getInsuranceIncome().equals(castOther.getInsuranceIncome())))
				&& ((this.getOvertimeIncome() == castOther.getOvertimeIncome())
						|| (this.getOvertimeIncome() != null && castOther.getOvertimeIncome() != null
								&& this.getOvertimeIncome().equals(castOther.getOvertimeIncome())))
				&& ((this.getEmployeeId() == castOther.getEmployeeId()) || (this.getEmployeeId() != null
						&& castOther.getEmployeeId() != null && this.getEmployeeId().equals(castOther.getEmployeeId())))
				&& ((this.getPeriodId() == castOther.getPeriodId()) || (this.getPeriodId() != null
						&& castOther.getPeriodId() != null && this.getPeriodId().equals(castOther.getPeriodId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmployeeIncomeTotalStatsId();
		result = 37 * result + (getBasicSalary() == null ? 0 : this.getBasicSalary().hashCode());
		result = 37 * result + (getEmployeeContribution() == null ? 0 : this.getEmployeeContribution().hashCode());
		result = 37 * result + (getEmployerContribution() == null ? 0 : this.getEmployerContribution().hashCode());
		result = 37 * result + (getImpost() == null ? 0 : this.getImpost().hashCode());
		result = 37 * result + (getTotalAffectedIncome() == null ? 0 : this.getTotalAffectedIncome().hashCode());
		result = 37 * result + (getTotalNetIncome() == null ? 0 : this.getTotalNetIncome().hashCode());
		result = 37 * result + (getTotalMassIncome() == null ? 0 : this.getTotalMassIncome().hashCode());
		result = 37 * result + (getWorkingSalary() == null ? 0 : this.getWorkingSalary().hashCode());
		result = 37 * result + (getSalaryBeforePit() == null ? 0 : this.getSalaryBeforePit().hashCode());
		result = 37 * result + (getNumberOfDependants() == null ? 0 : this.getNumberOfDependants().hashCode());
		result = 37 * result + (getDecreaseFamily() == null ? 0 : this.getDecreaseFamily().hashCode());
		result = 37 * result + (getDecreaseOtOther() == null ? 0 : this.getDecreaseOtOther().hashCode());
		result = 37 * result + (getDecreaseOneself() == null ? 0 : this.getDecreaseOneself().hashCode());
		result = 37 * result + (getDecreaseDependants() == null ? 0 : this.getDecreaseDependants().hashCode());
		result = 37 * result + (getSalaryAfterDiscountPit() == null ? 0 : this.getSalaryAfterDiscountPit().hashCode());
		result = 37 * result + (getCurrencies() == null ? 0 : this.getCurrencies().hashCode());
		result = 37 * result + (getEmployeeSi() == null ? 0 : this.getEmployeeSi().hashCode());
		result = 37 * result + (getEmployeeHi() == null ? 0 : this.getEmployeeHi().hashCode());
		result = 37 * result + (getEmployeeUi() == null ? 0 : this.getEmployeeUi().hashCode());
		result = 37 * result + (getEmployeeUnion() == null ? 0 : this.getEmployeeUnion().hashCode());
		result = 37 * result + (getEmployerSi() == null ? 0 : this.getEmployerSi().hashCode());
		result = 37 * result + (getEmployerHi() == null ? 0 : this.getEmployerHi().hashCode());
		result = 37 * result + (getEmployerUi() == null ? 0 : this.getEmployerUi().hashCode());
		result = 37 * result + (getEmployerUnion() == null ? 0 : this.getEmployerUnion().hashCode());
		result = 37 * result + (getTaxableIncome() == null ? 0 : this.getTaxableIncome().hashCode());
		result = 37 * result + (getInsuranceIncome() == null ? 0 : this.getInsuranceIncome().hashCode());
		result = 37 * result + (getOvertimeIncome() == null ? 0 : this.getOvertimeIncome().hashCode());
		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		result = 37 * result + (getPeriodId() == null ? 0 : this.getPeriodId().hashCode());
		return result;
	}

}
