package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpEmployeeIncomeTotalStats generated by hbm2java
 */
@Entity
@Table(name = "Tmp_EMPLOYEE_INCOME_TOTAL_STATS", catalog = "eHRM_JavaResearching")
public class TmpEmployeeIncomeTotalStats implements java.io.Serializable {

	private TmpEmployeeIncomeTotalStatsId id;

	public TmpEmployeeIncomeTotalStats() {
	}

	public TmpEmployeeIncomeTotalStats(TmpEmployeeIncomeTotalStatsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeIncomeTotalStatsId", column = @Column(name = "EMPLOYEE_INCOME_TOTAL_STATS_ID", nullable = false)),
			@AttributeOverride(name = "basicSalary", column = @Column(name = "BASIC_SALARY", precision = 18, scale = 10)),
			@AttributeOverride(name = "employeeContribution", column = @Column(name = "EMPLOYEE_CONTRIBUTION", precision = 18, scale = 6)),
			@AttributeOverride(name = "employerContribution", column = @Column(name = "EMPLOYER_CONTRIBUTION", precision = 18, scale = 6)),
			@AttributeOverride(name = "impost", column = @Column(name = "IMPOST", precision = 18, scale = 6)),
			@AttributeOverride(name = "totalAffectedIncome", column = @Column(name = "TOTAL_AFFECTED_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "totalNetIncome", column = @Column(name = "TOTAL_NET_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "totalMassIncome", column = @Column(name = "TOTAL_MASS_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "workingSalary", column = @Column(name = "WORKING_SALARY", precision = 18, scale = 6)),
			@AttributeOverride(name = "salaryBeforePit", column = @Column(name = "SALARY_BEFORE_PIT", precision = 18, scale = 6)),
			@AttributeOverride(name = "numberOfDependants", column = @Column(name = "NUMBER_OF_DEPENDANTS")),
			@AttributeOverride(name = "decreaseFamily", column = @Column(name = "DECREASE_FAMILY", precision = 18, scale = 6)),
			@AttributeOverride(name = "decreaseOtOther", column = @Column(name = "DECREASE_OT_OTHER", precision = 18, scale = 6)),
			@AttributeOverride(name = "decreaseOneself", column = @Column(name = "DECREASE_ONESELF", precision = 18, scale = 6)),
			@AttributeOverride(name = "decreaseDependants", column = @Column(name = "DECREASE_DEPENDANTS", precision = 18, scale = 6)),
			@AttributeOverride(name = "salaryAfterDiscountPit", column = @Column(name = "SALARY_AFTER_DISCOUNT_PIT", precision = 18, scale = 6)),
			@AttributeOverride(name = "currencies", column = @Column(name = "CURRENCIES")),
			@AttributeOverride(name = "employeeSi", column = @Column(name = "EMPLOYEE_SI", precision = 18, scale = 6)),
			@AttributeOverride(name = "employeeHi", column = @Column(name = "EMPLOYEE_HI", precision = 18, scale = 6)),
			@AttributeOverride(name = "employeeUi", column = @Column(name = "EMPLOYEE_UI", nullable = false, precision = 18, scale = 6)),
			@AttributeOverride(name = "employeeUnion", column = @Column(name = "EMPLOYEE_UNION", precision = 18, scale = 6)),
			@AttributeOverride(name = "employerSi", column = @Column(name = "EMPLOYER_SI", precision = 18, scale = 6)),
			@AttributeOverride(name = "employerHi", column = @Column(name = "EMPLOYER_HI", precision = 18, scale = 6)),
			@AttributeOverride(name = "employerUi", column = @Column(name = "EMPLOYER_UI", precision = 18, scale = 6)),
			@AttributeOverride(name = "employerUnion", column = @Column(name = "EMPLOYER_UNION", precision = 18, scale = 6)),
			@AttributeOverride(name = "taxableIncome", column = @Column(name = "TAXABLE_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "insuranceIncome", column = @Column(name = "INSURANCE_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "overtimeIncome", column = @Column(name = "OVERTIME_INCOME", precision = 18, scale = 6)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "EMPLOYEE_ID")),
			@AttributeOverride(name = "periodId", column = @Column(name = "PERIOD_ID")) })
	public TmpEmployeeIncomeTotalStatsId getId() {
		return this.id;
	}

	public void setId(TmpEmployeeIncomeTotalStatsId id) {
		this.id = id;
	}

}
