package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TripRequestHistories generated by hbm2java
 */
@Entity
@Table(name = "TRIP_REQUEST_HISTORIES", catalog = "eHRM_JavaResearching")
public class TripRequestHistories implements java.io.Serializable {

	private Integer tripRequestHistoryId;
	private Employees employees;
	private MasterDatas masterDatas;
	private TripRequests tripRequests;
	private Date modifiedDate;
	private Serializable comment;

	public TripRequestHistories() {
	}

	public TripRequestHistories(Employees employees, MasterDatas masterDatas, TripRequests tripRequests,
			Date modifiedDate) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.tripRequests = tripRequests;
		this.modifiedDate = modifiedDate;
	}

	public TripRequestHistories(Employees employees, MasterDatas masterDatas, TripRequests tripRequests,
			Date modifiedDate, Serializable comment) {
		this.employees = employees;
		this.masterDatas = masterDatas;
		this.tripRequests = tripRequests;
		this.modifiedDate = modifiedDate;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TRIP_REQUEST_HISTORY_ID", unique = true, nullable = false)
	public Integer getTripRequestHistoryId() {
		return this.tripRequestHistoryId;
	}

	public void setTripRequestHistoryId(Integer tripRequestHistoryId) {
		this.tripRequestHistoryId = tripRequestHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPROVER_ID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRIP_REQUEST_STATUS_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRIP_REQUEST_ID", nullable = false)
	public TripRequests getTripRequests() {
		return this.tripRequests;
	}

	public void setTripRequests(TripRequests tripRequests) {
		this.tripRequests = tripRequests;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_DATE", nullable = false, length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "COMMENT")
	public Serializable getComment() {
		return this.comment;
	}

	public void setComment(Serializable comment) {
		this.comment = comment;
	}

}
