package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", catalog = "eHRM_JavaResearching")
public class Users implements java.io.Serializable {

	private Integer userId;
	private Employees employees;
	private String userName;
	private String password;
	private boolean active;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<UserLogs> userLogses = new HashSet<UserLogs>(0);
	private Set<UserUnitRights> userUnitRightses = new HashSet<UserUnitRights>(0);
	private Set<UserModuleRights> userModuleRightses = new HashSet<UserModuleRights>(0);
	private Set<UserModuleRoles> userModuleRoleses = new HashSet<UserModuleRoles>(0);

	public Users() {
	}

	public Users(String userName, String password, boolean active) {
		this.userName = userName;
		this.password = password;
		this.active = active;
	}

	public Users(Employees employees, String userName, String password, boolean active,
			Set<UserRoles> userRoleses, Set<UserLogs> userLogses, Set<UserUnitRights> userUnitRightses,
			Set<UserModuleRights> userModuleRightses, Set<UserModuleRoles> userModuleRoleses) {
		this.employees = employees;
		this.userName = userName;
		this.password = password;
		this.active = active;
		this.userRoleses = userRoleses;
		this.userLogses = userLogses;
		this.userUnitRightses = userUnitRightses;
		this.userModuleRightses = userModuleRightses;
		this.userModuleRoleses = userModuleRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "USER_NAME", nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVE", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserLogs> getUserLogses() {
		return this.userLogses;
	}

	public void setUserLogses(Set<UserLogs> userLogses) {
		this.userLogses = userLogses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserUnitRights> getUserUnitRightses() {
		return this.userUnitRightses;
	}

	public void setUserUnitRightses(Set<UserUnitRights> userUnitRightses) {
		this.userUnitRightses = userUnitRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserModuleRights> getUserModuleRightses() {
		return this.userModuleRightses;
	}

	public void setUserModuleRightses(Set<UserModuleRights> userModuleRightses) {
		this.userModuleRightses = userModuleRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserModuleRoles> getUserModuleRoleses() {
		return this.userModuleRoleses;
	}

	public void setUserModuleRoleses(Set<UserModuleRoles> userModuleRoleses) {
		this.userModuleRoleses = userModuleRoleses;
	}

	@Override
	public String toString() {
		return "Users [userId=" + userId + ", employees=" + employees + ", userName=" + userName + ", password="
				+ password + ", active=" + active + ", userRoleses=" + userRoleses + ", userLogses=" + userLogses
				+ ", userUnitRightses=" + userUnitRightses + ", userModuleRightses=" + userModuleRightses
				+ ", userModuleRoleses=" + userModuleRoleses + "]";
	}
	
}
