package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLogs generated by hbm2java
 */
@Entity
@Table(name = "USER_LOGS", catalog = "eHRM_JavaResearching")
public class UserLogs implements java.io.Serializable {

	private Integer userLogId;
	private Users users;
	private Date updateTime;
	private Serializable description;
	private Serializable a;

	public UserLogs() {
	}

	public UserLogs(Users users, Date updateTime) {
		this.users = users;
		this.updateTime = updateTime;
	}

	public UserLogs(Users users, Date updateTime, Serializable description, Serializable a) {
		this.users = users;
		this.updateTime = updateTime;
		this.description = description;
		this.a = a;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_LOG_ID", unique = true, nullable = false)
	public Integer getUserLogId() {
		return this.userLogId;
	}

	public void setUserLogId(Integer userLogId) {
		this.userLogId = userLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", nullable = false, length = 23)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DESCRIPTION")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "a")
	public Serializable getA() {
		return this.a;
	}

	public void setA(Serializable a) {
		this.a = a;
	}

}
