package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserModuleRoles generated by hbm2java
 */
@Entity
@Table(name = "USER_MODULE_ROLES", catalog = "eHRM_JavaResearching")
public class UserModuleRoles implements java.io.Serializable {

	private Integer userModuleRoleId;
	private MasterDatas masterDatas;
	private Modules modules;
	private Users users;

	public UserModuleRoles() {
	}

	public UserModuleRoles(MasterDatas masterDatas, Modules modules, Users users) {
		this.masterDatas = masterDatas;
		this.modules = modules;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_MODULE_ROLE_ID", unique = true, nullable = false)
	public Integer getUserModuleRoleId() {
		return this.userModuleRoleId;
	}

	public void setUserModuleRoleId(Integer userModuleRoleId) {
		this.userModuleRoleId = userModuleRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID", nullable = false)
	public MasterDatas getMasterDatas() {
		return this.masterDatas;
	}

	public void setMasterDatas(MasterDatas masterDatas) {
		this.masterDatas = masterDatas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULE_ID", nullable = false)
	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
