package com.thienhoang.ehrm.model;
// Generated Apr 22, 2018 7:20:49 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VariableIntermediates generated by hbm2java
 */
@Entity
@Table(name = "VARIABLE_INTERMEDIATES", catalog = "eHRM_JavaResearching")
public class VariableIntermediates implements java.io.Serializable {

	private Integer variableIntermediateId;
	private String variableIntermediateName;
	private Set<Incomes> incomeses = new HashSet<Incomes>(0);
	private Set<Taxes> taxeses = new HashSet<Taxes>(0);

	public VariableIntermediates() {
	}

	public VariableIntermediates(String variableIntermediateName) {
		this.variableIntermediateName = variableIntermediateName;
	}

	public VariableIntermediates(String variableIntermediateName, Set<Incomes> incomeses, Set<Taxes> taxeses) {
		this.variableIntermediateName = variableIntermediateName;
		this.incomeses = incomeses;
		this.taxeses = taxeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VARIABLE_INTERMEDIATE_ID", unique = true, nullable = false)
	public Integer getVariableIntermediateId() {
		return this.variableIntermediateId;
	}

	public void setVariableIntermediateId(Integer variableIntermediateId) {
		this.variableIntermediateId = variableIntermediateId;
	}

	@Column(name = "VARIABLE_INTERMEDIATE_NAME", nullable = false)
	public String getVariableIntermediateName() {
		return this.variableIntermediateName;
	}

	public void setVariableIntermediateName(String variableIntermediateName) {
		this.variableIntermediateName = variableIntermediateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variableIntermediates")
	public Set<Incomes> getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set<Incomes> incomeses) {
		this.incomeses = incomeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "variableIntermediates")
	public Set<Taxes> getTaxeses() {
		return this.taxeses;
	}

	public void setTaxeses(Set<Taxes> taxeses) {
		this.taxeses = taxeses;
	}

}
